#!/usr/bin/env python3
"""`luria index` — render every scheme's view from its fragments.

    luria index            # write the views
    luria index --check    # exit 1 if any of them is stale

A scheme's view used to be hand-maintained: every decision-bearing branch
appended a row to the same table and a link to the same category list. That
makes it the shared-file lock [DP-2](../docs/design-principles.md#dp-2) names,
and it *drifts*, because the row duplicates data the document already owns — in
the corpus this was extracted from, 45 of 155 rows disagreed with their own
decision's status (ADR-004).

So the view is generated. Each document carries YAML frontmatter, and a scheme
declares how its documents are rendered (ADR-012):

  render = "index"      the browsable shape — a table plus per-tag pages
      docs/decisions/README.md        stub prose + category lists + the table
      docs/decisions/tags/<tag>.md    one page per tag

  render = "document"   the read-as-a-whole shape — bodies concatenated
      docs/design-principles.md       stub prose + every principle in order

Adding a document means adding ONE file. Adding a *tag* means using it in one;
`tags.yaml` only supplies ordering and a blurb, so an unlisted tag still renders.

`--check` is what makes idempotency enforceable: `luria lint` runs it, so a stale
view is a lint failure rather than a silent divergence — which only works because
a generated view's sources persist, unlike a collected one's (ADR-012).

The stub/placeholder shape is borrowed from dmarx/bench-warmers, which solved
the same problem for a brainstorming repo: prose lives in a `.stub`, the
generator substitutes `{placeholders}`, and tags get their own generated pages.
"""

from __future__ import annotations

import argparse
import os.path
import re
import sys
from pathlib import Path

import yaml

from .config import current

TITLE_RE = re.compile(r"^#\s*[A-Z]+-\d+\s*(?::|—|-)\s*")
TABLE_HEAD = "| # | Title | Status |\n|---|---|---|\n"

# Used when a project has no `README.stub`. The stub exists so prose lives in
# markdown rather than in this generator; not having written one yet shouldn't
# stop the index from building.
DEFAULT_DOCUMENT_STUB = """# Design principles

<!-- GENERATED by `luria index` — edit the fragments, not this file. -->

{principles}
"""

DEFAULT_STUB = """# Architecture decision records

<!-- GENERATED below this line by `luria index` — edit README.stub instead. -->

{categories}

{table}
"""

# A markdown link with a *relative* target: not an anchor, not root-relative,
# not a URL scheme. Those are the only ones a change of output directory moves.
RELATIVE_LINK_RE = re.compile(r"(?<=\]\()(?![#/]|[A-Za-z][A-Za-z0-9+.-]*:)([^)\s]+)")


def rebase_links(text: str, prefix: str) -> str:
    """Rewrite relative link targets in `text` for output `prefix` levels away.

    Summaries are authored relative to `docs/decisions/` — the same base as the
    ADR body they were lifted from — and this index renders them both there
    (`README.md`, prefix "") and one level down (`tags/<tag>.md`, prefix "../").
    Owning the rendering is what lets a summary carry links at all: without this,
    no single relative target could be correct in both (ADR-005)."""
    if not prefix:
        return text
    return RELATIVE_LINK_RE.sub(lambda m: prefix + m.group(1), text)


def parse_frontmatter(text: str) -> tuple[dict, str]:
    """Split leading `---` YAML frontmatter from the body. Missing frontmatter
    yields an empty dict so a half-migrated tree still renders — lint reports
    the omission rather than the build crashing on it."""
    if not text.startswith("---\n"):
        return {}, text
    end = text.find("\n---\n", 3)
    if end == -1:
        return {}, text
    return yaml.safe_load(text[4 : end + 1]) or {}, text[end + 5 :]


class Adr:
    def __init__(self, path: Path, scheme=None):
        scheme = scheme or current().schemes["ADR"]
        self.path = path
        self.scheme = scheme
        self.prefix = scheme.prefix
        self.number = scheme.number_of(path)
        self.meta, body = parse_frontmatter(path.read_text())
        # `title:` is the source of truth; the body's H1 is the fallback, so a
        # document written before the field existed — or in a project that
        # hasn't adopted it — still renders a title rather than a blank cell
        # (ADR-013).
        first = next((ln for ln in body.splitlines() if ln.startswith("#")), "")
        self.heading = TITLE_RE.sub("", first).strip()
        self.title = str(self.meta.get("title") or "").strip() or self.heading

    @property
    def code(self) -> str:
        return f"{self.prefix}-{self.number:03d}"

    @property
    def status(self) -> str:
        return str(self.meta.get("status", "")).strip()

    @property
    def tags(self) -> list[str]:
        return [str(t).strip().lower() for t in (self.meta.get("tags") or [])]

    def cell(self, prefix: str = "") -> str:
        """The table's middle column: the summary when there is one, else the
        title. A row has always been one blob, not a title plus a description —
        keeping that shape is what made the migration byte-identical.

        A summary may carry relative links, written — like the ADR's body —
        relative to `docs/decisions/`. `prefix` rebases them for output that
        renders somewhere else (ADR-005); it is the same prefix the row's own
        ADR link already took."""
        return rebase_links(str(self.meta.get("summary") or self.title).strip(), prefix)

    @property
    def version(self) -> int:
        """Which revision of this document's claim you are reading.

        Standard frontmatter for every scheme (ADR-016), not just principles.
        A decision is superseded rather than rewritten, so its version moves
        rarely — but "rarely" is not "never": a decision whose *scope* widens
        without its choice changing is a revision, and that is exactly the case
        a reader needs told apart from a fresh decision."""
        return int(self.meta.get("version", 1) or 1)

    @property
    def influenced_by(self) -> list[str]:
        raw = self.meta.get("influenced_by") or []
        return [str(x).strip() for x in raw]

    def row(self, prefix: str = "") -> str:
        # unresolved-ok-block: ADR-100 — a stand-in number in the example below
        # Every rendered field is rebased, not just the ADR's own link: a
        # "Superseded — by [ADR-100](…)" note is prose too, and its link was
        # silently broken on the tag pages (four of them) until this existed.
        #
        # The version is shown only when it isn't 1. A column of 1s teaches
        # nothing; the field exists so a document that HAS been revised says so
        # where it is read (ADR-016).
        version = f" v{self.version}" if self.version > 1 else ""
        return (f"| [{self.code}]({prefix}{self.path.name}){version} "
                f"| {self.cell(prefix)} | {rebase_links(self.status, prefix)} |")


def load_adrs() -> list[Adr]:
    """The ADR scheme's documents. Kept as its own name because the pending
    report is about decisions specifically, not about every scheme."""
    return load_scheme(current().schemes["ADR"])


def load_scheme(scheme) -> list[Adr]:
    return [Adr(p, scheme) for p in scheme.documents().values()]


def tag_order(adrs: list[Adr]) -> list[tuple[str, dict]]:
    """Declared tags first, in tags.yaml order; then any undeclared tag an ADR
    actually uses, alphabetically. Using a new tag must never require a code
    change — that's the whole point of pushing categories down onto the ADRs."""
    tags_file = current().tags_yaml
    declared = yaml.safe_load(tags_file.read_text()) if tags_file.exists() else {}
    declared = declared or {}
    used = {t for a in adrs for t in a.tags}
    ordered = [(t, declared[t] or {}) for t in declared if t in used]
    ordered += [(t, {}) for t in sorted(used - set(declared))]
    return ordered


def render_categories(adrs: list[Adr], tags: list[tuple[str, dict]]) -> str:
    blocks = []
    for tag, meta in tags:
        listed = [a for a in adrs if tag in a.tags]
        label = meta.get("label", tag.title())
        blurb = f" — {meta['blurb']}" if meta.get("blurb") else ""
        links = " · ".join(f"[{a.number:03d}]({a.path.name})" for a in listed)
        blocks.append(f"**[{label}](tags/{tag}.md)** ({len(listed)}){blurb}:\n{links}")
    return "\n\n".join(blocks)


def render_index(adrs: list[Adr], tags: list[tuple[str, dict]]) -> str:
    table = TABLE_HEAD + "\n".join(a.row() for a in adrs) + "\n"
    stub = current().stub
    prose = stub.read_text() if stub.exists() else DEFAULT_STUB
    return (prose.replace("{categories}", render_categories(adrs, tags))
                 .replace("{table}", table))


def render_tag_page(tag: str, meta: dict, adrs: list[Adr]) -> str:
    label = meta.get("label", tag.title())
    listed = [a for a in adrs if tag in a.tags]
    blurb = f"\n{meta['blurb'].capitalize()}.\n" if meta.get("blurb") else ""
    return (
        f"<!-- GENERATED by `luria index` — do not edit. -->\n\n"
        f"# ADRs tagged `{tag}`\n"
        f"{blurb}\n"
        f"{len(listed)} of {len(adrs)} decisions. Back to the [full index](../README.md).\n\n"
        + TABLE_HEAD
        + "\n".join(a.row(prefix="../") for a in listed)
        + "\n"
    )


def render_document(scheme, docs: list[Adr]) -> str:
    """Every document's body, in number order, as one page.

    The right shape when the set is read *as a whole* rather than browsed one at
    a time — which is what a principles document is: people cite "DP-3" and then
    read it in the context of its neighbours. The metadata line is what the
    fragment frontmatter buys: a version, so a revised principle says so
    (ADR-012), and the decisions whose experience produced it."""
    stub = scheme.dir / "README.stub"
    head = stub.read_text() if stub.exists() else DEFAULT_DOCUMENT_STUB
    base = scheme.output.parent if scheme.output else scheme.dir
    parts = []
    for doc in docs:
        body = parse_frontmatter(doc.path.read_text())[1].strip()
        # Demote the fragment's own H1 to the assembled document's H2, and
        # renumber it into the reader's numbering rather than the file's code.
        body = re.sub(r"^#\s*[A-Z]+-\d+\s*(?::|—|-)\s*",
                      f"## {doc.number}. ", body, count=1)
        # A stable anchor, because the heading is not one. A principle is a
        # living document — two of the eight here have been reworded already —
        # and a heading-derived anchor stops resolving the moment the wording
        # moves, silently, which is the fail-stale polarity DP-3 rules out.
        # This one is keyed to the number, which is the thing that never moves.
        body = f'<a name="{doc.prefix.lower()}-{doc.number}"></a>\n\n{body}'
        meta = [f"*v{doc.version}"]
        if doc.influenced_by:
            meta.append("shaped by " + ", ".join(
                f"[{code}]({target})" if (target := _link(code, base)) else code
                for code in doc.influenced_by))
        if doc.status != scheme.active:
            meta.append(f"**{doc.status}**")
        if origin := str(doc.meta.get("origin", "")).strip():
            meta.append(f"origin: {origin.rstrip('.')}")
        parts.append(f"{body}\n\n{' · '.join(meta)}*")
    return head.replace("{principles}", "\n\n".join(parts))


def _link(code: str, base: Path) -> str:
    """`ADR-004` → a link to that decision, relative to `base`.

    Relative to *where the text renders*, not where the fragment lives — the
    same rule the reference fixer follows for anything assembled elsewhere
    (ADR-005). An unresolvable code yields "", and the caller renders the bare
    code rather than a link to nothing (DP-1: say what you can, don't invent)."""
    try:
        prefix, number = code.split("-")
        path = current().schemes[prefix.upper()].documents().get(int(number))
    except (ValueError, KeyError):
        return ""
    return os.path.relpath(path, base) if path else ""


def outputs() -> dict[Path, str]:
    """Every generated view, across every scheme — one place, so the lint's
    staleness check covers a new scheme the moment it is configured."""
    cfg = current()
    out: dict[Path, str] = {}
    for scheme in cfg.schemes.values():
        docs = load_scheme(scheme)
        if scheme.render == "document":
            if scheme.output:
                out[scheme.output] = render_document(scheme, docs)
            continue
        tags = tag_order(docs)
        out[cfg.index] = render_index(docs, tags)
        for tag, meta in tags:
            out[cfg.tag_dir / f"{tag}.md"] = render_tag_page(tag, meta, docs)
    from . import journal
    out.update(journal.outputs())
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="exit 1 if anything is stale")
    args = ap.parse_args()

    rendered = outputs()
    if args.check:
        stale = [p for p, text in rendered.items()
                 if not p.exists() or p.read_text() != text]
        # A tag page whose tag no longer exists is stale too.
        stale += [p for p in current().tag_dir.glob("*.md") if p not in rendered]
        from . import badges
        readme = badges.readme()
        if readme.exists() and badges.OPEN in (text := readme.read_text()) \
                and badges.rewrite(text) != text:
            stale.append(readme)
        if stale:
            print("stale (run `luria index`):", file=sys.stderr)
            for p in sorted(stale):
                print(f"  {current().rel(p)}", file=sys.stderr)
            return 1
        print("luria index: current")
        return 0

    cfg = current()
    cfg.tag_dir.mkdir(parents=True, exist_ok=True)
    for p in cfg.tag_dir.glob("*.md"):
        if p not in rendered:
            p.unlink()
    for p, text in rendered.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text)
    # Name every scheme, not just the decisions: a project that adds one wants
    # to see it counted, and a scheme silently rendering nothing is the failure
    # this line exists to make visible (DP-1).
    from . import journal
    filed = {n: len(journal.entries(j)) for n, j in sorted(cfg.journals.items())}
    counted = ", ".join(
        [f"{len(load_scheme(s))} {p}s" for p, s in sorted(cfg.schemes.items())]
        + [f"{c} {n} entr{'y' if c == 1 else 'ies'}" for n, c in filed.items()])
    print(f"Wrote {len(rendered)} file(s) from {counted}.")
    # The README's badge counts are derived from the same frontmatter, so they
    # are regenerated here rather than by a command someone has to remember
    # (ADR-018). A project with no badge region is left alone.
    from . import badges
    readme = badges.readme()
    if readme.exists() and badges.OPEN in (text := readme.read_text()):
        readme.write_text(badges.rewrite(text))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
