#!/usr/bin/env python3
"""`luria index` — render every scheme's view from its fragments.

    luria index            # write the views
    luria index --check    # exit 1 if any of them is stale

A scheme's view used to be hand-maintained: every decision-bearing branch
appended a row to the same table and a link to the same category list. That
makes it the shared-file lock [DP-2](../docs/design-principles.md#dp-2) names,
and it *drifts*, because the row duplicates data the document already owns — in
the corpus this was extracted from, 45 of 155 rows disagreed with their own
decision's status (ADR-004).

So the view is generated. Each document carries YAML frontmatter, and a scheme
declares how its documents are rendered (ADR-012):

  render = "index"      the browsable shape — a table plus per-tag pages
      docs/decisions/README.md        stub prose + category lists + the table
      docs/decisions/tags/<tag>.md    one page per tag
      (sources in record/decisions.d/ — the view directory holds only what
       this generator wrote, which is what lets the lint call anything else
       in it an error, ADR-021)

  render = "document"   the read-as-a-whole shape — bodies concatenated
      docs/design-principles.md       stub prose + every principle in order

Adding a document means adding ONE file. Adding a *tag* means using it in one;
`tags.yaml` only supplies ordering and a blurb, so an unlisted tag still renders.

`--check` is what makes idempotency enforceable: `luria lint` runs it, so a stale
view is a lint failure rather than a silent divergence — which only works because
a generated view's sources persist, unlike a collected one's (ADR-012).

The stub/placeholder shape is borrowed from dmarx/bench-warmers, which solved
the same problem for a brainstorming repo: prose lives in a `.stub`, the
generator substitutes `{placeholders}`, and tags get their own generated pages.
"""

from __future__ import annotations

import os.path
import posixpath
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

import yaml

from .config import current

# The tail accepts a temporary code (`ADR-tmp47fje`, ADR-049) as well as a
# number: both are codes a heading legitimately carries.
TITLE_RE = re.compile(r"^#\s*[A-Z]+-[A-Za-z0-9]+\s*(?::|—|-)\s*")
TABLE_HEAD = "| # | Title | Summary | Status |\n|---|---|---|---|\n"

# A literal `|` in a summary is a cell delimiter to the table parser: the row
# grows extra columns, the summary truncates and its tail lands in the status
# column (#14). Escaping belongs to the renderer, not the author — a summary is
# prose, and GFM unescapes `\|` everywhere in a table, code spans included.
# `\\?\|` normalises rather than doubles: an author who already hand-escaped
# must not end up with `\\|`, which is a stray backslash and a broken row again.
_CELL_PIPE_RE = re.compile(r"\\?\|")


def escape_cell(text: str) -> str:
    """`text` as one table cell, however many `|` it contains."""
    return _CELL_PIPE_RE.sub(r"\\|", text)

# Used when a project has no `README.stub`. The stub exists so prose lives in
# markdown rather than in this generator; not having written one yet shouldn't
# stop the index from building.
#
# The heading names the *scheme*, not this package's own principles. It used to
# read "# Design principles" unconditionally, which meant a project rendering a
# SPEC or POLICY family as a document got a page titled after Luria's — found
# by building `examples/rfcs-and-specs`, which is what the examples are for.
DEFAULT_DOCUMENT_STUB = """# {title}

<!-- GENERATED by `luria index` — edit the fragments, not this file. -->

{principles}
"""

# Same rule as DEFAULT_DOCUMENT_STUB above, found the same way: the heading
# names the scheme, because a project that hasn't written a stub for its RFC
# index should not get a page titled after this package's decisions.
DEFAULT_STUB = """# {title}

<!-- GENERATED below this line by `luria index` — edit README.stub instead. -->

{categories}

{table}
"""

# A markdown link with a *relative* target: not an anchor, not root-relative,
# not a URL scheme. Those are the only ones a change of output directory moves.
RELATIVE_LINK_RE = re.compile(r"(?<=\]\()(?![#/]|[A-Za-z][A-Za-z0-9+.-]*:)([^)\s]+)")


def rebase_links(text: str, prefix: str) -> str:
    """Rewrite relative link targets in `text` for an output `prefix` away.

    Summaries are authored relative to the scheme's *source* directory — the
    same base as the ADR body they were lifted from — and this index renders
    them into the view directory and again one level down in `tags/<tag>.md`.
    Owning the rendering is what lets a summary carry links at all: without
    this, no single relative target could be correct everywhere (ADR-005).

    The result is **normalized**, because a link that only a webserver's path
    resolver forgives is a link some readers lose: concatenation alone yields
    `../../record/decisions.d/../../docs/design-principles.md`, which GitHub
    collapses and a static-site generator does not (#13)."""
    if not prefix:
        return text
    return RELATIVE_LINK_RE.sub(
        lambda m: _normalize(prefix + m.group(1)), text)


def _normalize(target: str) -> str:
    """Collapse `a/../b` in a relative link target, fragment preserved.

    `posixpath` because these are URLs, not filesystem paths — the separator
    is `/` on every platform that renders the view."""
    path, sep, fragment = target.partition("#")
    return (posixpath.normpath(path) if path else path) + sep + fragment


def prefix_for(scheme, out_dir: Path) -> str:
    """The rebase prefix for text authored in `scheme.dir`, rendered into
    `out_dir`. "" when they are the same place — the collocated layout — so
    the old output is byte-identical where nothing moved."""
    rel = os.path.relpath(scheme.dir, out_dir)
    return "" if rel == "." else rel + "/"


def parse_frontmatter(text: str) -> tuple[dict, str]:
    """Split leading `---` YAML frontmatter from the body. Missing frontmatter
    yields an empty dict so a half-migrated tree still renders — lint reports
    the omission rather than the build crashing on it."""
    if not text.startswith("---\n"):
        return {}, text
    end = text.find("\n---\n", 3)
    if end == -1:
        return {}, text
    return yaml.safe_load(text[4 : end + 1]) or {}, text[end + 5 :]


class Adr:
    def __init__(self, path: Path, scheme=None):
        scheme = scheme or current().schemes["ADR"]
        self.path = path
        self.scheme = scheme
        self.prefix = scheme.prefix
        self.number = scheme.number_of(path)
        # A merge-allocated document awaiting concretization (ADR-049): no
        # number yet, addressed by its temporary tail.
        self.tail = scheme.temp_of(path)
        self.meta, body = parse_frontmatter(path.read_text(encoding="utf-8"))
        # `title:` is the source of truth; the body's H1 is the fallback, so a
        # document written before the field existed — or in a project that
        # hasn't adopted it — still renders a title rather than a blank cell
        # (ADR-013).
        first = next((ln for ln in body.splitlines() if ln.startswith("#")), "")
        self.heading = TITLE_RE.sub("", first).strip()
        self.title = str(self.meta.get("title") or "").strip() or self.heading

    @property
    def code(self) -> str:
        if self.number is None and self.tail:
            return f"{self.prefix}-{self.tail}"
        return f"{self.prefix}-{self.number:03d}"

    @property
    def status(self) -> str:
        """The display form — `Superseded — by [X](…); note` — composed from
        the fields, a successor linked relative to the scheme directory the
        way a hand-written note's link was. `status_value`, `status_note`
        and `superseded_by` are the fields."""
        from . import statuses
        return statuses.display(
            statuses.of(self.meta),
            link=lambda c: f"[{c}]({t})" if (t := _link(c, self.scheme.dir)) else c)

    @property
    def superseded_by(self) -> tuple[str, ...]:
        from . import statuses
        return statuses.of(self.meta).superseded_by

    @property
    def status_value(self) -> str:
        from . import statuses
        return statuses.of(self.meta).value

    @property
    def status_note(self) -> str:
        from . import statuses
        return statuses.of(self.meta).note

    @property
    def tags(self) -> list[str]:
        return [str(t).strip().lower() for t in (self.meta.get("tags") or [])]

    def cell(self, prefix: str = "") -> str:
        """The Summary column: the `summary:` frontmatter, or empty.

        The row used to be one blob — summary when present, else title —
        under a column labelled "Title", a shape kept originally to make the
        migration byte-identical and outlived by its reason: any document
        with a summary showed its summary mislabelled as a title. The title
        now has its own column, so this one is honest about being optional —
        an empty cell is a document whose index row could say more, not a
        rendering fallback papering over the gap.

        A summary may carry relative links, written — like the ADR's body —
        relative to the scheme's source directory. `prefix` rebases them for
        output that renders somewhere else (ADR-005); it is the same prefix
        the row's own ADR link already took."""
        return rebase_links(str(self.meta.get("summary") or "").strip(), prefix)

    @property
    def version(self) -> int:
        """Which revision of this document's claim you are reading.

        Standard frontmatter for every scheme (ADR-016), not just principles.
        A decision is superseded rather than rewritten, so its version moves
        rarely — but "rarely" is not "never": a decision whose *scope* widens
        without its choice changing is a revision, and that is exactly the case
        a reader needs told apart from a fresh decision."""
        return int(self.meta.get("version", 1) or 1)

    @property
    def influenced_by(self) -> list[str]:
        raw = self.meta.get("influenced_by") or []
        return [str(x).strip() for x in raw]

    def row(self, prefix: str = "") -> str:
        # unresolved-ok-block: ADR-100 — a stand-in number in the example below
        # Every rendered field is rebased, not just the ADR's own link: a
        # "Superseded — by [ADR-100](…)" note is prose too, and its link was
        # silently broken on the tag pages (four of them) until this existed.
        #
        # The version is shown only when it isn't 1. A column of 1s teaches
        # nothing; the field exists so a document that HAS been revised says so
        # where it is read (ADR-016).
        version = f" v{self.version}" if self.version > 1 else ""
        return (f"| [{self.code}]({prefix}{self.path.name}){version} "
                f"| {escape_cell(self.title)} "
                f"| {escape_cell(self.cell(prefix))} "
                f"| {escape_cell(rebase_links(self.status, prefix))} |")


def load_adrs() -> list[Adr]:
    """The ADR scheme's documents. Kept as its own name because the pending
    report is about decisions specifically, not about every scheme."""
    return load_scheme(current().schemes["ADR"])


def load_scheme(scheme) -> list[Adr]:
    """Every document in the scheme: numbered ascending, then any temporary
    documents (ADR-049) by their `date:` and name — they have no place in the
    sequence yet, so they read after it."""
    docs = [Adr(p, scheme) for p in scheme.documents().values()]
    temps = [Adr(p, scheme) for p in scheme.temp_documents().values()]
    temps.sort(key=lambda a: (str(a.meta.get("date", "")), a.path.name))
    return docs + temps


def tag_order(adrs: list[Adr], scheme=None) -> list[tuple[str, dict]]:
    """Declared tags first, in tags.yaml order; then any undeclared tag an ADR
    actually uses, alphabetically. Using a new tag must never require a code
    change — that's the whole point of pushing categories down onto the ADRs."""
    tags_file = scheme.tags_yaml if scheme else current().tags_yaml
    declared = yaml.safe_load(tags_file.read_text(encoding="utf-8")) if tags_file.exists() else {}
    declared = declared or {}
    used = {t for a in adrs for t in a.tags}
    ordered = [(t, declared[t] or {}) for t in declared if t in used]
    ordered += [(t, {}) for t in sorted(used - set(declared))]
    return ordered


def render_categories(adrs: list[Adr], tags: list[tuple[str, dict]],
                      prefix: str = "") -> str:
    blocks = []
    for tag, meta in tags:
        listed = [a for a in adrs if tag in a.tags]
        label = meta.get("label", tag.title())
        blurb = f" — {meta['blurb']}" if meta.get("blurb") else ""
        # A temporary document (ADR-049) has no number to abbreviate to, so
        # its category chip is the tail — still short, still a link.
        links = " · ".join(
            f"[{a.number:03d}]({prefix}{a.path.name})" if a.number is not None
            else f"[{a.tail}]({prefix}{a.path.name})" for a in listed)
        blocks.append(f"**[{label}](tags/{tag}.md)** ({len(listed)}){blurb}:\n{links}")
    return "\n\n".join(blocks)


def render_index(adrs: list[Adr], tags: list[tuple[str, dict]],
                 scheme=None) -> str:
    scheme = scheme or current().schemes["ADR"]
    prefix = prefix_for(scheme, scheme.view)
    table = TABLE_HEAD + "\n".join(a.row(prefix) for a in adrs) + "\n"
    # A declared status vocabulary explains the column it sits above. Rendered
    # here rather than behind a stub placeholder: adopting `statuses.yaml`
    # should be enough to make the meaning visible, and a legend that needs a
    # second edit to appear is one that does not.
    from . import statuses
    if declared := statuses.legend(scheme):
        table = declared + "\n" + table
    stub = scheme.stub
    prose = (stub.read_text(encoding="utf-8") if stub.exists()
             else DEFAULT_STUB.replace(
                 "{title}", "Architecture decision records"
                 if scheme.prefix == "ADR" else f"{scheme.prefix} documents"))
    return (prose.replace("{categories}", render_categories(adrs, tags, prefix))
                 .replace("{table}", table))


def render_tag_page(tag: str, meta: dict, adrs: list[Adr],
                    scheme=None) -> str:
    scheme = scheme or current().schemes["ADR"]
    prefix = prefix_for(scheme, scheme.tag_dir)
    label = meta.get("label", tag.title())
    listed = [a for a in adrs if tag in a.tags]
    # Sentence-case the first letter only. `str.capitalize()` lowercases
    # everything after it, which silently destroys a blurb that runs to more
    # than one sentence or names anything capitalised.
    raw = meta.get("blurb") or ""
    blurb = f"\n{raw[:1].upper()}{raw[1:]}.\n" if raw else ""
    # The heading names the scheme, for the same reason DEFAULT_STUB does: a
    # project's RFC tag page should not be titled after this package's
    # decisions.
    noun = "decisions" if scheme.prefix == "ADR" else f"{scheme.prefix} documents"
    return (
        f"<!-- GENERATED by `luria index` — do not edit. -->\n\n"
        f"# {scheme.prefix}s tagged `{tag}`\n"
        f"{blurb}\n"
        f"{len(listed)} of {len(adrs)} {noun}. Back to the [full index](../README.md).\n\n"
        + TABLE_HEAD
        + "\n".join(a.row(prefix=prefix) for a in listed)
        + "\n"
    )


def render_document(scheme, docs: list[Adr]) -> str:
    """Every document's body, in number order, as one page.

    The right shape when the set is read *as a whole* rather than browsed one at
    a time — which is what a principles document is: people cite "DP-3" and then
    read it in the context of its neighbours. The metadata line is what the
    fragment frontmatter buys: a version, so a revised principle says so
    (ADR-012), and the decisions whose experience produced it."""
    stub = scheme.stub
    # A project that wrote a stub gets its own prose verbatim; one that hasn't
    # gets a heading named after its own scheme rather than after this
    # package's principles.
    head = (stub.read_text(encoding="utf-8") if stub.exists()
            else DEFAULT_DOCUMENT_STUB.replace(
                "{title}", f"{scheme.prefix} documents"))
    base = scheme.output.parent if scheme.output else scheme.dir
    parts = []
    for doc in docs:
        body = parse_frontmatter(doc.path.read_text(encoding="utf-8"))[1].strip()
        # Demote the fragment's own H1 to the assembled document's H2, and
        # renumber it into the reader's numbering rather than the file's code.
        label = doc.number if doc.number is not None else doc.code
        body = re.sub(r"^#\s*[A-Z]+-[A-Za-z0-9]+\s*(?::|—|-)\s*",
                      f"## {label}. ", body, count=1)
        # A stable anchor, because the heading is not one. A principle is a
        # living document — two of the eight here have been reworded already —
        # and a heading-derived anchor stops resolving the moment the wording
        # moves, silently, which is the fail-stale polarity DP-3 rules out.
        # This one is keyed to the number, which is the thing that never moves.
        slot = doc.number if doc.number is not None else doc.tail
        body = f'<a name="{doc.prefix.lower()}-{slot}"></a>\n\n{body}'
        meta = [f"*v{doc.version}"]
        if doc.influenced_by:
            meta.append("shaped by " + ", ".join(
                f"[{code}]({target})" if (target := _link(code, base)) else code
                for code in doc.influenced_by))
        if doc.status != scheme.active:
            meta.append(f"**{doc.status}**")
        if origin := str(doc.meta.get("origin", "")).strip():
            meta.append(f"origin: {origin.rstrip('.')}")
        parts.append(f"{body}\n\n{' · '.join(meta)}*")
    return head.replace("{principles}", "\n\n".join(parts))


def _link(code: str, base: Path) -> str:
    """`ADR-004` → a link to that decision, relative to `base`.

    Relative to *where the text renders*, not where the fragment lives — the
    same rule the reference fixer follows for anything assembled elsewhere
    (ADR-005). An unresolvable code yields "", and the caller renders the bare
    code rather than a link to nothing (DP-1: say what you can, don't invent)."""
    try:
        prefix, number = code.split("-")
        path = current().schemes[prefix.upper()].documents().get(int(number))
    except (ValueError, KeyError):
        return ""
    return os.path.relpath(path, base) if path else ""


def view_dirs() -> list[Path]:
    """Every directory the generator owns outright. Anything in one of these
    it didn't render is an orphan — a stale tag page, a book from an old
    granularity, or a hand-written file that will read as generated (ADR-021).
    A collocated scheme (no separate `output`) contributes only its tag dir,
    because its view directory also holds the sources."""
    cfg = current()
    dirs: list[Path] = []
    for s in cfg.schemes.values():
        if s.render != "index":
            continue
        dirs.append(s.tag_dir)
        if s.view != s.dir:
            dirs.append(s.view)
    dirs += [j.output for j in cfg.journals.values()]
    # The status reports are views like any other (#35) — a hand-written file
    # in their directory would read as generated, and a report from a retired
    # filename would linger as truth.
    dirs.append(cfg.reports)
    return dirs


def orphans(rendered: dict[Path, str]) -> list[Path]:
    return [p for d in view_dirs() if d.is_dir()
            for p in sorted(d.glob("*.md")) if p not in rendered]


def ignored(paths: list[Path]) -> set[Path]:
    """The subset of `paths` that git is configured to ignore.

    A generated view the project has gitignored is one it has decided not to
    keep — `[luria.paths] reports = "build/doc-reports"` behind a CI artifact
    upload is the shape that exists in the wild. The staleness check has
    nothing to compare against there: a fresh clone never has the file, so
    *missing* reads as *stale*, and the remedy the failure prints — regenerate
    and commit the result — is the one thing `.gitignore` forbids. A check
    that cannot be satisfied is not a check; it is a permanently red job that
    teaches people to stop reading it, which is DP-1 wearing a green hat.

    Only `--check` consults this. Writing is unaffected: `luria index` still
    renders an ignored view, because *not committed* is not *not wanted* —
    that report is precisely what the artifact upload publishes.

    One `git check-ignore` for the whole set. Exit 1 means "nothing matched",
    the ordinary answer; anything else (not a repo, no git on PATH) means we
    cannot tell, and not-ignored is the answer that keeps checking."""
    if not paths:
        return set()
    try:
        out = subprocess.run(
            ["git", "check-ignore", "--", *(str(p) for p in paths)],
            cwd=current().root, capture_output=True, text=True)
    except OSError:
        return set()
    if out.returncode not in (0, 1):
        return set()
    return {Path(line).resolve() for line in out.stdout.splitlines() if line}


def _render_scheme(scheme) -> dict[Path, str]:
    docs = load_scheme(scheme)
    if scheme.render == "document":
        return {scheme.output: render_document(scheme, docs)} if scheme.output else {}
    tags = tag_order(docs, scheme)
    out = {scheme.index_path: render_index(docs, tags, scheme)}
    for tag, meta in tags:
        out[scheme.tag_dir / f"{tag}.md"] = render_tag_page(tag, meta, docs, scheme)
    return out


def outputs() -> dict[Path, str]:
    """Every generated view, across every scheme — one place, so the lint's
    staleness check covers a new scheme the moment it is configured.

    Rendered wide (ADR-026): each scheme and each journal is an independent
    pure function of the tree, so they run as parallel units. `pmap` returns
    in input order, which is what keeps the merged dict — and therefore the
    staleness diff — deterministic."""
    from . import config_doc, journal, record_doc, reports
    from .parallel import pmap
    cfg = current()
    units = [lambda s=s: _render_scheme(s) for s in cfg.schemes.values()]
    units += [lambda j=j: journal.outputs_for(j) for j in cfg.journals.values()]
    # The status reports render with everything else (#35), so the badges have
    # a committed page to land on and a stale report is a lint failure.
    units += [reports.outputs]
    # The record description is a projection of *this* config's values, so
    # naming a new scheme rewrites it on the next build.
    units += [record_doc.outputs]
    # The configuration reference is a projection of the config *schema*, so it
    # goes stale on a code change rather than a record change — which is
    # exactly why it renders here instead of being written by hand. It renders
    # only where that schema's source lives: elsewhere it is a vendored copy of
    # another project's file, stale on their next upgrade (#114).
    if cfg.owns_schema:
        units += [config_doc.outputs]
    out: dict[Path, str] = {}
    for rendered in pmap(lambda u: u(), units):
        out.update(rendered)
    return out


@dataclass(frozen=True)
class Staleness:
    """Everything the staleness check has to say about the tree.

    Three kinds, kept apart because each wants a different sentence: a view
    that differs from what the generator would write, a file sitting in a view
    directory the generator never wrote, and a README whose badge counts have
    drifted."""
    stale: list[Path]
    orphaned: list[Path]
    # The README, when either of its generated regions has drifted — the badge
    # counts or the citation entry. One field because it is one file and one
    # remedy; the message names which region.
    readme: Path | None

    @property
    def all(self) -> list[Path]:
        return self.stale + self.orphaned + ([self.readme] if self.readme else [])

    @property
    def any(self) -> bool:
        return bool(self.all)


def staleness(rendered: dict[Path, str] | None = None) -> Staleness:
    """The one answer `luria index --check` and `luria lint` both consume.

    They used to compute it twice, in two files, from the same three rules —
    which is the arrangement where a fix lands in one of them and the other
    keeps failing. It did: the gitignore exemption below was written in
    `--check` first, and `lint` went on rejecting the same tree.

    A view the project gitignores is excluded from all three kinds. There is
    no committed copy to compare against — see `ignored`."""
    from . import badges as badges_mod
    from . import citation as citation_mod
    rendered = outputs() if rendered is None else rendered
    loose = orphans(rendered)
    skip = ignored(list(rendered) + loose)
    readme = badges_mod.readme()
    drifted = False
    if readme.exists() and readme not in skip:
        text = readme.read_text(encoding="utf-8")
        drifted = ((badges_mod.OPEN in text and badges_mod.rewrite(text) != text)
                   or (citation_mod.OPEN in text
                       and citation_mod.rewrite(text) != text))
    return Staleness(
        stale=[p for p, text in rendered.items()
               if p not in skip and (not p.exists() or p.read_text(encoding="utf-8") != text)],
        orphaned=[p for p in loose if p not in skip],
        readme=readme if drifted else None,
    )


def run(check: bool = False) -> None:
    """Regenerate every view — the decision index and tag pages, the
    principles document, the devlog books, the status reports, the README
    badges — and nothing else: sources are `luria repair`'s. --check exits 1
    if any view is stale instead of writing."""
    # Views only. The source repairs that used to run first — a journal
    # entry's missing `created:`, a retired configuration reference — are
    # `luria repair`'s (ADR-068): a repair is committed on the branch
    # that authored the source, a view on the default branch alone, and one
    # command cannot write to two commit points.
    if check:
        report = staleness()
        if report.any:
            from . import ci
            print(f"stale ({ci.regenerate_remedy()}):", file=sys.stderr)
            for p in sorted(report.all):
                print(f"  {current().rel(p)}", file=sys.stderr)
            raise SystemExit(1)
        print("luria index: current")
        return

    rendered = outputs()
    cfg = current()
    for stale_file in orphans(rendered):
        stale_file.unlink()
    for p, text in rendered.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text, encoding="utf-8")
    # Name every scheme, not just the decisions: a project that adds one wants
    # to see it counted, and a scheme silently rendering nothing is the failure
    # this line exists to make visible (DP-1).
    from . import journal
    filed = {n: len(journal.entries(j)) for n, j in sorted(cfg.journals.items())}
    counted = ", ".join(
        [f"{len(load_scheme(s))} {p}s" for p, s in sorted(cfg.schemes.items())]
        + [f"{c} {n} entr{'y' if c == 1 else 'ies'}" for n, c in filed.items()])
    print(f"Wrote {len(rendered)} file(s) from {counted}.")
    # The README's badge counts are derived from the same frontmatter, so they
    # are regenerated here rather than by a command someone has to remember
    # (ADR-018). A project with no badge region is left alone.
    from . import badges
    from . import citation
    readme = badges.readme()
    if readme.exists():
        text = readme.read_text(encoding="utf-8")
        if badges.OPEN in text:
            text = badges.rewrite(text)
        if citation.OPEN in text:
            text = citation.rewrite(text)
        if text != readme.read_text(encoding="utf-8"):
            readme.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    import fire
    fire.Fire(run)
