# luria/chains.py
"""A relation walked transitively, rendered once (#171).

`edges.py` reads a reference field as a typed relation and the site shows
each page's neighbours. Neighbours answer "what is next to this document".
They do not answer *what sequence is this document a step in*, which is the
question worth reading — and the question the documents themselves were
answering, one hand-written paragraph each, once per participant.

That is not a stylistic complaint. In the record this was built for, two
notes each ended with a sentence saying two rival designs had never been
compared. True when written, false three weeks later, corrected in two places
— found because one person happened to read both notes the same afternoon. A
third note describing the same line would have been a third place, and would
have been missed. Prose duplication does not decay because people are
careless; it decays because nothing points at the copies.

**The field carries the sequence; the prose carries the argument.** A chain
rendered mechanically is shallower than the paragraphs it replaces — "A
extends B" loses "free mixing is what made B unstable, and constraining it is
the whole point". So this renders the order, the status and the title, and
nothing else: each document keeps explaining its own step, and stops
restating the whole line.

Two shapes, and the difference matters:

- `relation` is the **spine**, and it is directed. A extends B means B came
  first. Succession is not symmetric and nothing expects it to be.
- `sibling` is the **cross-link**, and it is symmetric. A rival evaluated
  against another is a fact both documents hold, so one side declaring it
  alone is one document updated and one not — which is the failure the field
  exists to end, reappearing inside the mechanism. It is a finding.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from .adr_index import Adr, load_scheme, prefix_for
from .config import current
from .contract import for_scheme, values_of

MARKER = "<!-- GENERATED by `luria index` — do not edit. -->"


@dataclass
class Line:
    """One weakly-connected sequence: an ordered spine, plus the documents
    attached to it only by a cross-link."""
    spine: list[Adr] = field(default_factory=list)
    alongside: list[Adr] = field(default_factory=list)
    # Each spine member's distance from a root, for the rendered nesting.
    depth: dict[str, int] = field(default_factory=dict)

    @property
    def members(self) -> list[Adr]:
        return self.spine + self.alongside


def _codes(doc: Adr, name: str, contract) -> list[str]:
    """The codes one relation field holds on one document. A shape the
    contract rejects is the lint's finding, not this walk's — reading it as
    empty here keeps one mistake reported in one vocabulary."""
    spec = next((f for f in contract.fields if f.name == name), None)
    if spec is None:
        return []
    return [str(v).strip() for v in (values_of(spec, doc.meta.get(name)) or [])]


def _load(chain) -> tuple[dict[str, Adr], dict[str, list[str]],
                          dict[str, list[str]]]:
    """Every document of the chain's scheme, and its two relations, keyed by
    code and filtered to codes that land — a reference to something outside
    the scheme is the contract's finding, not a node here."""
    scheme = current().schemes[chain.scheme]
    docs = {d.code: d for d in load_scheme(scheme)}
    contract = for_scheme(scheme)
    spine: dict[str, list[str]] = {}
    cross: dict[str, list[str]] = {}
    for code, doc in docs.items():
        spine[code] = [c for c in _codes(doc, chain.relation, contract)
                       if c in docs]
        cross[code] = ([c for c in _codes(doc, chain.sibling, contract)
                        if c in docs] if chain.sibling else [])
    return docs, spine, cross


def _components(codes: list[str], neighbours: dict[str, set[str]]
                ) -> list[list[str]]:
    """Maximal weakly-connected groups, in the order their earliest member
    appears — so the page's sections are stable across runs."""
    seen: set[str] = set()
    out: list[list[str]] = []
    for start in codes:
        if start in seen or not neighbours[start]:
            continue
        group, stack = [], [start]
        seen.add(start)
        while stack:
            code = stack.pop()
            group.append(code)
            for other in sorted(neighbours[code]):
                if other not in seen:
                    seen.add(other)
                    stack.append(other)
        out.append(sorted(group))
    return out


def _depths(group: list[str], spine: dict[str, list[str]]) -> dict[str, int]:
    """Distance from a root, longest-path so a step never renders above
    something it extends. Bounded by the group's size, which is what keeps a
    cycle from spinning here rather than being reported."""
    depth = {c: 0 for c in group if spine[c]}
    for _ in range(len(group)):
        changed = False
        for code in group:
            if not spine[code]:
                continue
            want = max(depth.get(p, 0) for p in spine[code]) + 1
            if want > depth[code]:
                depth[code], changed = want, True
        if not changed:
            break
    for code in group:
        depth.setdefault(code, 0)
    return depth


def lines_of(chain) -> list[Line]:
    """Every sequence in one chain, spines ordered oldest first.

    A document is on the spine when it extends something or something
    extends it; one attached only by a cross-link renders alongside. Both
    the page and `walk()` come through here, so the view and the query
    cannot disagree about what a line contains."""
    docs, spine, cross = _load(chain)
    neighbours: dict[str, set[str]] = {c: set() for c in docs}
    for code in docs:
        for other in spine[code] + cross[code]:
            neighbours[code].add(other)
            neighbours[other].add(code)
    out: list[Line] = []
    for group in _components(sorted(docs), neighbours):
        depth = _depths(group, spine)
        line = Line(depth=depth)
        for code in sorted(group, key=lambda c: (depth[c], c)):
            on_spine = bool(spine[code]) or any(code in spine[o] for o in group)
            (line.spine if on_spine else line.alongside).append(docs[code])
        out.append(line)
    return out


def walk() -> list[Line]:
    """Every sequence in every declared chain."""
    return [line for chain in current().chains.values()
            for line in lines_of(chain)]


def rows() -> list[str]:
    """Structural findings: a cycle in a succession, and a comparison only
    one side declares. Both are always wrong and mechanically detectable,
    which is what lets them be checks rather than reports."""
    cfg = current()
    found: list[str] = []
    for chain in cfg.chains.values():
        docs, spine, cross = _load(chain)
        for code in sorted(docs):
            for reached in sorted(_reaches(code, spine)):
                if code in spine[reached] and code < reached:
                    found.append(
                        f"{cfg.rel(docs[code].path)}: `{chain.relation}:` "
                        f"makes a cycle — {code} and {reached} each come "
                        f"before the other, so neither is the earlier step")
        if not chain.sibling:
            continue
        for code in sorted(docs):
            for other in cross[code]:
                if code not in cross[other]:
                    found.append(
                        f"{cfg.rel(docs[other].path)}: {code} declares "
                        f"`{chain.sibling}: {other}` and {other} does not "
                        f"declare {code} — a comparison is a fact both "
                        f"documents hold")
    return sorted(set(found))


def _reaches(start: str, spine: dict[str, list[str]]) -> set[str]:
    """Every code reachable from one, following the spine. Visited-guarded,
    so a cycle terminates rather than being discovered by recursion depth."""
    seen: set[str] = set()
    stack = list(spine[start])
    while stack:
        code = stack.pop()
        if code in seen:
            continue
        seen.add(code)
        stack.extend(spine.get(code, ()))
    return seen


def relation_spans(path, text: str) -> list[tuple[int, int]]:
    """Where a document declares its place in a line, as character spans.

    Not a citation site. `extends:` names the step this work builds on, and
    that step being retired is what a line *looks like* — a successor's
    predecessor is superseded by construction. Reporting it would hand back
    one "cites a retired document" finding per retired step in every chain,
    at the field whose entire job is to name it, and the only way to quiet
    them would be an acknowledgement comment per edge. `compared_against:`
    goes the same way: a comparison against a design that has since been
    retired stayed true when the design was retired.

    The codes are still checked — that a reference resolves, and resolves in
    the declared scheme, is the contract's business and unaffected. What is
    suppressed is only the reading of these fields as *citations*, the way a
    `formerly:` entry and a code inside a URL already are."""
    cfg = current()
    fields = {f for chain in cfg.chains.values()
              for f in (chain.relation, chain.sibling)
              if f and path.parent == cfg.schemes[chain.scheme].dir}
    if not fields:
        return []
    spans, at, active = [], 0, False
    for line in text.splitlines(keepends=True):
        stripped = line.split(":", 1)[0]
        if active and not (line.startswith(("- ", "  ")) or not line.strip()):
            active = False
        if stripped in fields and line.rstrip().endswith(":"):
            active = True
        elif active:
            spans.append((at, at + len(line)))
        at += len(line)
    return spans


def _link(doc: Adr, chain) -> str:
    """A target that resolves from where the page renders.

    It points at the *source* document, not at the scheme's view directory:
    an index-rendered scheme puts a README and its tag pages there, never a
    page per document, so `docs/literature/LIT-140.md` resolves to nothing.
    The index's own rows have always linked this way, through `prefix_for`,
    and the first version of this function inventing a second convention was
    caught by the first real corpus it met — no fixture had checked that a
    rendered target exists."""
    scheme = current().schemes[chain.scheme]
    return prefix_for(scheme, chain.output.parent) + doc.path.name


def _annotation(doc: Adr, chain) -> str:
    """The chain's second axis for one step, read as the contract reads it —
    so a field with a `default` shows its default rather than a blank, which
    is what ADR-076 means by "never absent"."""
    if not chain.annotate:
        return ""
    obligations = for_scheme(current().schemes[chain.scheme])
    values = obligations.reading(chain.annotate, doc.meta)
    return f", {', '.join(str(v) for v in values)}" if values else ""


def _step(doc: Adr, chain, lead: str = "") -> str:
    """One line of the rendered list: the code, the title, and the status
    *value*.

    `Adr.status` is the composed display form — `Superseded — by [X](…);
    note` — and this page wants none of that. The successor is the next
    line, so linking it here says twice what the shape already says; and the
    note is an argument about why the step happened, which is the half this
    view deliberately leaves on the document. Rendering the composed form
    also dragged a link authored in the source's frame onto a page that
    renders somewhere else, which is a thing to rebase rather than a thing
    to want. `status_value` is the field, and the fields are why it is
    there to ask for."""
    return (f"{lead}[{doc.code}]({_link(doc, chain)}) — {doc.title} "
            f"*({doc.status_value}{_annotation(doc, chain)})*")


def _render(chain, lines: list[Line]) -> str:
    count = f"{len(lines)} line" + ("" if len(lines) == 1 else "s")
    out = [MARKER, "", f"# {chain.title}", "",
           f"{count}, walked from `{chain.relation}:` on {chain.scheme} "
           f"documents. Each step explains itself; this page is the order "
           f"they came in.", ""]
    for line in lines:
        head = line.spine[0] if line.spine else line.alongside[0]
        out.append(f"## From {head.title}")
        out.append("")
        for doc in line.spine:
            out.append("  " * line.depth[doc.code] + "- "
                       + _step(doc, chain))
        for doc in line.alongside:
            out.append(_step(doc, chain, lead="- alongside: "))
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def outputs() -> dict:
    """The rendered pages, for `luria index` to write and `--check` to
    compare — one entry per declared chain, none at all for a project that
    declares none."""
    return {chain.output: _render(chain, lines_of(chain))
            for chain in current().chains.values()}
