# luria/chains.py
"""A relation walked transitively, rendered once (#171).

`edges.py` reads a reference field as a typed relation and the site shows
each page's neighbours. Neighbours answer "what is next to this document".
They do not answer *what sequence is this document a step in*, which is the
question worth reading — and the question the documents themselves were
answering, one hand-written paragraph each, once per participant.

That is not a stylistic complaint. In the record this was built for, two
notes each ended with a sentence saying two rival designs had never been
compared. True when written, false three weeks later, corrected in two places
— found because one person happened to read both notes the same afternoon. A
third note describing the same line would have been a third place, and would
have been missed. Prose duplication does not decay because people are
careless; it decays because nothing points at the copies.

**The field carries the sequence; the prose carries the argument.** A chain
rendered mechanically is shallower than the paragraphs it replaces — "A
extends B" loses "free mixing is what made B unstable, and constraining it is
the whole point". So this renders the order, the status and the title, and
nothing else: each document keeps explaining its own step, and stops
restating the whole line.

Two shapes, and the difference is about rendering, not about truth:

- `relation` is the **spine**. A extends B means B came first, so the page
  nests A under B and the section reads oldest first.
- `sibling` is the **cross-link**, rendered "alongside" — a rival that
  succeeds nothing still belongs in the family, and joins the component
  through it.

Both are read through `relations.edges()`, which unions a relation with its
declared converse. That is why a one-sided declaration renders correctly
before anyone runs the fixer: the page shows the family the moment the fact
is stated anywhere, and `luria link --fix` makes the documents agree on disk
afterwards.

What is *symmetric*, and whether one side may be written from the other, is
not this module's question — a declared pair is one-sided or it is not,
whether or not any chain walks it. That lives in `relations.py`, and so does
the finding for it. What stays here is the cycle: a succession that loops has
no earliest step, which is a statement about the sequence and nothing else.
It is also the one finding no fixer can repair, because which of two steps
came first is not recoverable from the data.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

from .adr_index import Adr, load_scheme, prefix_for
from . import statuses
from .config import current
from .contract import for_scheme, values_of
from . import relations

MARKER = "<!-- GENERATED by `luria index` — do not edit. -->"


@dataclass
class Line:
    """One weakly-connected sequence: an ordered spine, plus the documents
    attached to it only by a cross-link."""
    spine: list[Adr] = field(default_factory=list)
    alongside: list[Adr] = field(default_factory=list)
    # Each spine member's distance from a root, for the rendered nesting.
    depth: dict[str, int] = field(default_factory=dict)
    # The parent each step renders *under*. The page indents by depth, so
    # nesting only reads correctly when a step is emitted directly after
    # this one; `_order` is what guarantees that. A step with several
    # parents renders under one of them and names the rest.
    under: dict[str, str] = field(default_factory=dict)
    also: dict[str, list[str]] = field(default_factory=dict)

    @property
    def members(self) -> list[Adr]:
        return self.spine + self.alongside


def _codes(doc: Adr, name: str, contract) -> list[str]:
    """The codes one relation field holds on one document. A shape the
    contract rejects is the lint's finding, not this walk's — reading it as
    empty here keeps one mistake reported in one vocabulary."""
    spec = next((f for f in contract.fields if f.name == name), None)
    if spec is None:
        return []
    return [str(v).strip() for v in (values_of(spec, doc.meta.get(name)) or [])]


def _load(chain) -> tuple[dict[str, Adr], dict[str, list[str]],
                          dict[str, list[str]]]:
    """Every document of the chain's scheme, and its two relations, keyed by
    code and filtered to codes that land — a reference to something outside
    the scheme is the contract's finding, not a node here."""
    scheme = current().schemes[chain.scheme]
    docs = {d.code: d for d in load_scheme(scheme)}
    # One spine, spelled by one relation or several (#211). Unioned before
    # the walk, so every step below reads a spine that does not know how
    # many fields filled it — which is what keeps ordering, depth and cycle
    # reporting identical whether a record signs its succession or not.
    held: dict[str, set[str]] = {}
    for field in chain.relation:
        for code, targets in relations.edges(chain.scheme, field).items():
            held.setdefault(code, set()).update(targets)
    apart = (relations.edges(chain.scheme, chain.sibling)
             if chain.sibling else {})
    spine = {code: sorted(held.get(code, ())) for code in docs}
    cross = {code: sorted(apart.get(code, ())) for code in docs}
    return docs, spine, cross


def _components(codes: list[str], neighbours: dict[str, set[str]]
                ) -> list[list[str]]:
    """Maximal weakly-connected groups, in the order their earliest member
    appears — so the page's sections are stable across runs."""
    seen: set[str] = set()
    out: list[list[str]] = []
    for start in codes:
        if start in seen or not neighbours[start]:
            continue
        group, stack = [], [start]
        seen.add(start)
        while stack:
            code = stack.pop()
            group.append(code)
            for other in sorted(neighbours[code]):
                if other not in seen:
                    seen.add(other)
                    stack.append(other)
        out.append(sorted(group))
    return out


def _depths(group: list[str], spine: dict[str, list[str]]) -> dict[str, int]:
    """Distance from a root, longest-path so a step never renders above
    something it extends. Bounded by the group's size, which is what keeps a
    cycle from spinning here rather than being reported."""
    depth = {c: 0 for c in group if spine[c]}
    for _ in range(len(group)):
        changed = False
        for code in group:
            if not spine[code]:
                continue
            want = max(depth.get(p, 0) for p in spine[code]) + 1
            if want > depth[code]:
                depth[code], changed = want, True
        if not changed:
            break
    for code in group:
        depth.setdefault(code, 0)
    return depth


def _order(group: list[str], spine: dict[str, list[str]],
           depth: dict[str, int]) -> tuple[list[str], dict[str, str],
                                           dict[str, list[str]]]:
    """The spine in render order: every step immediately after the parent it
    nests under.

    Sorting by `(depth, code)` is not enough, and the way it fails is silent.
    The page carries nesting as indentation, so a step at depth d+1 reads as
    a child of whatever step at depth d preceded it — which, under a plain
    sort, is whichever one happened to sort last. One group with two roots,
    or one step with two parents, and the page asserts a descent nobody
    declared. Found in `anthology-of-the-sota`, where Kimi Linear rendered
    as a descendant of Mamba-3 because Gated DeltaNet has two parents.

    So: choose one parent per step — the deepest, ties broken by code, so a
    step nests under the most specific thing it extends — and emit each
    subtree depth-first from its root. The other parents are real and are
    returned to be named rather than dropped."""
    kids: dict[str, list[str]] = {c: [] for c in group}
    under: dict[str, str] = {}
    also: dict[str, list[str]] = {}
    for code in sorted(group):
        parents = [p for p in spine[code] if p in depth]
        if not parents:
            continue
        best = sorted(parents, key=lambda p: (-depth[p], p))[0]
        under[code] = best
        kids[best].append(code)
        rest = sorted(p for p in parents if p != best)
        if rest:
            also[code] = rest
    order: list[str] = []
    def emit(code: str) -> None:
        order.append(code)
        for kid in sorted(kids[code], key=lambda c: (depth[c], c)):
            emit(kid)
    for code in sorted(group, key=lambda c: (depth[c], c)):
        if code not in under:
            emit(code)
    # A cycle leaves its members unreachable from any root; they are the
    # `rows()` finding, and dropping them here would hide it.
    order += [c for c in sorted(group, key=lambda c: (depth[c], c))
              if c not in order]
    return order, under, also


def lines_of(chain) -> list[Line]:
    """Every sequence in one chain, spines ordered oldest first.

    A document is on the spine when it extends something or something
    extends it; one attached only by a cross-link renders alongside. Both
    the page and `walk()` come through here, so the view and the query
    cannot disagree about what a line contains."""
    docs, spine, cross = _load(chain)
    neighbours: dict[str, set[str]] = {c: set() for c in docs}
    for code in docs:
        for other in spine[code] + cross[code]:
            neighbours[code].add(other)
            neighbours[other].add(code)
    out: list[Line] = []
    for group in _components(sorted(docs), neighbours):
        depth = _depths(group, spine)
        order, under, also = _order(group, spine, depth)
        line = Line(depth=depth, under=under, also=also)
        for code in order:
            on_spine = bool(spine[code]) or any(code in spine[o] for o in group)
            (line.spine if on_spine else line.alongside).append(docs[code])
        out.append(line)
    return out


def walk() -> list[Line]:
    """Every sequence in every declared chain."""
    return [line for chain in current().chains.values()
            for line in lines_of(chain)]


def rows() -> list[str]:
    """A succession that loops: always wrong, mechanically detectable, and
    not repairable — which of two steps came first is not in the data.

    A relation stated on only one side used to be reported here too. It
    moved to `relations.py`, because it is a fact about the relation and not
    about any chain that happens to walk it: a declared pair is one-sided or
    it is not, whether or not a page renders it."""
    cfg = current()
    found: list[str] = []
    for chain in cfg.chains.values():
        docs, spine, _ = _load(chain)
        for code in sorted(docs):
            for reached in sorted(_reaches(code, spine)):
                if code in spine[reached] and code < reached:
                    found.append(
                        f"{cfg.rel(docs[code].path)}: {_spine(chain)} "
                        f"makes a cycle — {code} and {reached} each come "
                        f"before the other, so neither is the earlier step")
    return sorted(set(found))


def _spine(chain) -> str:
    """The chain's spine relations, as prose — `` `extends:` `` for the
    common case and `` `extends:` and `corrects:` `` for a signed one. One
    implementation, because the cycle finding and the page header name the
    same thing and drifting apart would be a small lie in two voices."""
    fields = [f"`{f}:`" for f in chain.relation]
    if len(fields) < 3:
        return " and ".join(fields)
    return ", ".join(fields[:-1]) + f" and {fields[-1]}"


def _reaches(start: str, spine: dict[str, list[str]]) -> set[str]:
    """Every code reachable from one, following the spine. Visited-guarded,
    so a cycle terminates rather than being discovered by recursion depth."""
    seen: set[str] = set()
    stack = list(spine[start])
    while stack:
        code = stack.pop()
        if code in seen:
            continue
        seen.add(code)
        stack.extend(spine.get(code, ()))
    return seen


def _link(doc: Adr, chain) -> str:
    """A target that resolves from where the page renders.

    It points at the *source* document, not at the scheme's view directory:
    an index-rendered scheme puts a README and its tag pages there, never a
    page per document, so `docs/literature/LIT-140.md` resolves to nothing.
    The index's own rows have always linked this way, through `prefix_for`,
    and the first version of this function inventing a second convention was
    caught by the first real corpus it met — no fixture had checked that a
    rendered target exists."""
    scheme = current().schemes[chain.scheme]
    return prefix_for(scheme, chain.output.parent) + doc.path.name


def _annotation(doc: Adr, chain) -> str:
    """One step's value along each facet the chain names, in that order.

    Read through the compiled contract rather than raw frontmatter, so a
    field with a `default` shows its default rather than a blank — what
    ADR-076 means by an effective value never being absent — and a `status:`
    carrying a qualifying note reads as its word."""
    obligations = for_scheme(current().schemes[chain.scheme])
    meta = statuses.normalised(doc.meta)
    shown: list[str] = []
    for field in chain.facet_by:
        shown += [str(v) for v in (obligations.reading(field, meta) or ())]
    return ", ".join(shown)


def _step(doc: Adr, chain, lead: str = "") -> str:
    """One line of the rendered list: the code, the title, and the status
    *value*.

    `Adr.status` is the composed display form — `Superseded — by [X](…);
    note` — and this page wants none of that. The successor is the next
    line, so linking it here says twice what the shape already says; and the
    note is an argument about why the step happened, which is the half this
    view deliberately leaves on the document. Rendering the composed form
    also dragged a link authored in the source's frame onto a page that
    renders somewhere else, which is a thing to rebase rather than a thing
    to want. `status_value` is the field, and the fields are why it is
    there to ask for."""
    shown = _annotation(doc, chain)
    return (f"{lead}[{doc.code}]({_link(doc, chain)}) — {doc.title}"
            + (f" *({shown})*" if shown else ""))


def _render(chain, lines: list[Line]) -> str:
    count = f"{len(lines)} line" + ("" if len(lines) == 1 else "s")
    out = [MARKER, "", f"# {chain.title}", "",
           f"{count}, walked from {_spine(chain)} on {chain.scheme} "
           f"documents. Each step explains itself; this page is the order "
           f"they came in.", ""]
    for line in lines:
        head = line.spine[0] if line.spine else line.alongside[0]
        out.append(f"## From {head.title}")
        out.append("")
        for doc in line.spine:
            # A step with several parents nests under one of them; the rest
            # are named here so the page holds every declared edge, not the
            # subset a tree layout can draw.
            extra = line.also.get(doc.code, [])
            tail = (f" — also extends {', '.join(extra)}" if extra else "")
            out.append("  " * line.depth[doc.code] + "- "
                       + _step(doc, chain) + tail)
        for doc in line.alongside:
            out.append(_step(doc, chain, lead="- alongside: "))
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def outputs() -> dict:
    """The rendered pages, for `luria index` to write and `--check` to
    compare — one entry per declared chain, none at all for a project that
    declares none."""
    return {chain.output: _render(chain, lines_of(chain))
            for chain in current().chains.values()}
