#!/usr/bin/env python3
"""The configuration reference, rendered from the config schema itself.

    luria index                 # → <docs>/configuration.md, in Luria's own tree

It renders only where `luria/config.py` is a file the reader can open — see
`Config.owns_schema` (ADR-059). An adopting project gets `record.md` instead,
which describes the record *it* configured; this page is the schema, and the
schema is not theirs to maintain.

Luria's capability surface *is* `luria.yaml`: a scheme, a fragment directory, a
journal, a remote and the site are five composable primitives, and the ADR /
DP / changelog / devlog record this package ships is one instantiation of them
rather than a fixed set of parts. That was true long before this module
existed and was documented nowhere a reader arrives at in time — the prose
lived in `config.py`'s docstrings, and the reasoning lived in the decision
record, which is archaeology, not a reference.

Writing that page by hand would have made it the second copy of a schema that
changes — exactly the hand-maintained projection DP-3 says will drift. So it
is generated, and the load-bearing property is this: **the key tables come
from `dataclasses.fields()`, not from a list kept here.** Add a field to
`Site` and it appears in the reference on the next `luria index`; leave it
undocumented and the row still appears, with its type and default, because
the row was never something anyone had to remember to write.

The prose is this module's, not a per-project stub. A scheme's `README.stub`
exists because a project's decision index needs *its own* preamble; the
configuration reference is Luria describing its own schema, and that text is
identical in every repository that installs the package. A stub here would be
a file every adopter carried and none of them edited.

Three derivations, all mechanical:

- **Which sections exist** — `tables()` reads every dataclass out of
  `config.py`. This was a hand-kept list once, and it rotted exactly as one
  does: `chains` and seven nested tables — where `unique`, `alert`,
  `converse`, `invariant` and `required_when` all live — were absent from the
  reference for as long as they had existed, while every test passed, because
  each asked whether the sections listed were real rather than whether the
  real ones were listed. `ORDER` below is a reading order; anything it does
  not name is appended rather than dropped.
- **Dataclass sections** — `inspect.getdoc()` for the prose (those docstrings
  already carry worked YAML examples, so they stay the single source), plus a
  computed key table.
- **Plain-table sections** — `issue_url`, `paths`, `code`, `lint`, which have
  no dataclass behind them, render straight from `config.DEFAULTS`: keys from
  the schema, prose from `PLAIN`. A key nobody has described still gets a row,
  and `test_config_doc` fails until somebody writes one — the reminder lands
  in CI rather than in a reader's head.

The prose is the only hand-written part, and losing it is a blank cell rather
than a missing row. That asymmetry is the whole design: a table nobody
described renders undescribed, where a table nobody listed renders not at all.

The page registers in `Config.is_generated`, which is what makes it safe to
fill with example codes: `doc_refs.doc_files` filters on that flag, so the
bare-reference lint and `luria link --fix` both skip it, the same way they
skip the status reports.
"""

from __future__ import annotations

import dataclasses
import inspect
import re
from pathlib import Path

from . import config as config_mod
from .adr_index import escape_cell
from .config import (FAMILIES, Chain, FieldGroup, Fragment, Journal,
                     PlainField, Reference, Remote, RemoteScheme, RequiredWhen,
                     Scheme, Site, TagGroup, Vocabulary, VocabularyTable,
                     current)

#: Imported, not re-spelled: `FAMILIES` is the list `config.load` replaces
#: whole, and the shape table in `HEADER` says the same thing in words. The
#: test holds the two together, so a sixth family cannot arrive with the prose
#: still saying five.
_ = FAMILIES

STAMP = ("*Generated by `luria index` from the dataclasses in "
         "`luria/config.py` — built, not edited. A key that exists in the "
         "schema is a row here whether or not anyone remembered to describe "
         "it.*\n")

#: What proves Luria wrote a file at this path — used by `retire` so that
#: cleaning up after the pre-ADR-059 behaviour can never delete a project's
#: own prose that happens to live at the same name.
MARKER = "<!-- GENERATED by `luria index` — edit `luria/config.py`"

HEADER = """# Configuration

<!-- GENERATED by `luria index` — edit `luria/config.py`, not this file. -->

{stamp}
Everything Luria does is driven by one file at the project root,
`luria.yaml`. **Every key has a default**, so a project with the conventional
layout needs only `issue_url` — and Luria runs without the file at all, on
defaults alone, which is what lets `luria init` bootstrap into an empty
repository.

## The shape of the file

The tables below are the whole schema. Five of them — `schemes`, `fragments`,
`journals`, `remotes` and `chains` — are *families*: you name the entries, and
the name you choose becomes part of the vocabulary. `schemes.RFC` is how a
project gets RFCs; `journals.incidents` is how it gets a second
journal. No code path spells `ADR`.

That is worth stating plainly, because this package ships one instantiation of
its own machinery — decisions, principles, a changelog and a devlog — and it
is easy to read those four as Luria's parts. They are its defaults. A record
made of RFCs, specs and a meeting log is the same engine with different
tables.

Two merge rules follow from that split (ADR-047). A *settings* table —
`paths`, `code`, `lint`, `site` — merges per key: setting `docs` does not
clear `reports`. A *family* table is **replaced whole the moment you declare
it**: a project that writes `schemes.RFC` and nothing else has
exactly one scheme, and the shipped `ADR` is simply absent. Declare a family
and it is yours entirely; leave it undeclared and the default stands. This is
also what makes omission meaningful inside a declared family — an `output`
you leave out is genuinely unset, because there is no default entry left for
it to inherit from.

| table | what it configures | families |
|---|---|---|
| `luria` | issue links, staleness horizon, nested records | — |
| `paths` | where the read and write surfaces live | — |
| `vocabularies.<name>` | value sets a scheme's fields point at by name | — |
| `schemes.X` | a referable document family: `ADR`, `RFC`, `SPEC` | yes, keyed by prefix |
| `fragments.<dir>` | many small files assembled into one document | yes, keyed by directory |
| `journals.X` | dated entries that persist, rendered into books | yes, keyed by name |
| `chains.X` | a relation walked transitively, rendered as sequences | yes, keyed by name |
| `remotes.X` | another project's codes, cited from this one | yes, keyed by prefix |
| `code` | which source files are scanned for stale references | — |
| `lint` | which warning classes fail, and which are not reported | — |
| `site` | publishing the record as a browsable site | — |
"""

FOOTER = """
## Environment variables

Two, both escape hatches rather than configuration — they change how a run
behaves, never what the record *is*, which is why they are not in the file.

| variable | effect |
|---|---|
| `LURIA_ROOT` | the project root, overriding the search for `luria.yaml` / `.git`. What lets the test suite run against fixture trees, and what a CI job uses when it checks out a project somewhere other than the working directory. |
| `LURIA_JOBS` | caps the thread pool that renders views, scans files and probes remote URLs. `LURIA_JOBS=1` is the serial escape hatch — the one to reach for when a failure needs a deterministic ordering to reproduce. |

## Running one module without the package

Every command is a plain function, and the modules stay runnable standalone:

    python -m luria.ref_status --all

That is for a project that vendors a single file rather than installing
Luria. The CLI is the supported surface; this is the door left unlocked.

## What is not configurable

Said plainly, because a reference that only lists dials reads as though
everything is one:

- **The lint checks themselves.** They are functions, not a registry — a
  project cannot add a check or switch one off. What it *can* do is promote
  warning classes to failures with `lint.fail_on`, and acknowledge
  individual findings with the comment directives. A check earns its place by
  being always wrong and mechanically fixable; anything else is a report.
- **The frontmatter vocabulary.** `status:`, `title:`, `tags:`, `date:`,
  `version:`, `history:` are fixed field names. Which *statuses* count as in
  force is per-scheme (`active`), but the field they live in is not.
- **The record's shape, from the command line.** Adding `schemes.RFC` costs
  one table, and that table is the only way to add it: there is no
  `luria add-scheme`. Changing a shape that already has documents under it is
  `luria migrate`, which executes a spec committed to `record/migrations.d/`
  — renaming a prefix or moving a document between schemes, swept across the
  repository in one pass. The spec is a file because the rename is a thing
  the record should remember, not an argument typed once.

Two earlier entries in this list are gone because they stopped being true
(ADR-047): the shipped `ADR` scheme *can* be removed — declare the `schemes`
family without it — and a declared scheme's `output` *is* unset by omission,
because a declared family no longer inherits from the defaults. Both are
demonstrated and pinned by `examples/` in the Luria repository, which CI
runs.
"""

# Which class holds which table, and the one sentence that says what the table
# is for. The *membership* of this page is not decided here — `tables()` reads
# the schema — so a class missing from this dict still gets a section, with its
# own name as the heading. What a person supplies is the prose; what the schema
# supplies is the section.
PROSE: dict[type, tuple[str, str]] = {
    Scheme: ("Schemes — `schemes.X`",
     "One entry per referable document family. The key is the prefix codes "
     "carry, so `schemes.RFC` makes `RFC-7` a first-class reference: "
     "`luria link --fix` writes its link, `luria lint` demands one, and "
     "`luria new rfc` scaffolds the next free number — none of which needs "
     "anything beyond the table."),
    Vocabulary: ("Vocabulary fields — `schemes.X.fields.<field>`",
     "A field whose values come from a named set the project declares. "
     "`status` and `tags` are two instances of this shape rather than two "
     "special cases beside it, which is why a scheme can narrow either one."),
    PlainField: ("Plain fields — `schemes.X.fields.<field>`",
     "The same table, for a field that carries no vocabulary: its type is "
     "\"any truthy value\" and what it adds over a `requires` entry is when "
     "the requirement applies."),
    RequiredWhen: ("Conditional requirement — `…fields.<field>.required_when`",
     "A field demanded only while another field says one of a set of "
     "values — the shape a question that is only open while a document is "
     "unsettled actually has."),
    Reference: ("Reference fields — `schemes.X.references.<field>`",
     "A frontmatter field that holds a code from a named scheme. Declaring "
     "the relationship rather than merely requiring the field is what turns "
     "one check into four — present, shaped like a code, resolving to a real "
     "document, and in force — and what lets `luria link --fix` complete a "
     "declared `converse`."),
    TagGroup: ("Tag groups — `schemes.X.fields.<field>.groups.<name>`",
     "Which of a field's values may appear together. A vocabulary says what "
     "a value means; a group says whether the field is an axis or a pile."),
    FieldGroup: ("Field groups — `schemes.X.field_groups.<name>`",
     "Several fields of which an entry must carry some, named for what they "
     "have in common — the shape of *a source*, where `requires` can only "
     "spell one of the fields that would be one."),
    VocabularyTable: ("Vocabularies — `vocabularies.<name>`",
     "The central table a scheme's fields point at by name, so a set of "
     "values and their blurbs are declared once however many fields use "
     "them. A value may be a bare blurb or this nested table."),
    Fragment: ("Fragment directories — `fragments.<dir>`",
     "One entry per directory whose files are assembled into a single "
     "document and then consumed. The changelog is the shipped instance; the "
     "mechanism is not changelog-shaped."),
    Journal: ("Journals — `journals.X`",
     "One entry per stream of dated entries that persist. This is a family "
     "like any other — a project can run a devlog, a meeting log and an "
     "incident log side by side, each with its own granularity and output."),
    Chain: ("Chains — `chains.X`",
     "One entry per relation walked transitively and rendered as sequences. "
     "Where a reference field gives a document its neighbours, a chain "
     "answers the question no single document holds: what line of work is "
     "this a step in?"),
    Remote: ("Remotes — `remotes.X`",
     "One entry per foreign project whose codes this record cites. The `uid` "
     "key is the general case: with a regex and a URL template, a remote need "
     "not hold a Luria-shaped record — or any record — at all, which is how "
     "arXiv identifiers, ticket keys and CVE numbers become linted "
     "references."),
    RemoteScheme: ("Per-scheme remote construction — `remotes.X.schemes.Y`",
     "Optional, and only for a remote whose code families do not all "
     "construct the same way — a file per code in one, sections of a single "
     "page in another."),
    Site: ("The site — `site`",
     "Publishing the record as a browsable vault. Every key derives from "
     "`issue_url` for a GitHub project, so the conventional case needs no "
     "table at all."),
}

#: The one dataclass in `config.py` that is not a table in `luria.yaml`:
#: `Config` is the parsed *result*, the object every command reads, and its
#: fields are flattened from the tables below rather than written anywhere.
#: A denylist of one, so that everything else is covered by default — the
#: safe direction, because a table nobody described renders undescribed
#: where a table nobody listed renders not at all.
NOT_A_TABLE = ("Config",)

#: Reading order. Membership is `tables()`'s, not this list's: a class missing
#: here is appended rather than dropped, so a new nested table lands at the end
#: of the page instead of nowhere.
ORDER = [Scheme, Vocabulary, PlainField, RequiredWhen, Reference, TagGroup,
         FieldGroup, VocabularyTable, Fragment, Journal, Chain, Remote,
         RemoteScheme, Site]


def tables() -> list[type]:
    """Every config dataclass, in reading order.

    Derived for the same reason the rows are, and after the same failure: the
    list this replaced was hand-kept, and `chains` plus seven nested tables
    were missing from the reference for as long as they had existed. The rows
    inside a section were always safe; which sections existed at all was not,
    and a page can be wrong by omission as easily as by a wrong row (DP-3)."""
    found = [obj for name, obj in vars(config_mod).items()
             if isinstance(obj, type) and dataclasses.is_dataclass(obj)
             and obj.__module__ == config_mod.__name__
             and name not in NOT_A_TABLE]
    known = [cls for cls in ORDER if cls in found]
    return known + [cls for cls in found if cls not in known]


def sections() -> list[tuple[str, type, str]]:
    """(title, class, blurb) per section — membership from the schema.

    A class `PROSE` does not name still gets a section, headed by its own
    name: a reader learns the table exists and that nobody has described it,
    which beats learning nothing."""
    out = []
    for cls in tables():
        title, blurb = PROSE.get(cls, (f"`{cls.__name__}`", ""))
        out.append((title, cls, blurb))
    return out


SECTIONS: list[tuple[str, type, str]] = sections()

# The dict-valued `DEFAULTS` keys that are rendered as a table somewhere else —
# either a dataclass section or one of `PLAIN`'s flat sub-tables. Anything else
# whose default is a dict is a free-form mapping and belongs in the table above
# it, as a row like any other key.
SECTION_SUBTREES: frozenset[str] = frozenset(
    {"paths", "lint", "site", "code", "schemes", "chains", "remotes",
     "journals", "fragments", "vocabularies"})

# Prose for the tables that have no dataclass behind them: scalars at the top
# level, and the three flat sub-tables. Each is (title, DEFAULTS subtree, blurb,
# prose) where prose maps key → description; an empty subtree name means the
# top level. The *keys* are `config.DEFAULTS`' — `plain_keys` reads them —
# because a list of them kept here is the thing that lost `lint.mute` and
# `lint.network`. A key with no prose still gets a row; `test_config_doc`
# fails until someone writes one, which is the right place for the reminder.
PLAIN: list[tuple[str, str, str, dict[str, str]]] = [
    ("Top level — `luria`", "", "", {
        "issue_url": "A template for issue links, with `{n}` for the number. "
                     "Writing it also tells Luria which GitHub repository "
                     "this is, which is where every `site` default "
                     "comes from. Unset, issue numbers stay bare rather than "
                     "linking somewhere wrong.",
        "stale_days": "How long a document may sit undecided before the "
                      "pending-decisions report calls it out.",
        "user_agent": "What Luria announces when it opens a socket — the "
                      "identifier check and remote discovery both send it. "
                      "The default is `luria/<version>`: honest about the "
                      "software, the way `curl/8.0` is, and carrying no "
                      "contact, because a URL or mailbox in a shipped "
                      "default would route every user's traffic to whoever "
                      "maintains Luria. Add your own contact here if you "
                      "want the treatment some hosts reserve for callers "
                      "who identify themselves — CrossRef's polite pool "
                      "wants a real address — since that address belongs to "
                      "your record rather than to Luria.",
        "include_records": "Globs naming further records inside this "
                           "repository — `examples/*` — each read with its "
                           "own `luria.yaml` and linted in the same run. What "
                           "makes a worked example a thing CI exercises "
                           "rather than a directory of prose nobody runs.",
    }),
    ("Paths — `paths`", "paths", "The read/write boundary: `docs/` is where a "
     "reader browses, `record/` is where a contributor files.", {
        "docs": "The read surface — prose plus every generated view.",
        "decisions": "The default scheme's source directory. Kept as its own "
                     "key for projects that predate `schemes.X`.",
        "design_principles": "Where the principles document renders.",
        "reports": "Where the status reports land. Committed views rather "
                   "than build artifacts, so a README badge has a real page "
                   "to point at.",
    }),
    ("Code scanning — `code`", "code", "Which files outside the record are "
     "checked for references to retired documents. A decision number in a "
     "code comment is the strongest form of the claim being checked — it is "
     "the stated reason the code is shaped that way.", {
        "globs": "Source files to scan, as glob patterns.",
        "historical": "Files that are true about the day they were written "
                      "and never updated — scanning them produces permanent, "
                      "unactionable noise. Journals are covered "
                      "automatically.",
    }),
    ("Enforcement — `lint`", "lint", "The dial between reported and enforced. "
     "Status findings are warnings by default; a class named here fails "
     "`luria lint` instead. Acknowledgement directives keep working under "
     "enforcement, because only unacknowledged rows ever reach a class.", {
        "fail_on": "Warning classes promoted to failures.",
        "baseline": "A standing count per warning class, for a record whose "
                    "residue is real and not shrinking. A class at or below "
                    "its number reports as usual; above it, the excess is a "
                    "violation naming both figures, and the rows still print "
                    "because which ones are new is not knowable from a count. "
                    "Below it, and when the class has cleared entirely, the "
                    "run says so — a baseline nobody lowers is a ratchet "
                    "pointing the wrong way. This is what `fail_on` cannot "
                    "say (it fails at the first row) and what `mute` cannot "
                    "say (it hides the new rows with the old). A count of "
                    "`0` is `fail_on` in this dial's dialect; naming a class "
                    "in both, or in this and `mute`, is refused rather than "
                    "resolved. An unknown class or a negative count is "
                    "reported and then ignored for gating.",
        "mute": "Warning classes not reported at all. Where `fail_on` changes "
                "a finding's consequence, this removes it from the run — the "
                "blunter instrument, for a check a project has decided is not "
                "useful to it, where an acknowledgement directive is the "
                "right shape when the finding is about one document. Naming a "
                "class in both is refused rather than resolved. `luria "
                "reports` renders the full accounting either way.",
        "narrow_terms": "This project's own concrete nouns. A title in a "
                        "scheme marked `titles_generalize` that names one is "
                        "reported as `narrow-titles`. Luria ships none — the "
                        "words are yours, and empty means the class never "
                        "fires.",
        "network": "How far `luria lint` may reach to check what a cited "
                   "identifier actually is. `auto` asks only about "
                   "identifiers the lockfile has no answer for and falls back "
                   "to reporting them unchecked; `never` answers from the "
                   "lockfile alone, for the hermetic build; `require` makes "
                   "an unreachable remote a failure, so a green run means the "
                   "references were verified rather than remembered.",
    }),
]


def plain_keys(subtree: str) -> list[str]:
    """The keys of one scalar table, read from `config.DEFAULTS`.

    A key whose default is a *dict* is usually a table in its own right —
    `paths`, `lint`, `schemes`, `chains` — and has its own section, so it is
    not also a row in the table above it.

    Usually, not always. A *free-form mapping* — `lint.baseline`, whose keys
    are warning-class names a project chooses — has no fixed shape, so nothing
    generates a section for it, and excluding it on the strength of its type
    dropped it out of the reference entirely and out of the "a key with no
    prose still gets a row" guard with it. The test for a table is whether
    something renders one, which is `SECTION_SUBTREES`, not whether the
    default happens to be a `dict`."""
    defaults = config_mod.DEFAULTS.get(subtree, {}) if subtree \
        else config_mod.DEFAULTS
    return [k for k, v in defaults.items()
            if not isinstance(v, dict) or k not in SECTION_SUBTREES]


# A run of 4-space-indented lines inside a docstring is a worked example. The
# docstrings write them as indented blocks because that is what reads well in
# a terminal; a fenced block is what reads well on a page.
_INDENTED = re.compile(r"(?m)^(?:    .*(?:\n|$))+")


def fence(text: str, lang: str = "yaml") -> str:
    """Indented example blocks in a docstring → fenced code blocks."""
    def swap(m: re.Match) -> str:
        body = "\n".join(line[4:] for line in m.group(0).rstrip("\n").split("\n"))
        return f"```{lang}\n{body}\n```\n"
    return _INDENTED.sub(swap, text)


# Presentation only — which fields are not keys a person writes. The key
# *list* is still `dataclasses.fields()`, so a field missing from these sets
# still gets a row; it is merely labelled `*required*` until someone
# classifies it, which is the safe direction to be wrong in.
FROM_TABLE_NAME: dict[type, set[str]] = {
    Scheme: {"prefix"},          # `schemes.ADR` → prefix "ADR"
    Journal: {"name"},           # `journals.devlog` → name "devlog"
    Remote: {"prefix"},          # …but `Remote.name` IS a key, deliberately
    RemoteScheme: {"prefix"},
}
DERIVED: dict[type, set[str]] = {
    Site: {"title", "base_url", "source_url"},   # …off `issue_url` (DP-3)
}


def rows(cls: type) -> list[tuple[str, str, str]]:
    """(key, type, default) for every public field of a config dataclass.

    The whole point of the module: this reads the schema rather than a list,
    so a field added to `Site` cannot be silently missing from the reference.

    The default shown is the *dataclass's* — the answer to "what do I get if I
    omit this key?", which is the question a reference is asked. What the
    shipped `luria.yaml` happens to set for its own ADR scheme is a different
    question, and answering it here would tell a project adding a second
    scheme that `output` defaults to `docs/decisions`, which is false."""
    out = []
    for f in dataclasses.fields(cls):
        if f.name.startswith("_"):
            continue
        if f.default is not dataclasses.MISSING:
            shown = f.default
        elif f.default_factory is not dataclasses.MISSING:  # type: ignore[misc]
            shown = f.default_factory()  # type: ignore[misc]
        else:
            shown = dataclasses.MISSING
        if f.name in FROM_TABLE_NAME.get(cls, ()):
            label = "*the table's own name*"
        elif f.name in DERIVED.get(cls, ()):
            label = "*derived from `issue_url`*"
        else:
            label = _render_default(shown)
        out.append((f.name, str(f.type), label))
    return out


def _render_default(value) -> str:
    if value is dataclasses.MISSING:
        return "*required*"
    if value in ((), [], {}, "", None):
        return "*unset*"
    return f"`{value!r}`" if not isinstance(value, str) else f"`\"{value}\"`"


def table(cls: type) -> str:
    # `escape_cell` because a union annotation carries the same `|` markdown
    # uses for a column boundary — `Path | None` silently becomes two columns
    # otherwise, and every row below it shifts.
    lines = ["| key | type | default |", "|---|---|---|"]
    for name, type_, default in rows(cls):
        lines.append(f"| `{name}` | `{escape_cell(type_)}` | {default} |")
    return "\n".join(lines) + "\n"


def plain_table(keys: list[str], defaults: dict, prose: dict[str, str]) -> str:
    """One scalar table. `keys` is the schema's, `prose` is a person's.

    A key with no prose renders with an empty description rather than not at
    all — the stamp's promise, and the only behaviour under which the page
    cannot quietly lose a key nobody got around to writing about."""
    lines = ["| key | default | what it does |", "|---|---|---|"]
    for name in keys:
        lines.append(f"| `{name}` | {_render_default(defaults.get(name, ''))} "
                     f"| {prose.get(name, '')} |")
    return "\n".join(lines) + "\n"


def render() -> str:
    parts = [HEADER.format(stamp=STAMP)]

    for title, subtree, blurb, prose in PLAIN:
        defaults = config_mod.DEFAULTS.get(subtree, {}) if subtree \
            else config_mod.DEFAULTS
        parts.append(f"\n## {title}\n")
        if blurb:
            parts.append(f"\n{blurb}\n")
        parts.append("\n" + plain_table(plain_keys(subtree), defaults, prose))

    # `sections()`, not the `SECTIONS` snapshot: the page is rendered from
    # the schema as it is at render time, and a module-level constant is one
    # more copy that could be the stale one.
    for title, cls, blurb in sections():
        parts.append(f"\n## {title}\n\n{blurb}\n\n")
        parts.append(fence(inspect.getdoc(cls) or "").rstrip("\n") + "\n\n")
        parts.append(table(cls))

    parts.append(FOOTER)
    return "".join(parts)


def outputs(out_dir: Path | None = None) -> dict[Path, str]:
    """The reference, keyed by where it lands — the unit `luria index`
    renders, so a stale page fails the same check as every other view."""
    cfg = current()
    path = cfg.config_doc if out_dir is None else out_dir / "configuration.md"
    return {path: render()}


def retire() -> list[Path]:
    """Remove a configuration reference this project no longer generates.

    Until ADR-059 the page rendered into every adopting project, so an upgrade
    leaves one behind: a vendored copy of Luria's schema, already a release out
    of date, with nothing in the repository responsible for keeping it true.
    Left alone it is worse than absent, because it reads as current.

    Deleting a file in somebody else's repository wants a reason better than
    "we stopped writing it", so the guard is the generator's own marker: its
    presence is proof Luria wrote this file, and its absence means the path is
    the project's own prose and is left exactly where it is."""
    cfg = current()
    path = cfg.config_doc
    if cfg.owns_schema or not path.exists():
        return []
    if MARKER not in path.read_text(encoding="utf-8"):
        return []
    path.unlink()
    return [path]


def write(out_dir: Path | None = None) -> list[Path]:
    rendered = outputs(out_dir)
    for path, text in rendered.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    return sorted(rendered)


if __name__ == "__main__":
    import fire
    fire.Fire(write)
