#!/usr/bin/env python3
"""The configuration reference, rendered from the config schema itself.

    luria index                 # → <docs>/configuration.md, with every other view

Luria's capability surface *is* `luria.toml`: a scheme, a fragment directory, a
journal, a remote and the site are five composable primitives, and the ADR /
DP / changelog / devlog record this package ships is one instantiation of them
rather than a fixed set of parts. That was true long before this module
existed and was documented nowhere a reader arrives at in time — the prose
lived in `config.py`'s docstrings, and the reasoning lived in the decision
record, which is archaeology, not a reference.

Writing that page by hand would have made it the second copy of a schema that
changes — exactly the hand-maintained projection DP-3 says will drift. So it
is generated, and the load-bearing property is this: **the key tables come
from `dataclasses.fields()`, not from a list kept here.** Add a field to
`Site` and it appears in the reference on the next `luria index`; leave it
undocumented and the row still appears, with its type and default, because
the row was never something anyone had to remember to write.

The prose is this module's, not a per-project stub. A scheme's `README.stub`
exists because a project's decision index needs *its own* preamble; the
configuration reference is Luria describing its own schema, and that text is
identical in every repository that installs the package. A stub here would be
a file every adopter carried and none of them edited.

Two derivations, both mechanical:

- **Dataclass sections** — `inspect.getdoc()` for the prose (those docstrings
  already carry worked TOML examples, so they stay the single source), plus a
  computed key table.
- **Plain-table sections** — `issue_url`, `paths`, `code`, `lint`, which have
  no dataclass behind them, render straight from `config.DEFAULTS`.

The page registers in `Config.is_generated`, which is what makes it safe to
fill with example codes: `doc_refs.doc_files` filters on that flag, so the
bare-reference lint and `luria link --fix` both skip it, the same way they
skip the status reports.
"""

from __future__ import annotations

import dataclasses
import inspect
import re
from pathlib import Path

from . import config as config_mod
from .adr_index import escape_cell
from .config import Fragment, Journal, Remote, RemoteScheme, Scheme, Site, current

STAMP = ("*Generated by `luria index` from the dataclasses in "
         "`luria/config.py` — built, not edited. A key that exists in the "
         "schema is a row here whether or not anyone remembered to describe "
         "it.*\n")

HEADER = """# Configuration

<!-- GENERATED by `luria index` — edit `luria/config.py`, not this file. -->

{stamp}
Everything Luria does is driven by one file at the project root,
`luria.toml`. **Every key has a default**, so a project with the conventional
layout needs only `issue_url` — and Luria runs without the file at all, on
defaults alone, which is what lets `luria init` bootstrap into an empty
repository.

## The shape of the file

The tables below are the whole schema. Four of them — `schemes`, `fragments`,
`journals` and `remotes` — are *families*: you name the entries, and the name
you choose becomes part of the vocabulary. `[luria.schemes.RFC]` is how a
project gets RFCs; `[luria.journals.incidents]` is how it gets a second
journal. No code path spells `ADR`.

That is worth stating plainly, because this package ships one instantiation of
its own machinery — decisions, principles, a changelog and a devlog — and it
is easy to read those four as Luria's parts. They are its defaults. A record
made of RFCs, specs and a meeting log is the same engine with different
tables.

The defaults themselves do spell `ADR`, though, and configuration *merges*
over them rather than replacing them. Two consequences worth knowing before
you design around them, both under "What is not configurable" below: the
shipped `ADR` scheme cannot be removed, and omitting its `output` inherits
`docs/decisions` rather than collocating the view.

| table | what it configures | families |
|---|---|---|
| `[luria]` | issue links, staleness horizon | — |
| `[luria.paths]` | where the read and write surfaces live | — |
| `[luria.schemes.X]` | a referable document family: `ADR`, `RFC`, `SPEC` | yes, keyed by prefix |
| `[luria.fragments."dir"]` | many small files assembled into one document | yes, keyed by directory |
| `[luria.journals.X]` | dated entries that persist, rendered into books | yes, keyed by name |
| `[luria.remotes.X]` | another project's codes, cited from this one | yes, keyed by prefix |
| `[luria.code]` | which source files are scanned for stale references | — |
| `[luria.lint]` | which warning classes fail the build | — |
| `[luria.site]` | publishing the record as a browsable site | — |
"""

FOOTER = """
## Environment variables

Two, both escape hatches rather than configuration — they change how a run
behaves, never what the record *is*, which is why they are not in the file.

| variable | effect |
|---|---|
| `LURIA_ROOT` | the project root, overriding the search for `luria.toml` / `.git`. What lets the test suite run against fixture trees, and what a CI job uses when it checks out a project somewhere other than the working directory. |
| `LURIA_JOBS` | caps the thread pool that renders views, scans files and probes remote URLs. `LURIA_JOBS=1` is the serial escape hatch — the one to reach for when a failure needs a deterministic ordering to reproduce. |

## Running one module without the package

Every command is a plain function, and the modules stay runnable standalone:

    python -m luria.ref_status --all

That is for a project that vendors a single file rather than installing
Luria. The CLI is the supported surface; this is the door left unlocked.

## What is not configurable

Said plainly, because a reference that only lists dials reads as though
everything is one:

- **The lint checks themselves.** They are functions, not a registry — a
  project cannot add a check or switch one off. What it *can* do is promote
  warning classes to failures with `[luria.lint] fail_on`, and acknowledge
  individual findings with the comment directives. A check earns its place by
  being always wrong and mechanically fixable; anything else is a report.
- **The frontmatter vocabulary.** `status:`, `title:`, `tags:`, `date:`,
  `version:`, `history:` are fixed field names. Which *statuses* count as in
  force is per-scheme (`active`), but the field they live in is not.
- **Renaming a scheme in place.** Adding `[luria.schemes.RFC]` costs one
  table; renaming an existing scheme, or moving its documents, is currently a
  manual pass — there is no migration command. The decision that would give
  it one is still Proposed.
- **Removing the shipped `ADR` scheme.** Configuration merges over the
  defaults rather than replacing them, and the defaults define
  `[luria.schemes.ADR]`. A project that wants only RFCs still carries an ADR
  scheme and still renders an empty decision index. Leaving it empty is
  harmless; deleting it is not possible today.
- **Collocating `ADR` by omitting `output`.** Same merge, sharper edge. For a
  scheme you invent, an omitted `output` is genuinely unset and the view
  renders beside its sources. For `ADR` it inherits `docs/decisions` from the
  defaults — so a project that points `dir` at its existing decisions and
  omits `output`, expecting to keep its layout, finds the index relocated.
  Write `output` equal to `dir` instead.

Both `ADR` limits are demonstrated and pinned by `examples/` in the Luria
repository, which CI runs.
"""

# The families, in the order the reference reads them: the two that define a
# project's own documents first, then the ones that connect and publish it.
SECTIONS: list[tuple[str, type, str]] = [
    ("Schemes — `[luria.schemes.X]`", Scheme,
     "One entry per referable document family. The key is the prefix codes "
     "carry, so `[luria.schemes.RFC]` makes `RFC-7` a first-class reference: "
     "`luria link --fix` writes its link, `luria lint` demands one, and "
     "`luria new rfc` scaffolds the next free number — none of which needs "
     "anything beyond the table."),
    ("Fragment directories — `[luria.fragments.\"dir\"]`", Fragment,
     "One entry per directory whose files are assembled into a single "
     "document and then consumed. The changelog is the shipped instance; the "
     "mechanism is not changelog-shaped."),
    ("Journals — `[luria.journals.X]`", Journal,
     "One entry per stream of dated entries that persist. This is a family "
     "like any other — a project can run a devlog, a meeting log and an "
     "incident log side by side, each with its own granularity and output."),
    ("Remotes — `[luria.remotes.X]`", Remote,
     "One entry per foreign project whose codes this record cites. The `uid` "
     "key is the general case: with a regex and a URL template, a remote need "
     "not hold a Luria-shaped record — or any record — at all, which is how "
     "arXiv identifiers, ticket keys and CVE numbers become linted "
     "references."),
    ("Per-scheme remote construction — `[luria.remotes.X.schemes.Y]`",
     RemoteScheme,
     "Optional, and only for a remote whose code families do not all "
     "construct the same way — a file per code in one, sections of a single "
     "page in another."),
    ("The site — `[luria.site]`", Site,
     "Publishing the record as a browsable vault. Every key derives from "
     "`issue_url` for a GitHub project, so the conventional case needs no "
     "table at all."),
]

# Rows for the tables that have no dataclass behind them: scalars at the top
# level, and the three flat sub-tables. Each is (title, DEFAULTS subtree, blurb,
# rows) and each row is (key, prose) — the *default* is never written here, it
# is read from `config.DEFAULTS`. An empty subtree name means the top level.
PLAIN: list[tuple[str, str, str, list[tuple[str, str]]]] = [
    ("Top level — `[luria]`", "", "", [
        ("issue_url", "A template for issue links, with `{n}` for the number. "
                      "Writing it also tells Luria which GitHub repository "
                      "this is, which is where every `[luria.site]` default "
                      "comes from. Unset, issue numbers stay bare rather than "
                      "linking somewhere wrong."),
        ("stale_days", "How long a document may sit undecided before the "
                       "pending-decisions report calls it out."),
    ]),
    ("Paths — `[luria.paths]`", "paths", "The read/write boundary: `docs/` is where a "
     "reader browses, `record/` is where a contributor files.", [
        ("docs", "The read surface — prose plus every generated view."),
        ("decisions", "The default scheme's source directory. Kept as its own "
                      "key for projects that predate `[luria.schemes.X]`."),
        ("design_principles", "Where the principles document renders."),
        ("reports", "Where the status reports land. Committed views rather "
                    "than build artifacts, so a README badge has a real page "
                    "to point at."),
    ]),
    ("Code scanning — `[luria.code]`", "code", "Which files outside the record are "
     "checked for references to retired documents. A decision number in a "
     "code comment is the strongest form of the claim being checked — it is "
     "the stated reason the code is shaped that way.", [
        ("globs", "Source files to scan, as glob patterns."),
        ("historical", "Files that are true about the day they were written "
                       "and never updated — scanning them produces permanent, "
                       "unactionable noise. Journals are covered "
                       "automatically."),
    ]),
    ("Enforcement — `[luria.lint]`", "lint", "The dial between reported and enforced. "
     "Status findings are warnings by default; a class named here fails "
     "`luria lint` instead. Acknowledgement directives keep working under "
     "enforcement, because only unacknowledged rows ever reach a class.", [
        ("fail_on", "Warning classes promoted to failures."),
    ]),
]

# A run of 4-space-indented lines inside a docstring is a worked example. The
# docstrings write them as indented blocks because that is what reads well in
# a terminal; a fenced block is what reads well on a page.
_INDENTED = re.compile(r"(?m)^(?:    .*(?:\n|$))+")


def fence(text: str, lang: str = "toml") -> str:
    """Indented example blocks in a docstring → fenced code blocks."""
    def swap(m: re.Match) -> str:
        body = "\n".join(line[4:] for line in m.group(0).rstrip("\n").split("\n"))
        return f"```{lang}\n{body}\n```\n"
    return _INDENTED.sub(swap, text)


# Presentation only — which fields are not keys a person writes. The key
# *list* is still `dataclasses.fields()`, so a field missing from these sets
# still gets a row; it is merely labelled `*required*` until someone
# classifies it, which is the safe direction to be wrong in.
FROM_TABLE_NAME: dict[type, set[str]] = {
    Scheme: {"prefix"},          # `[luria.schemes.ADR]` → prefix "ADR"
    Journal: {"name"},           # `[luria.journals.devlog]` → name "devlog"
    Remote: {"prefix"},          # …but `Remote.name` IS a key, deliberately
    RemoteScheme: {"prefix"},
}
DERIVED: dict[type, set[str]] = {
    Site: {"title", "base_url", "source_url"},   # …off `issue_url` (DP-3)
}


def rows(cls: type) -> list[tuple[str, str, str]]:
    """(key, type, default) for every public field of a config dataclass.

    The whole point of the module: this reads the schema rather than a list,
    so a field added to `Site` cannot be silently missing from the reference.

    The default shown is the *dataclass's* — the answer to "what do I get if I
    omit this key?", which is the question a reference is asked. What the
    shipped `luria.toml` happens to set for its own ADR scheme is a different
    question, and answering it here would tell a project adding a second
    scheme that `output` defaults to `docs/decisions`, which is false."""
    out = []
    for f in dataclasses.fields(cls):
        if f.name.startswith("_"):
            continue
        if f.default is not dataclasses.MISSING:
            shown = f.default
        elif f.default_factory is not dataclasses.MISSING:  # type: ignore[misc]
            shown = f.default_factory()  # type: ignore[misc]
        else:
            shown = dataclasses.MISSING
        if f.name in FROM_TABLE_NAME.get(cls, ()):
            label = "*the table's own name*"
        elif f.name in DERIVED.get(cls, ()):
            label = "*derived from `issue_url`*"
        else:
            label = _render_default(shown)
        out.append((f.name, str(f.type), label))
    return out


def _render_default(value) -> str:
    if value is dataclasses.MISSING:
        return "*required*"
    if value in ((), [], {}, "", None):
        return "*unset*"
    return f"`{value!r}`" if not isinstance(value, str) else f"`\"{value}\"`"


def table(cls: type) -> str:
    # `escape_cell` because a union annotation carries the same `|` markdown
    # uses for a column boundary — `Path | None` silently becomes two columns
    # otherwise, and every row below it shifts.
    lines = ["| key | type | default |", "|---|---|---|"]
    for name, type_, default in rows(cls):
        lines.append(f"| `{name}` | `{escape_cell(type_)}` | {default} |")
    return "\n".join(lines) + "\n"


def plain_table(keys: list[tuple[str, str]], defaults: dict) -> str:
    lines = ["| key | default | what it does |", "|---|---|---|"]
    for name, prose in keys:
        lines.append(f"| `{name}` | {_render_default(defaults.get(name, ''))} "
                     f"| {prose} |")
    return "\n".join(lines) + "\n"


def render() -> str:
    parts = [HEADER.format(stamp=STAMP)]

    for title, subtree, blurb, keys in PLAIN:
        defaults = config_mod.DEFAULTS.get(subtree, {}) if subtree \
            else config_mod.DEFAULTS
        parts.append(f"\n## {title}\n")
        if blurb:
            parts.append(f"\n{blurb}\n")
        parts.append("\n" + plain_table(keys, defaults))

    for title, cls, blurb in SECTIONS:
        parts.append(f"\n## {title}\n\n{blurb}\n\n")
        parts.append(fence(inspect.getdoc(cls) or "").rstrip("\n") + "\n\n")
        parts.append(table(cls))

    parts.append(FOOTER)
    return "".join(parts)


def outputs(out_dir: Path | None = None) -> dict[Path, str]:
    """The reference, keyed by where it lands — the unit `luria index`
    renders, so a stale page fails the same check as every other view."""
    cfg = current()
    path = cfg.config_doc if out_dir is None else out_dir / "configuration.md"
    return {path: render()}


def write(out_dir: Path | None = None) -> list[Path]:
    rendered = outputs(out_dir)
    for path, text in rendered.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
    return sorted(rendered)


if __name__ == "__main__":
    import fire
    fire.Fire(write)
