"""`luria init` — scaffold the record a project's config declares.

    luria init                    # into the current project root
    luria init --config my.toml   # install this config, scaffold its shape
    luria init --into PATH
    luria init --dry-run          # list what would be written

The scaffold is planned from configuration, not copied from a fixed tree
(ADR-048). Three sources, in order: a file named with `--config`; a
`luria.toml` the project already has at its root; and the shipped template's
config, which is what a bare `luria init` has always meant. Whichever wins,
the plan is the same function of it: a directory and a `_template.md` for
every scheme, journal and fragment directory the config declares, a stub for
every scheme's view, the docs index listing exactly the views this record
renders, and the agent file and workflows from the template.

The shipped ADR and DP schemes keep their rich templates — the decision
doctrine and the seed principles are the content this package has to offer a
default-shaped record. Any other scheme gets a neutral template and a stub
titled after itself: Luria has no opinion about what an RFC should say.

The seed principles are deliberately about *the record itself* — drift, locks,
one authoritative implementation. They ship whenever the config declares a
document-rendered DP scheme, which is the shape they were written for. Delete
the ones you disagree with; a principle nobody believes is worse than an
empty file.

**Nothing is overwritten.** Existing files are reported as skipped, so running
this on a project that already has half the record adds only the missing half —
and running it twice is a no-op. A scaffolder that clobbers is a scaffolder
nobody dares re-run, which means the one thing it is good at (filling in what a
project grew past) never gets used. The one hard refusal: `--config` against a
project that already has a `luria.toml` is an error, not a skip — scaffolding
one config's shape while a different config governs the record would build
directories the project's own machinery doesn't know about.
"""

from __future__ import annotations

import re
import os
from pathlib import Path

from .config import CONFIG_NAME, Config, Scheme, find_root, load


def _template_dir() -> Path:
    """The scaffold's location, which depends on how Luria arrived.

    Installed from a wheel, the template ships inside the package
    (`luria/template/`, ADR-027); in a checkout it sits at the repository
    top level, where a visitor browses it (ADR-021). Packaged wins when both
    exist, because an installed Luria should scaffold what it shipped."""
    packaged = Path(__file__).resolve().parent / "template"
    if packaged.is_dir():
        return packaged
    return Path(__file__).resolve().parent.parent / "template"


TEMPLATE = _template_dir()

# The template for a scheme this package has no doctrine about. The
# `{PREFIX}-NNN` placeholder is `luria new`'s contract (ADR-036): the copy
# gets its real code substituted everywhere a reader would see one, and the
# `date:` line is restamped. The frontmatter is the shape the lint demands —
# a canonical status, a title agreeing with the heading, at least one tag.
GENERIC_TEMPLATE = """\
---
# Copy this file to {PREFIX}-NNN.md — or run `luria new {prefix}`, which
# computes the next free number and stamps the date. The filename is the code
# and nothing else; the title lives in `title:`, where correcting it costs an
# edit rather than a rename plus every inbound link (LU-ADR-013).

# Active | Proposed | Deferred | Superseded | Rejected. A qualifying note goes
# in `status_note:` — prose, like `summary:`.
# `luria lint` enforces the vocabulary; which one counts as "in force" for
# this scheme is the `active` key in luria.toml.
status: Proposed

title: Stated as the thing it establishes

version: 1

tags:
- record

date: '2026-01-01'

# Optional, but it is what the index shows in place of the bare title: what
# this document establishes, and what it rejected.
summary: >-
  One-paragraph description for the index row.
---

# {PREFIX}-NNN: Stated as the thing it establishes

## Context

What was true that made this necessary.

## Content

The substance, in the active voice.
"""

# The view stubs a custom scheme starts with. Both are *authored* files — the
# generator fills the placeholders and leaves the prose to the project.
GENERIC_STUB_INDEX = """\
# {PREFIX} documents

One entry per document, generated from frontmatter — edit the fragments in
this directory, then run `luria index`.

<!-- GENERATED below this line by `luria index` — edit README.stub instead. -->

{categories}

{table}
"""

GENERIC_STUB_DOCUMENT = """\
# {PREFIX} documents

<!-- GENERATED by `luria index` — edit the fragments, not this file. -->

{principles}
"""


# ── Inferring the issue URL from the git remote ──────────────────────────
#
# `issue_url` is the one key a conventional project still has to supply, and
# for a repository with an origin remote it is already written down. Deriving
# it also cascades: `[luria.site]` takes its title, its Pages URL and its
# source base from this one value, so a project that never opens luria.toml
# gets four correct settings from having a remote.
#
# Only hosts whose issue path is known. A wrong issue URL is worse than an
# empty one — it renders a link on every decision that carries an issue, and
# each one 404s — so an unrecognised host produces nothing and says so.
ISSUE_PATHS = {
    "github.com": "issues",
    "gitlab.com": "-/issues",
}

# The scheme-bearing forms are tried FIRST: `https` matches a bare hostname
# under the scp-like branch, so the obvious ordering silently reads
# `https://github.com/o/r` as host `https` and path `/github.com/o/r`.
_REMOTE_RE = re.compile(
    r"""^(?:
          https?://(?:[^@/]+@)?(?P<h2>[^/]+)/            # https://host/
        | ssh://(?:[^@/]+@)?(?P<h3>[^/:]+)(?::\d+)?/     # ssh://git@host[:port]/
        | (?:[^@/]+@)(?P<h1>[^/:]+):                     # git@host:
        )
        (?P<path>.+?)(?:\.git)?/?$
    """, re.X)


def _origin_url(into: Path) -> str:
    """The `origin` remote, or "" — for any reason at all.

    Not being in a repository is the ordinary case for `luria init`, and so is
    having no origin yet. Neither is a problem worth a message, let alone a
    failure: the key this feeds is optional."""
    import subprocess
    try:
        done = subprocess.run(
            ["git", "-C", str(into), "remote", "get-url", "origin"],
            capture_output=True, text=True, timeout=5)
    except (OSError, subprocess.SubprocessError):
        return ""
    return done.stdout.strip() if done.returncode == 0 else ""


def infer_issue_url(into: Path) -> str:
    """`https://github.com/owner/repo/issues/{n}` from the origin remote.

    Empty when there is no remote, or when its host is not one whose issue
    path this knows. Guessing at an unknown forge would put a broken link on
    every entry that names an issue, which is a worse default than the empty
    string it replaces."""
    m = _REMOTE_RE.match(_origin_url(into))
    if not m:
        return ""
    host = (m.group("h1") or m.group("h2") or m.group("h3") or "").lower()
    path = m.group("path").strip("/")
    segment = ISSUE_PATHS.get(host)
    if not segment or path.count("/") != 1:
        return ""
    return f"https://{host}/{path}/{segment}/{{n}}"


# ── Shorthand for a scaffold that is mostly the defaults ─────────────────
#
# The conventional scheme table is four lines, three of which follow from the
# prefix: `record/rfcs.d`, `docs/rfcs`, rendered as an index. Typing them is
# the boilerplate a new project meets first, and it is exactly the part with
# no decision in it.
#
#     luria init --schemes "RFC,SPEC:document" --journals "incidents:day"
#
# The shorthand is an ARGUMENT, never a stored format. What lands in
# `luria.toml` is the ordinary explicit table, commented like the rest of the
# template — a config a reader cannot read is a worse trade than the typing it
# saved, and every other part of this package reads that file rather than a
# second grammar. ADR-048 plans the scaffold from configuration; this only
# decides what the configuration says.

RENDERS = ("index", "document")
GRANULARITIES = ("year", "month", "day")


def _slug(prefix: str) -> str:
    """`RFC` → `rfcs`, the directory name a prefix implies.

    Mechanical on purpose. The shipped schemes are named for what they hold
    (`decisions.d`, `principles.d`) rather than for their codes, and a project
    that wants that can edit one line — but guessing at it here would mean
    guessing at what an RFC *is*, which this package has no opinion about."""
    lower = prefix.lower()
    return lower if lower.endswith("s") else lower + "s"


def _spec(item: str, kinds: tuple, default: str, what: str) -> tuple:
    """`NAME` or `NAME:kind`, validated at the point of typing.

    Eagerly, and with the vocabulary in the message: a scaffold is run once,
    usually by somebody meeting these words for the first time, so a silent
    fallback would be discovered much later and by reading generated output.

    `default` is passed rather than taken as the first of `kinds`, which is
    the shape this had until a test caught it defaulting a journal to `year`.
    The listing order is for the error message and the default is a fact about
    the dataclass; tying them together made the second follow the first."""
    name, _, kind = item.partition(":")
    name, kind = name.strip(), (kind.strip() or default)
    if not name:
        raise SystemExit("luria init: empty name in --%ss" % what)
    if kind not in kinds:
        raise SystemExit(
            "luria init: %s %r asks for %r; expected one of %s"
            % (what, name, kind, ", ".join(kinds)))
    return name, kind


def _scheme_table(prefix: str, render: str) -> str:
    slug = _slug(prefix)
    output = "docs/%s.md" % slug if render == "document" else "docs/%s" % slug
    reading = ("read as a whole, so its entries concatenate into one page"
               if render == "document" else
               "browsed one at a time, so its view is an index plus tag pages")
    return (
        "\n# %s — %s.\n"
        "# The paths follow the prefix; rename them if this family is better\n"
        "# called something other than what its codes spell.\n"
        "[luria.schemes.%s]\n"
        'dir    = "record/%s.d"\n'
        'output = "%s"\n'
        'render = "%s"\n' % (prefix, reading, prefix, slug, output, render))


def _journal_table(name: str, granularity: str) -> str:
    title = name.replace("-", " ").replace("_", " ").capitalize()
    return (
        "\n# %s — dated entries that persist and are never revised, collected\n"
        "# into one book per %s.\n"
        "[luria.journals.%s]\n"
        'dir         = "record/%s.d"\n'
        'output      = "docs/%s"\n'
        'granularity = "%s"\n'
        'title       = "%s"\n'
        % (name, granularity, name, name, name, granularity, title))


def shorthand_tables(text: str, schemes: str, journals: str) -> str:
    """The template's config, plus one table per shorthand entry.

    Additive by design. The template already declares ADR and DP, so appending
    a third scheme keeps all three — which is what "mostly the defaults" has to
    mean, given that a declared family replaces the shipped one whole
    (ADR-047). Removing a default is deleting its table, which is an edit to a
    file the user can now see."""
    added = []
    for item in (s for s in schemes.split(",") if s.strip()):
        prefix, render = _spec(item, RENDERS, "index", "scheme")
        prefix = prefix.upper()
        if "[luria.schemes.%s]" % prefix in text:
            raise SystemExit(
                "luria init: the template already declares %s; drop it from "
                "--schemes and edit the table it writes" % prefix)
        added.append(_scheme_table(prefix, render))
    for item in (s for s in journals.split(",") if s.strip()):
        name, granularity = _spec(item, GRANULARITIES, "month", "journal")
        if "[luria.journals.%s]" % name in text:
            raise SystemExit(
                "luria init: the template already declares the %s journal; "
                "drop it from --journals and edit its table" % name)
        added.append(_journal_table(name, granularity))
    if not added:
        return text
    return text.rstrip("\n") + "\n" + "".join(added)


def _read(rel: str) -> str:
    return (TEMPLATE / rel).read_text(encoding="utf-8")


def _toml_text(into: Path, config_arg: str | None, issue_url: str,
               schemes: str = "", journals: str = "") -> str:
    """The config the scaffold is planned from, resolved in priority order."""
    root_cfg = into / CONFIG_NAME
    if config_arg:
        if root_cfg.exists():
            raise SystemExit(
                f"luria init: {CONFIG_NAME} already exists in {into} — "
                "refusing to scaffold from a different config. Merge the two "
                "by hand, then re-run without --config.")
        if schemes or journals:
            raise SystemExit(
                "luria init: --schemes/--journals extend the shipped "
                "template; with --config the shape is already declared, so "
                "add the tables to that file instead.")
        return Path(config_arg).read_text(encoding="utf-8")
    if root_cfg.exists():
        if schemes or journals:
            raise SystemExit(
                f"luria init: {CONFIG_NAME} already exists in {into}, so the "
                "shape is already declared — add the tables to it rather "
                "than passing --schemes/--journals.")
        return root_cfg.read_text(encoding="utf-8")
    return template_config(into, issue_url, schemes, journals)


def template_config(into: Path, issue_url: str = "", schemes: str = "",
                    journals: str = "") -> str:
    """The shipped template's config, with the issue URL filled in and the
    shorthand expanded.

    Shared by `luria init` and `luria config`, which differ only in what they
    do with the result — scaffold from it, or hand it over to be edited."""
    text = _read(CONFIG_NAME)
    # The one key a conventional project still had to supply, and a repository
    # with an origin remote has already written it down somewhere else.
    issue_url = issue_url or infer_issue_url(into)
    if issue_url:
        text = text.replace(
            'issue_url = ""',
            f'issue_url = "{issue_url.rstrip("/")}/{{n}}"'
            if "{n}" not in issue_url else f'issue_url = "{issue_url}"')
    return shorthand_tables(text, schemes, journals)


def _scheme_files(scheme: Scheme) -> dict[Path, str]:
    """What one scheme's directory starts with.

    ADR and a document-rendered DP get the shipped rich content — the
    decision doctrine and the seed principles are what this package has to
    say, and they are prefix-specific on purpose. Everything else gets the
    neutral shapes above, titled after itself."""
    if scheme.prefix == "ADR":
        return {
            scheme.dir / "_template.md": _read("record/decisions.d/_template.md"),
            scheme.stub: _read("record/decisions.d/README.stub"),
            scheme.tags_yaml: _read("record/decisions.d/tags.yaml"),
        }
    if scheme.prefix == "DP" and scheme.render == "document":
        return {scheme.dir / src.name: src.read_text(encoding="utf-8")
                for src in sorted((TEMPLATE / "record/principles.d").glob("*"))
                if src.is_file()}
    stub = (GENERIC_STUB_DOCUMENT if scheme.render == "document"
            else GENERIC_STUB_INDEX)
    subs = {"{PREFIX}": scheme.prefix, "{prefix}": scheme.prefix.lower()}
    template = GENERIC_TEMPLATE
    for key, value in subs.items():
        template = template.replace(key, value)
    return {scheme.dir / "_template.md": template,
            scheme.stub: stub.replace("{PREFIX}", scheme.prefix)}


def _views(cfg: Config) -> str:
    """The docs index's bullet list — one line per view this record renders,
    derived from the config so the list and the record cannot disagree about
    what exists (the docs-index lint would catch it, but a scaffold that
    starts red teaches the wrong first lesson)."""
    rel = lambda p: os.path.relpath(p, cfg.docs)  # noqa: E731
    lines = []
    for s in cfg.schemes.values():
        if s.render == "document":
            target = s.output if s.output else s.view / "README.md"
            if s.prefix == "DP":
                lines.append(f"- [Design principles]({rel(target)}) — standing "
                             "values, numbered.")
            else:
                lines.append(f"- [{s.prefix} documents]({rel(target)}) — the "
                             "set, read as one page.")
        elif s.prefix == "ADR":
            lines.append(f"- [Decisions]({rel(s.index_path)}) — choices, with "
                         "their alternatives.")
        else:
            lines.append(f"- [{s.prefix} index]({rel(s.index_path)}) — one "
                         "entry per document, with status and tags.")
    for j in cfg.journals.values():
        lines.append(f"- [{j.title}]({rel(j.output / 'README.md')}) — the "
                     f"narrative, one book per {j.granularity}.")
    lines.append("- [The record](record.md) — what this project's record is "
                 "made of and where each kind of entry is filed, generated "
                 "from `luria.toml`. Read it before assuming this record can "
                 "only hold decisions: schemes, journals, fragment "
                 "directories and remotes are families *this* project "
                 "names.")
    return "\n".join(lines)


def plan(into: Path, config_arg: str | None = None,
         issue_url: str = "", schemes: str = "",
         journals: str = "") -> list[tuple[Path, str]]:
    """(destination, content) for everything the scaffold would write."""
    if not TEMPLATE.is_dir():                       # installed without data
        return []
    toml_text = _toml_text(into, config_arg, issue_url, schemes, journals)
    cfg = load(into, text=toml_text)

    files: dict[Path, str] = {into / CONFIG_NAME: toml_text}
    for scheme in cfg.schemes.values():
        files.update(_scheme_files(scheme))
    for journal in cfg.journals.values():
        files[journal.dir / "_template.md"] = _read("record/devlog.d/_template.md")
    for name in cfg.fragments:
        files[into / name / "_template.md"] = _read("record/changelog.d/_template.md")
    files[cfg.docs / "README.md"] = _read("docs/README.md").replace(
        "{views}", _views(cfg))
    files[into / "CLAUDE.md"] = _read("CLAUDE.md")
    for wf in sorted((TEMPLATE / ".github").rglob("*")):
        if wf.is_file():
            files[into / wf.relative_to(TEMPLATE)] = wf.read_text(encoding="utf-8")
    return sorted(files.items())


def write(into: Path, issue_url: str = "", dry_run: bool = False,
          config: str | None = None, schemes: str = "",
          journals: str = "") -> tuple[int, int, list[Path]]:
    written = skipped = 0
    kept: list[Path] = []
    for dest, content in plan(into, config, issue_url, schemes, journals):
        if dest.exists():
            print(f"  skip   {dest.relative_to(into)} (exists)")
            skipped += 1
            kept.append(dest)
            continue
        print(f"  write  {dest.relative_to(into)}")
        written += 1
        if dry_run:
            continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, encoding="utf-8")
    return written, skipped, kept



def config_run(into: str = None, issue_url: str = "", schemes: str = "",
               journals: str = "", stdout: bool = False) -> None:
    """Write a starting `luria.toml` from the shorthand, and stop there.

    The same file `luria init` would have written, without the scaffold. It
    exists because the shorthand covers the two things projects usually vary
    and nothing else: a project that also wants a different directory, a
    narrowed status vocabulary or a tag group has to edit the config, and
    doing that *after* a scaffold means moving directories the first run
    already created.

        luria config --schemes "RFC,SPEC:document"   # write it
        $EDITOR luria.toml                           # change what you like
        luria init                                   # scaffold that shape

    Refuses to overwrite, like everything else here. `--stdout` prints instead
    of writing, for a look before committing to one."""
    into = (Path(into) if into else find_root()).resolve()
    text = template_config(into, issue_url, schemes, journals)
    if stdout:
        print(text, end="")
        return
    dest = into / CONFIG_NAME
    if dest.exists():
        raise SystemExit(
            f"luria config: {dest} already exists — this writes a starting "
            f"config, and yours has already started. Add the tables by hand, "
            f"or pass --stdout to see what this would have written.")
    dest.write_text(text, encoding="utf-8")
    print(dest)
    print("\nEdit it, then `luria init` to scaffold the shape it declares.")

def run(into: str = None, issue_url: str = "", dry_run: bool = False,
        config: str = None, schemes: str = "", journals: str = "") -> None:
    """Scaffold the record a config declares (default: the detected root's
    own config, or the shipped template's). Never overwrites; --config PATH
    installs that file as luria.toml and scaffolds its shape; --dry-run lists
    what would be written; --issue-url makes issue numbers linkable.

    --schemes and --journals extend the shipped template for a project that
    wants the defaults plus a little: `--schemes "RFC,SPEC:document"`,
    `--journals "incidents:day"`. Each entry becomes an ordinary commented
    table in the luria.toml this writes, so the shorthand is something you
    type once rather than a format anything reads back."""
    into = (Path(into) if into else find_root()).resolve()
    print(f"luria init → {into}")
    if not issue_url and not config and not (into / CONFIG_NAME).exists():
        if guessed := infer_issue_url(into):
            print(f"  issue_url  {guessed}  (from the origin remote)")
    written, skipped, kept = write(into, issue_url, dry_run, config,
                                   schemes, journals)
    if not written and not skipped:
        print("  nothing to write — is the template directory installed?")
        raise SystemExit(1)
    verb = "would write" if dry_run else "wrote"
    print(f"{verb} {written} file(s), skipped {skipped} existing.")
    # A file the project already owns is never touched — but the one an
    # agent reads first deserves more than a silent skip (DP-1): say what
    # the scaffolded shape would have been, and leave the merge to a human
    # or their agent.
    if any(p.name == "CLAUDE.md" for p in kept):
        print("\nYour CLAUDE.md was left alone. The scaffolded shape is a "
              "short map — links to the record's docs plus an invitation to "
              "run `luria --help` (LU-ADR-037). Worth borrowing: ask your "
              "agent to fold that shape into your existing file.")
    if written and not dry_run:
        print("\nNext: `luria index` to build the generated views, then "
              "`luria lint`.")


if __name__ == "__main__":
    import fire
    fire.Fire(run)
