from __future__ import annotations
import os
from pathlib import Path
from .config import CONFIG_NAME, Config, Scheme, find_root, load

def _template_dir() -> Path:
    packaged = Path(__file__).resolve().parent / 'template'
    if packaged.is_dir():
        return packaged
    return Path(__file__).resolve().parent.parent / 'template'
TEMPLATE = _template_dir()
GENERIC_TEMPLATE = '---\n# Copy this file to {PREFIX}-NNN.md — or run `luria new {prefix}`, which\n# computes the next free number and stamps the date. The filename is the code\n# and nothing else; the title lives in `title:`, where correcting it costs an\n# edit rather than a rename plus every inbound link (LU-ADR-013).\n\n# Active | Proposed | Deferred | Superseded | Rejected, optionally " — note".\n# `luria lint` enforces the vocabulary; which one counts as "in force" for\n# this scheme is the `active` key in luria.toml.\nstatus: Proposed\n\ntitle: Stated as the thing it establishes\n\nversion: 1\n\ntags:\n- record\n\ndate: \'2026-01-01\'\n\n# Optional, but it is what the index shows in place of the bare title: what\n# this document establishes, and what it rejected.\nsummary: >-\n  One-paragraph description for the index row.\n---\n\n# {PREFIX}-NNN: Stated as the thing it establishes\n\n## Context\n\nWhat was true that made this necessary.\n\n## Content\n\nThe substance, in the active voice.\n'
GENERIC_STUB_INDEX = '# {PREFIX} documents\n\nOne entry per document, generated from frontmatter — edit the fragments in\nthis directory, then run `luria index`.\n\n<!-- GENERATED below this line by `luria index` — edit README.stub instead. -->\n\n{categories}\n\n{table}\n'
GENERIC_STUB_DOCUMENT = '# {PREFIX} documents\n\n<!-- GENERATED by `luria index` — edit the fragments, not this file. -->\n\n{principles}\n'

def _read(rel: str) -> str:
    return (TEMPLATE / rel).read_text()

def _toml_text(into: Path, config_arg: str | None, issue_url: str) -> str:
    root_cfg = into / CONFIG_NAME
    if config_arg:
        if root_cfg.exists():
            raise SystemExit(f'luria init: {CONFIG_NAME} already exists in {into} — refusing to scaffold from a different config. Merge the two by hand, then re-run without --config.')
        return Path(config_arg).read_text()
    if root_cfg.exists():
        return root_cfg.read_text()
    text = _read(CONFIG_NAME)
    if issue_url:
        text = text.replace('issue_url = ""', f'''issue_url = "{issue_url.rstrip('/')}/{{n}}"''' if '{n}' not in issue_url else f'issue_url = "{issue_url}"')
    return text

def _scheme_files(scheme: Scheme) -> dict[Path, str]:
    if scheme.prefix == 'ADR':
        return {scheme.dir / '_template.md': _read('record/decisions.d/_template.md'), scheme.stub: _read('record/decisions.d/README.stub'), scheme.tags_yaml: _read('record/decisions.d/tags.yaml')}
    if scheme.prefix == 'DP' and scheme.render == 'document':
        return {scheme.dir / src.name: src.read_text() for src in sorted((TEMPLATE / 'record/principles.d').glob('*')) if src.is_file()}
    stub = GENERIC_STUB_DOCUMENT if scheme.render == 'document' else GENERIC_STUB_INDEX
    subs = {'{PREFIX}': scheme.prefix, '{prefix}': scheme.prefix.lower()}
    template = GENERIC_TEMPLATE
    for key, value in subs.items():
        template = template.replace(key, value)
    return {scheme.dir / '_template.md': template, scheme.stub: stub.replace('{PREFIX}', scheme.prefix)}

def _views(cfg: Config) -> str:
    rel = lambda p: os.path.relpath(p, cfg.docs)
    lines = []
    for s in cfg.schemes.values():
        if s.render == 'document':
            target = s.output if s.output else s.view / 'README.md'
            if s.prefix == 'DP':
                lines.append(f'- [Design principles]({rel(target)}) — standing values, numbered.')
            else:
                lines.append(f'- [{s.prefix} documents]({rel(target)}) — the set, read as one page.')
        elif s.prefix == 'ADR':
            lines.append(f'- [Decisions]({rel(s.index_path)}) — choices, with their alternatives.')
        else:
            lines.append(f'- [{s.prefix} index]({rel(s.index_path)}) — one entry per document, with status and tags.')
    for j in cfg.journals.values():
        lines.append(f"- [{j.title}]({rel(j.output / 'README.md')}) — the narrative, one book per {j.granularity}.")
    lines.append("- [The record](record.md) — what this project's record is made of and where each kind of entry is filed, generated from `luria.toml`. Read it before assuming this record can only hold decisions: schemes, journals, fragment directories and remotes are families *this* project names.")
    return '\n'.join(lines)

def plan(into: Path, config_arg: str | None=None, issue_url: str='') -> list[tuple[Path, str]]:
    if not TEMPLATE.is_dir():
        return []
    toml_text = _toml_text(into, config_arg, issue_url)
    cfg = load(into, text=toml_text)
    files: dict[Path, str] = {into / CONFIG_NAME: toml_text}
    for scheme in cfg.schemes.values():
        files.update(_scheme_files(scheme))
    for journal in cfg.journals.values():
        files[journal.dir / '_template.md'] = _read('record/devlog.d/_template.md')
    for name in cfg.fragments:
        files[into / name / '_template.md'] = _read('record/changelog.d/_template.md')
    files[cfg.docs / 'README.md'] = _read('docs/README.md').replace('{views}', _views(cfg))
    files[into / 'CLAUDE.md'] = _read('CLAUDE.md')
    for wf in sorted((TEMPLATE / '.github').rglob('*')):
        if wf.is_file():
            files[into / wf.relative_to(TEMPLATE)] = wf.read_text()
    return sorted(files.items())

def write(into: Path, issue_url: str='', dry_run: bool=False, config: str | None=None) -> tuple[int, int, list[Path]]:
    written = skipped = 0
    kept: list[Path] = []
    for dest, content in plan(into, config, issue_url):
        if dest.exists():
            print(f'  skip   {dest.relative_to(into)} (exists)')
            skipped += 1
            kept.append(dest)
            continue
        print(f'  write  {dest.relative_to(into)}')
        written += 1
        if dry_run:
            continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content)
    return (written, skipped, kept)

def run(into: str=None, issue_url: str='', dry_run: bool=False, config: str=None) -> None:
    into = (Path(into) if into else find_root()).resolve()
    print(f'luria init → {into}')
    written, skipped, kept = write(into, issue_url, dry_run, config)
    if not written and (not skipped):
        print('  nothing to write — is the template directory installed?')
        raise SystemExit(1)
    verb = 'would write' if dry_run else 'wrote'
    print(f'{verb} {written} file(s), skipped {skipped} existing.')
    if any((p.name == 'CLAUDE.md' for p in kept)):
        print("\nYour CLAUDE.md was left alone. The scaffolded shape is a short map — links to the record's docs plus an invitation to run `luria --help` (LU-ADR-037). Worth borrowing: ask your agent to fold that shape into your existing file.")
    if written and (not dry_run):
        print('\nNext: `luria index` to build the generated views, then `luria lint`.')
if __name__ == '__main__':
    import fire
    fire.Fire(run)
