from __future__ import annotations
import datetime as dt
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from .adr_index import parse_frontmatter
from .config import Journal, current
PATH_RE = re.compile('(\\d{4})/(\\d{2})/(\\d{2})/(\\d{2})(\\d{2})(\\d{2})\\.md$')
SLUG_RE = re.compile('[^a-z0-9]+')

def parse_created(raw) -> dt.datetime | None:
    if isinstance(raw, dt.datetime):
        return raw
    if isinstance(raw, dt.date):
        return dt.datetime(raw.year, raw.month, raw.day)
    try:
        return dt.datetime.fromisoformat(str(raw))
    except (TypeError, ValueError):
        return None

def path_for(journal: Journal, created: dt.datetime) -> Path:
    return journal.dir / created.strftime('%Y/%m/%d/%H%M%S.md')

def created_from_path(path: Path) -> dt.datetime | None:
    m = PATH_RE.search(path.as_posix())
    return dt.datetime(*(int(g) for g in m.groups())) if m else None

@dataclass(frozen=True)
class Entry:
    created: dt.datetime
    title: str
    tags: tuple[str, ...]
    body: str
    path: Path

    @property
    def anchor(self) -> str:
        return self.created.strftime('%Y%m%d%H%M%S')

def read(path: Path) -> Entry | None:
    meta, body = parse_frontmatter(path.read_text())
    created = parse_created(meta.get('created')) or created_from_path(path)
    if created is None:
        return None
    return Entry(created, str(meta.get('title') or '').strip(), tuple((str(t).strip() for t in meta.get('tags') or [])), body.strip(), path)

def entries(journal: Journal) -> list[Entry]:
    found = [e for p in sorted(journal.dir.rglob('*.md')) if p.name != '_template.md' and (e := read(p)) is not None]
    return sorted(found, key=lambda e: (e.created, e.path.as_posix()))
_CREATED_LINE_RE = re.compile('^created:.*$', re.MULTILINE)

def populate_created(journal: Journal) -> list[Path]:
    fixed: list[Path] = []
    for path in sorted(journal.dir.rglob('*.md')):
        if path.name == '_template.md':
            continue
        text = path.read_text()
        meta, _ = parse_frontmatter(text)
        if parse_created(meta.get('created')) is not None:
            continue
        created = created_from_path(path)
        if created is None:
            continue
        line = f"created: '{created.isoformat(timespec='seconds')}'"
        if meta and 'created' in meta:
            new_text = _CREATED_LINE_RE.sub(line, text, count=1)
        elif text.startswith('---\n'):
            head, rest = text.split('\n', 1)
            new_text = f'{head}\n{line}\n{rest}'
        else:
            new_text = f'---\n{line}\n---\n\n{text}'
        path.write_text(new_text)
        fixed.append(path)
    return fixed
FORMATS = {'year': '%Y', 'month': '%Y-%m', 'day': '%Y-%m-%d'}
LABELS = {'year': '%Y', 'month': '%B %Y', 'day': '%-d %B %Y'}

def book_key(journal: Journal, created: dt.datetime) -> str:
    return created.strftime(FORMATS[journal.granularity])

def books(journal: Journal) -> dict[str, list[Entry]]:
    out: dict[str, list[Entry]] = {}
    for entry in entries(journal):
        out.setdefault(book_key(journal, entry.created), []).append(entry)
    return out

def render_book(journal: Journal, key: str, filed: list[Entry]) -> str:
    label = filed[0].created.strftime(LABELS[journal.granularity]).lstrip('0')
    lines = [f'<!-- GENERATED by `luria index` from {journal.rel_dir}/ — edit the entries, not this file. -->', '', f'# {journal.title} — {label}', '', f"{len(filed)} entr{('y' if len(filed) == 1 else 'ies')}. [All books](README.md).", '', '## Contents', '']
    for entry in filed:
        stamp = entry.created.strftime('%d %b %H:%M').lstrip('0')
        lines.append(f'- [{stamp} — {entry.title}](#{entry.anchor})')
    lines.append('')
    for entry in filed:
        lines += ['---', '', f'<a name="{entry.anchor}"></a>', '', f'## {entry.title}', '', f"*{entry.created.strftime('%Y-%m-%d %H:%M:%S')}" + (' · ' + ' · '.join(entry.tags) if entry.tags else '') + '*', '', entry.body, '']
    return '\n'.join(lines)

def render_index(journal: Journal, grouped: dict[str, list[Entry]]) -> str:
    lines = [f'<!-- GENERATED by `luria index` from {journal.rel_dir}/ — edit the entries, not this file. -->', '', f'# {journal.title}', '']
    if journal.blurb:
        lines += [journal.blurb, '']
    if not grouped:
        lines += ['Nothing filed yet.', '']
        return '\n'.join(lines)
    latest = max(grouped)
    label = grouped[latest][0].created.strftime(LABELS[journal.granularity]).lstrip('0')
    lines += [f'## Currently — [{label}]({latest}.md)', '']
    for entry in reversed(grouped[latest]):
        stamp = entry.created.strftime('%d %b %H:%M').lstrip('0')
        lines.append(f'- [{stamp} — {entry.title}]({latest}.md#{entry.anchor})')
    lines.append('')
    total = sum((len(v) for v in grouped.values()))
    lines += [f'## All books', '', f"{total} entr{('y' if total == 1 else 'ies')} across {len(grouped)} book{('' if len(grouped) == 1 else 's')}, newest first.", '', '| Book | Entries | First | Last |', '|---|--:|---|---|']
    for key in sorted(grouped, reverse=True):
        filed = grouped[key]
        lines.append(f'| [{key}]({key}.md) | {len(filed)} | {filed[0].created:%Y-%m-%d} | {filed[-1].created:%Y-%m-%d} |')
    lines.append('')
    return '\n'.join(lines)

def outputs_for(journal: Journal) -> dict[Path, str]:
    if not journal.dir.exists():
        return {}
    grouped = books(journal)
    out = {journal.output / 'README.md': render_index(journal, grouped)}
    for key, filed in grouped.items():
        out[journal.output / f'{key}.md'] = render_book(journal, key, filed)
    return out

def outputs() -> dict[Path, str]:
    out: dict[Path, str] = {}
    for journal in current().journals.values():
        out.update(outputs_for(journal))
    return out

def new(journal: Journal, title: str, now: dt.datetime) -> Path:
    while (path := path_for(journal, now)).exists():
        now += dt.timedelta(seconds=1)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(f"---\ntitle: {title!r}\ncreated: '{now.isoformat(timespec='seconds')}'\ntags: []\n---\n\nWrite the entry here: what problem was solved, what the fix was, and\nwhat was found along the way — the failed approaches and the traps the\nnext person would otherwise rediscover.\n")
    return path

def run(journal: str=None) -> None:
    cfg = current()
    if not cfg.journals:
        print('luria journal: none configured. Add one to luria.toml:\n\n  [luria.journals.devlog]\n  dir = "devlog.d"\n  output = "docs/devlog"\n', file=sys.stderr)
        return
    name = journal or next(iter(cfg.journals))
    if name not in cfg.journals:
        print(f"luria journal: unknown journal {name!r}; configured: {', '.join(cfg.journals)}", file=sys.stderr)
        raise SystemExit(2)
    journal_cfg = cfg.journals[name]
    grouped = books(journal_cfg)
    total = sum((len(v) for v in grouped.values()))
    period = {'year': 'yearly', 'month': 'monthly', 'day': 'daily'}[journal_cfg.granularity]
    print(f"{name}: {total} entr{('y' if total == 1 else 'ies')} in {len(grouped)} {period} book{('' if len(grouped) == 1 else 's')} → {cfg.rel(journal_cfg.output)}/")
    for key in sorted(grouped, reverse=True):
        filed = grouped[key]
        print(f"  {key}.md  {len(filed):>3} entr{('y' if len(filed) == 1 else 'ies')}")
if __name__ == '__main__':
    import fire
    fire.Fire(run)
