from __future__ import annotations
from pathlib import Path
from . import config as config_mod
from .adr_index import escape_cell
from .config import current
SCHEMA_URL = 'https://github.com/dmarx/luria/blob/main/docs/configuration.md'
STAMP = "*Generated by `luria index` from this project's `luria.toml` — built, not edited. A table configured is a row here whether or not anyone remembered to describe it.*\n"
HEADER = "# The record\n\n<!-- GENERATED by `luria index` — edit `luria.toml`, not this file. -->\n\n{stamp}\nThis is the shape *this* project gave the record machinery: the document\nfamilies it named, where entries are filed, where views are rendered, and what\nto type to add one. It is a description of `luria.toml` as configured, not of\nwhat `luria.toml` can hold — for the key-by-key schema, with defaults and\nmeanings, see [Luria's configuration reference]({schema}).\n"
NOTHING = '*None configured.*\n'

def _rel(cfg, path: Path | None, dir: bool=False) -> str:
    if path is None:
        return '—'
    try:
        text = str(Path(path).relative_to(cfg.root))
    except ValueError:
        text = str(path)
    return f'`{text}/`' if dir else f'`{text}`'

def _table(header: list[str], rows: list[list[str]]) -> str:
    if not rows:
        return NOTHING
    out = ['| ' + ' | '.join(header) + ' |', '|' + '|'.join(('---' for _ in header)) + '|']
    out += ['| ' + ' | '.join((escape_cell(c) for c in r)) + ' |' for r in rows]
    return '\n'.join(out) + '\n'

def schemes_section(cfg) -> str:
    rows = []
    for prefix, s in cfg.schemes.items():
        if s.render == 'document':
            view = f'{_rel(cfg, s.output)} (one page, read as a whole)'
        else:
            view = f'{_rel(cfg, s.index_path)} + tag pages'
        rows.append([f'`{prefix}-001`', _rel(cfg, s.dir, dir=True), view, f'`{s.active}`'])
    return _table(['a code looks like', 'filed in', 'rendered to', 'in force when status is'], rows)

def journals_section(cfg) -> str:
    rows = [[f'`{j.name}`', f'{_rel(cfg, j.dir, dir=True)} `yyyy/mm/dd/hhmmss.md`', _rel(cfg, j.output, dir=True), j.granularity, j.title] for j in cfg.journals.values()]
    return _table(['journal', 'entries filed at', 'books rendered to', 'one book per', 'titled'], rows)

def fragments_section(cfg) -> str:
    rows = [[_rel(cfg, cfg.root / d, dir=True), _rel(cfg, cfg.root / f.target), f.style] for d, f in cfg.fragments.items()]
    return _table(['directory', 'assembled into', 'style'], rows)

def remotes_section(cfg) -> str:
    rows = []
    for prefix, r in cfg.remotes.items():
        example = next(iter(r.schemes), 'ADR')
        rows.append([f'`{prefix}-{example}-001`', r.name or r.repo or '—', r.repo or '—', r.ref or '—'])
    return _table(['cited as', 'project', 'repository', 'ref'], rows)

def filing_section(cfg) -> str:
    from .new import default_kind, kinds
    default = default_kind()
    rows = []
    for kind, (sort, target) in sorted(kinds().items()):
        if sort == 'scheme':
            what = f'a document in the `{target.prefix}` scheme, numbered for you'
        elif sort == 'journal':
            what = f'a dated entry in the `{target.name}` journal'
        elif sort == 'fragment':
            what = f'a fragment in `{target}/`'
        else:
            what = 'a migration spec'
        cmd = f'`luria new --kind {kind} --title "…"`'
        if kind == default:
            cmd += ' — or just `luria new --title "…"`, the default kind'
        rows.append([cmd, what])
    return _table(['command', 'files'], rows)

def _flatten(prefix: str, value, depth: int) -> list[tuple[str, object]]:
    if isinstance(value, dict) and depth > 0:
        out: list[tuple[str, object]] = []
        for k, v in value.items():
            out += _flatten(f'{prefix}.{k}' if prefix else k, v, depth - 1)
        return out
    return [(prefix, value)]

def _value(v) -> str:
    if isinstance(v, dict):
        return f"*{len(v)} key{('s' if len(v) != 1 else '')} set*" if v else '*empty*'
    if isinstance(v, (list, tuple)):
        return ', '.join((f'`{x}`' for x in v)) if v else '*empty*'
    if v == '':
        return '*empty*'
    return f'`{v}`'
FAMILIES = ('schemes', 'fragments', 'journals', 'remotes')

def settings_section(cfg) -> str:
    sentinel = object()
    defaults = dict(_flatten('', config_mod.DEFAULTS, 2))
    rows = []
    for key, value in _flatten('', cfg._raw, 2):
        if key.split('.')[0] in FAMILIES:
            continue
        was = defaults.get(key, sentinel)
        if value == was:
            continue
        rows.append([f'`{key}`', _value(value), '*unset*' if was is sentinel else _value(was)])
    if not rows:
        return f"*Every setting is at its default — the record's shape is entirely in the families above. See the [schema]({SCHEMA_URL}) for what else can be set.*\n"
    return _table(['key', 'this project', "Luria's default"], rows)
SECTIONS = (('Referable documents', 'A code — `ADR-012` — resolves to a document, and every reference to it in this repository is checked. `luria lint` fails on a bare code that was never linked; `luria link --fix` writes the link so nobody has to know where the document renders.', schemes_section), ('Journals', 'Dated observations. An entry is true about the day it was written and is never revised or consumed — the books are a view over sources that stay, which is what makes a journal safe to write into without coordinating.', journals_section), ('Fragment directories', 'One file per contribution, assembled into a single document and then consumed. The point is the absence of a shared file to conflict on: every contributor writes a new path.', fragments_section), ('Other projects this record cites', "A prefixed code reaches into another project's record, so a citation says whose decision it is at the point of use rather than leaving the reader to guess.", remotes_section), ('Filing something new', 'Every kind this project scaffolds, straight from the dispatch table `luria new` itself uses.', filing_section), ('Settings this project changed', "Everything not listed here is at Luria's default.", settings_section))

def render() -> str:
    cfg = current()
    parts = [HEADER.format(stamp=STAMP, schema=SCHEMA_URL)]
    for title, blurb, section in SECTIONS:
        parts.append(f'\n## {title}\n\n{blurb}\n\n')
        parts.append(section(cfg))
    return ''.join(parts)

def outputs(out_dir: Path | None=None) -> dict[Path, str]:
    cfg = current()
    path = cfg.record_doc if out_dir is None else out_dir / 'record.md'
    return {path: render()}

def write(out_dir: Path | None=None) -> list[Path]:
    rendered = outputs(out_dir)
    for path, text in rendered.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
    return sorted(rendered)
if __name__ == '__main__':
    import fire
    fire.Fire(write)
