from __future__ import annotations
import json
import re
import sys
import urllib.error
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from .config import Remote, current
DEFAULT_TAIL = '[A-Z]{2,10}-\\d{1,4}'

def tail_re(remote: Remote) -> str:
    return remote.uid or DEFAULT_TAIL

def remote_pattern(remote: Remote) -> re.Pattern:
    end = '' if remote.uid else '\\b'
    return re.compile(f'\\b{re.escape(remote.prefix)}{re.escape(remote.delim)}(?P<code>{tail_re(remote)}){end}')

@dataclass(frozen=True)
class RemoteRef:
    remote: Remote
    tail: str
    start: int
    end: int
    text: str

    @property
    def prefix(self) -> str:
        return self.remote.prefix

    @property
    def composed(self) -> str:
        return f'{self.prefix}{self.remote.delim}{self.tail}'

def references(text: str) -> list[RemoteRef]:
    found: list[RemoteRef] = []
    for remote in sorted(current().remotes.values(), key=lambda r: len(r.prefix), reverse=True):
        for m in remote_pattern(remote).finditer(text):
            if any((r.start < m.end() and m.start() < r.end for r in found)):
                continue
            found.append(RemoteRef(remote, remote.canon(m.group('code')), m.start(), m.end(), m.group(0)))
    return sorted(found, key=lambda r: r.start)

def parse_code(text: str) -> tuple[Remote, str] | None:
    for remote in sorted(current().remotes.values(), key=lambda r: len(r.prefix), reverse=True):
        m = re.fullmatch(f'{re.escape(remote.prefix)}{re.escape(remote.delim)}({tail_re(remote)})', text)
        if m:
            return (remote, remote.canon(m.group(1)))
    return None

def normalise(code: str) -> str:
    prefix, number = code.rsplit('-', 1)
    return f'{prefix.upper()}-{int(number):03d}'

def lock() -> dict[str, dict[str, str]]:
    path = current().remotes_lock
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text()).get('remotes', {})
    except (OSError, ValueError):
        return {}

def write_lock(found: dict[str, dict[str, str]]) -> Path:
    path = current().remotes_lock
    path.write_text(json.dumps({'_comment': 'Generated by `luria remotes --refresh`. Committed so CI and offline checkouts resolve foreign references the same way (ADR-016).', 'remotes': {k: dict(sorted(v.items())) for k, v in sorted(found.items())}}, indent=2) + '\n')
    return path

def link(remote: Remote, code: str) -> str:
    code = remote.canon(code)
    if remote.uid:
        return remote.link(code)
    scheme = remote.scheme_for(code)
    if scheme is not None and (scheme.url or scheme.document):
        return remote.link(code)
    if remote.url:
        return remote.link(code)
    known = lock().get(remote.prefix)
    if known is not None:
        return remote.link(code, known[code]) if code in known else ''
    return remote.link(code)

def resolve(remote_prefix: str, code: str) -> str:
    remote = current().remotes.get(remote_prefix.upper())
    return link(remote, code) if remote else ''
URL_OK = 'url-ok'

def hand_links(files: list[Path] | None=None) -> tuple[list[str], list[str]]:
    from . import directives, doc_refs, ref_status
    if not current().remotes:
        return ([], [])
    link_re = re.compile('\\[([^\\]\\s]+)\\]\\(([^)\\s]+)\\)')
    cfg = current()
    flagged: list[str] = []
    stale: list[str] = []
    for path in files if files is not None else ref_status.scanned_files():
        try:
            text = path.read_text()
        except (OSError, UnicodeDecodeError):
            continue
        quoted = doc_refs.code_spans(text) if path.suffix == '.md' else []
        found = directives.find(path, text, {URL_OK})
        used: set[tuple[int, str]] = set()
        for m in link_re.finditer(text):
            if any((a <= m.start() < b for a, b in quoted)):
                continue
            parsed = parse_code(m.group(1))
            if parsed is None:
                continue
            remote, tail = parsed
            code = f'{remote.prefix}{remote.delim}{tail}'
            target = m.group(2)
            constructed = link(remote, tail)
            if target == constructed:
                continue
            line = text.count('\n', 0, m.start()) + 1
            ack = next((d for d in found if d.covers(line) and any((_same_code(a, code) for a in d.args))), None)
            if ack is not None:
                for a in ack.args:
                    if _same_code(a, code):
                        used.add((ack.line, a))
                continue
            flagged.append(f"{cfg.rel(path)}:{line}: {code} links to a hand-written URL (construction would say: {constructed or 'nothing — not in the lockfile'})")
        for d in found:
            problem = directives.problems(d)
            for arg in d.args:
                if problem or (d.line, arg) not in used:
                    stale.append(f'{cfg.rel(path)}:{d.line}: `url-ok` names {arg}, which acknowledges no hand-written link here')
    return (flagged, stale)

def _same_code(arg: str, code: str) -> bool:
    a, b = (parse_code(arg), parse_code(code))
    return a is not None and b is not None and ((a[0].prefix, a[1]) == (b[0].prefix, b[1]))
FILENAME_RE = re.compile('^([A-Za-z]{2,10})-0*(\\d{1,4})(?:-[^/]*)?\\.md$')

def _from_names(names: list[str]) -> dict[str, str]:
    out: dict[str, str] = {}
    for name in sorted(names):
        m = FILENAME_RE.match(name)
        if m:
            out.setdefault(normalise(f'{m.group(1)}-{m.group(2)}'), name)
    return out

def _upstream_dir(text: str, fallback: str) -> str:
    try:
        import tomllib
        raw = tomllib.loads(text)
    except ValueError:
        return fallback
    luria = raw.get('luria', raw)
    schemes = luria.get('schemes') or {}
    for spec in schemes.values():
        if isinstance(spec, dict) and spec.get('dir'):
            return spec['dir']
    return (luria.get('paths') or {}).get('decisions', fallback)

def _fetch(url: str) -> tuple[str, str]:
    try:
        with urllib.request.urlopen(url, timeout=15) as response:
            return (response.read().decode(), '')
    except urllib.error.HTTPError as exc:
        return ('', 'not readable anonymously' if exc.code in (401, 403, 404) else f'HTTP {exc.code}')
    except (urllib.error.URLError, OSError, UnicodeDecodeError) as exc:
        return ('', f'unreachable ({exc.__class__.__name__})')

def discover(remote: Remote) -> tuple[dict[str, str], str]:
    if not remote.repo:
        return ({}, 'no `repo` configured')
    raw = f'https://raw.githubusercontent.com/{remote.repo}/{remote.ref}'
    config, _ = _fetch(f'{raw}/luria.toml')
    directory = _upstream_dir(config, remote.dir) if config else remote.dir
    body, why = _fetch(f'https://api.github.com/repos/{remote.repo}/contents/{directory}?ref={remote.ref}')
    if why:
        return ({}, f'GitHub API: {why}')
    try:
        entries = json.loads(body)
    except ValueError:
        return ({}, "GitHub API returned something that isn't JSON")
    how = f'GitHub API, {directory}/' + (' (from its luria.toml)' if config else '')
    return (_from_names([e['name'] for e in entries if e.get('type') == 'file']), how)

@dataclass(frozen=True)
class Probe:
    remote: str
    code: str
    url: str
    status: str

    @property
    def ok(self) -> bool:
        return self.status == 'ok'

def cited() -> dict[str, set[str]]:
    from . import ref_status
    found: dict[str, set[str]] = {}
    if not current().remotes:
        return found
    for path in ref_status.scanned_files():
        try:
            text = path.read_text()
        except (OSError, UnicodeDecodeError):
            continue
        for ref in references(text):
            found.setdefault(ref.prefix, set()).add(ref.tail)
    return found

def _head(url: str) -> tuple[bool, str]:
    try:
        with urllib.request.urlopen(urllib.request.Request(url, method='HEAD'), timeout=15) as r:
            return (True, '') if r.status == 200 else (False, str(r.status))
    except urllib.error.HTTPError as exc:
        return (False, str(exc.code))
    except (urllib.error.URLError, OSError) as exc:
        return (False, exc.__class__.__name__)

def readable(remote: Remote) -> tuple[bool, str]:
    if remote.uid and remote.url:
        return (True, '')
    if not remote.repo:
        return (False, 'no `repo` configured')
    ok, why = _head(f'https://github.com/{remote.repo}')
    if ok:
        return (True, '')
    return (False, 'private or missing — every document will 404 anonymously' if why in ('403', '404') else why)

def probe(remote: Remote, code: str, visible: bool=True) -> Probe:
    url = link(remote, code)
    if not url:
        return Probe(remote.prefix, code, '', 'absent from the remote')
    if not visible:
        return Probe(remote.prefix, code, url, 'unverifiable: repo not public')
    ok, why = _head(url)
    return Probe(remote.prefix, code, url, 'ok' if ok else '404' if why in ('403', '404') else f'unchecked: {why}')

def run(refresh: bool=False, check: bool=False) -> None:
    cfg = current()
    if not cfg.remotes:
        print('luria remotes: none configured. Add one to luria.toml:\n\n  [luria.remotes.LU]\n  repo = "owner/name"\n\nthen cite it as `LU-ADR-013`.', file=sys.stderr)
        return
    if refresh:
        found: dict[str, dict[str, str]] = {}
        for remote in cfg.remotes.values():
            if remote.uid:
                print(f'{remote.prefix} ({remote.label}): a uid remote — nothing to discover')
                continue
            entries, how = discover(remote)
            found[remote.prefix] = entries
            print(f'{remote.prefix} ({remote.label}): {len(entries)} document(s) via {how}')
        path = write_lock(found)
        print(f'wrote {cfg.rel(path)}')
    references = cited()
    locked = lock()
    for remote in cfg.remotes.values():
        codes = sorted(references.get(remote.prefix, ()))
        known = locked.get(remote.prefix, {})
        rung = 'a url template over the uid' if remote.uid else 'an explicit url template' if remote.url else f'{len(known)} discovered filename(s)' if known else 'the code-only filename convention'
        print(f'\n{remote.prefix} → {remote.label}: {len(codes)} reference(s), resolved by {rung}')
        for code in codes:
            target = link(remote, code)
            scheme = remote.scheme_for(code)
            if remote.uid:
                note = ''
            elif scheme is not None and (scheme.url or scheme.document):
                note = "  (by the scheme's url template)" if scheme.url else '  (a document anchor, per the scheme)'
            elif code in known or remote.url:
                note = ''
            else:
                note = '  (by the code-only convention)'
            print(f"  {code}  {target or 'NO SUCH DOCUMENT'}{(note if target else '')}")
    if check:
        broken, unverifiable, absent = ([], [], [])
        for remote in cfg.remotes.values():
            codes = sorted(references.get(remote.prefix, ()))
            if not codes:
                continue
            visible, why = readable(remote)
            print(f'\nchecking {remote.prefix} ({remote.label})' + ('' if visible else f' — {why}'))
            from .parallel import pmap
            for result in pmap(lambda c: probe(remote, c, visible), codes):
                if result.ok:
                    continue
                bucket = unverifiable if result.status.startswith('unverifiable') else absent if result.status == 'absent from the remote' else broken
                bucket.append(result)
                print(f'  {result.remote}-{result.code}: {result.status}' + (f' — {result.url}' if result.url else ''))
        print()
        if unverifiable:
            backed = sum((1 for p in unverifiable if p.code in lock().get(p.remote, {})))
            evidence = f'{backed} of them rest on a discovered filename; the rest on the code-only convention alone' if backed else 'their URLs rest on the code-only convention alone, which is a prediction about the remote, not a fact about it'
            print(f'remotes: {len(unverifiable)} could not be checked — the repository is not readable anonymously, so {evidence}')
        if absent:
            print(f'remotes: {len(absent)} name no document in their remote (see `luria reports`)')
        print(f'remotes: {len(broken)} reference(s) did not answer 200' if broken else 'remotes: nothing verifiable is broken', file=sys.stderr if broken else sys.stdout)
if __name__ == '__main__':
    import fire
    fire.Fire(run)
