#!/usr/bin/env python3
"""Foreign references: `LU-ADR-013` is that remote's decision number 13.

    luria remotes              # what is configured, and how each resolves
    luria remotes --refresh    # discover code→filename maps, write the lockfile
    luria remotes --check      # HEAD every construction; report what 404s

A project that cites another project's record constantly cannot use an
unprefixed code, because it would mean both "our thirteenth decision" and
"theirs". The prefix makes the namespace explicit at the point of use, and one
config entry teaches Luria how to turn it into a URL (ADR-016):

    [luria.remotes.LU]
    repo = "dmarx/luria"

From there `LU-ADR-013` is a first-class reference — `luria link --fix` writes
the link, and `luria lint` demands it, exactly as it does for a local code.

Constructing the URL
--------------------
Three rungs, strongest first. An explicit `url` template wins. Otherwise a
**discovered filename** from the lockfile, which is the only thing that can
resolve a remote whose files carry title slugs (`adr-013-a-long-title.md`).
Otherwise the code-only convention (ADR-013), which needs no lockfile at all
and is the default because it is Luria's own.

**Discovery reads a public repository over HTTPS**, and reads that repository's
own `luria.toml` when it has one, so `dir` comes from the authority rather than
from a guess. A remote Luria cannot read is told so and left on rung three or
one — the fix is a `url` template, not a workaround.

Why a lockfile
--------------
CI, an offline checkout and a laptop with a network connection have to resolve
the same reference the same way, and a check that reaches the network is a
check that fails on a train. Discovery is an explicit command whose output is
committed; nothing else in Luria opens a socket.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.error
import urllib.request
from dataclasses import dataclass
from pathlib import Path

from .config import Remote, current

# `LU-ADR-013`: a remote prefix, then a code in that remote's own namespace.
# Built from config, because an unconfigured prefix must NOT match — otherwise
# a hyphenated word before a code would be read as a namespace.
CODE_TAIL = r"(?P<code>[A-Z]{2,10}-\d{1,4})\b"


def pattern() -> re.Pattern | None:
    prefixes = sorted(current().remotes, key=len, reverse=True)
    if not prefixes:
        return None
    return re.compile(rf"\b(?P<remote>{'|'.join(prefixes)})-{CODE_TAIL}")


def normalise(code: str) -> str:
    """A code with and without leading zeros is one document — one lock key."""
    prefix, number = code.rsplit("-", 1)
    return f"{prefix.upper()}-{int(number):03d}"


# ── The lockfile ─────────────────────────────────────────────────────────


def lock() -> dict[str, dict[str, str]]:
    path = current().remotes_lock
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text()).get("remotes", {})
    except (OSError, ValueError):
        return {}


def write_lock(found: dict[str, dict[str, str]]) -> Path:
    path = current().remotes_lock
    path.write_text(json.dumps(
        {"_comment": "Generated by `luria remotes --refresh`. Committed so "
                     "CI and offline checkouts resolve foreign references the "
                     "same way (ADR-016).",
         "remotes": {k: dict(sorted(v.items())) for k, v in sorted(found.items())}},
        indent=2) + "\n")
    return path


def link(remote: Remote, code: str) -> str:
    """The URL for one foreign code, using the strongest rung available.

    **Discovery, once done, is authoritative.** If this remote has a lockfile
    entry and the code isn't in it, the answer is "" rather than a guessed
    filename — the map was read from the remote itself, so a code missing from
    it names no document there. Guessing anyway once produced a confident link
    to a file that has never existed (ADR-016)."""
    code = normalise(code)
    if remote.url:
        return remote.link(code)
    known = lock().get(remote.prefix)
    if known is not None:
        return remote.link(code, known[code]) if code in known else ""
    return remote.link(code)


def resolve(remote_prefix: str, code: str) -> str:
    remote = current().remotes.get(remote_prefix.upper())
    return link(remote, code) if remote else ""


# ── Discovery ────────────────────────────────────────────────────────────

FILENAME_RE = re.compile(r"^([A-Za-z]{2,10})-0*(\d{1,4})(?:-[^/]*)?\.md$")


def _from_names(names: list[str]) -> dict[str, str]:
    """Filenames → {code: filename}. The same permissive rule
    `Scheme.number_of` uses, so a remote on either naming convention reads."""
    out: dict[str, str] = {}
    for name in sorted(names):
        m = FILENAME_RE.match(name)
        if m:
            out.setdefault(normalise(f"{m.group(1)}-{m.group(2)}"), name)
    return out


def _upstream_dir(text: str, fallback: str) -> str:
    """The remote's own `luria.toml` is the authority on where its documents
    live. Reading it rather than guessing is the whole point of a config file
    existing — and when there isn't one, the configured value stands."""
    try:
        import tomllib
        raw = tomllib.loads(text)
    except ValueError:
        return fallback
    luria = raw.get("luria", raw)
    schemes = luria.get("schemes") or {}
    for spec in schemes.values():
        if isinstance(spec, dict) and spec.get("dir"):
            return spec["dir"]
    return (luria.get("paths") or {}).get("decisions", fallback)


def _fetch(url: str) -> tuple[str, str]:
    """(body, why-not). Public HTTPS only — there is no credential path here,
    deliberately: a discovery that needs a secret is a discovery CI can't
    reproduce, and the answer for an unreadable remote is a `url` template."""
    try:
        with urllib.request.urlopen(url, timeout=15) as response:
            return response.read().decode(), ""
    except urllib.error.HTTPError as exc:
        return "", ("not readable anonymously"
                    if exc.code in (401, 403, 404) else f"HTTP {exc.code}")
    except (urllib.error.URLError, OSError, UnicodeDecodeError) as exc:
        return "", f"unreachable ({exc.__class__.__name__})"


def discover(remote: Remote) -> tuple[dict[str, str], str]:
    """({code: filename}, how) for one remote. `how` names the source, or the
    reason there wasn't one — a discovery that silently finds nothing is
    indistinguishable from a remote with no documents (DP-1)."""
    if not remote.repo:
        return {}, "no `repo` configured"
    raw = f"https://raw.githubusercontent.com/{remote.repo}/{remote.ref}"
    config, _ = _fetch(f"{raw}/luria.toml")
    directory = _upstream_dir(config, remote.dir) if config else remote.dir
    body, why = _fetch(f"https://api.github.com/repos/{remote.repo}/contents/"
                       f"{directory}?ref={remote.ref}")
    if why:
        return {}, f"GitHub API: {why}"
    try:
        entries = json.loads(body)
    except ValueError:
        return {}, "GitHub API returned something that isn't JSON"
    how = f"GitHub API, {directory}/" + (" (from its luria.toml)" if config else "")
    return _from_names([e["name"] for e in entries
                        if e.get("type") == "file"]), how


# ── Reachability ─────────────────────────────────────────────────────────


@dataclass(frozen=True)
class Probe:
    remote: str
    code: str
    url: str
    status: str          # "ok" | "404" | "unchecked: <why>"

    @property
    def ok(self) -> bool:
        return self.status == "ok"


def cited() -> dict[str, set[str]]:
    """Every foreign code this project actually cites, by remote prefix."""
    from . import ref_status
    found: dict[str, set[str]] = {}
    regex = pattern()
    if regex is None:
        return found
    for path in ref_status.scanned_files():
        try:
            text = path.read_text()
        except (OSError, UnicodeDecodeError):
            continue
        for m in regex.finditer(text):
            found.setdefault(m.group("remote"), set()).add(
                normalise(m.group("code")))
    return found


def _head(url: str) -> tuple[bool, str]:
    """(reached, why-not). A HEAD, because the body is never wanted."""
    try:
        with urllib.request.urlopen(
                urllib.request.Request(url, method="HEAD"), timeout=15) as r:
            return (True, "") if r.status == 200 else (False, str(r.status))
    except urllib.error.HTTPError as exc:
        return False, str(exc.code)
    except (urllib.error.URLError, OSError) as exc:
        return False, exc.__class__.__name__


def readable(remote: Remote) -> tuple[bool, str]:
    """Whether this remote can be read at all, anonymously.

    Probed once per remote, and it is what keeps the check honest. A private
    repository answers 404 to every anonymous request, so probing documents
    without asking this first reports a shelf of perfectly good links as
    broken — a guard that cries wolf, which is a guard nobody reads
    (ADR-016)."""
    if not remote.repo:
        return False, "no `repo` configured"
    ok, why = _head(f"https://github.com/{remote.repo}")
    if ok:
        return True, ""
    return False, ("private or missing — every document will 404 anonymously"
                   if why in ("403", "404") else why)


def probe(remote: Remote, code: str, visible: bool = True) -> Probe:
    """One document. `visible` is `readable()`'s verdict for the remote, so a
    private repo yields "unverifiable" rather than a false "404"."""
    url = link(remote, code)
    if not url:
        # Not "unchecked": the lockfile was read from the remote itself, so its
        # silence about this code is a finding, not a gap.
        return Probe(remote.prefix, code, "", "absent from the remote")
    if not visible:
        return Probe(remote.prefix, code, url, "unverifiable: repo not public")
    ok, why = _head(url)
    return Probe(remote.prefix, code, url, "ok" if ok else
                 ("404" if why in ("403", "404") else f"unchecked: {why}"))


# ── CLI ──────────────────────────────────────────────────────────────────


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--refresh", action="store_true",
                    help="discover code→filename maps and write the lockfile")
    ap.add_argument("--check", action="store_true",
                    help="HEAD every cited foreign reference (needs network)")
    args = ap.parse_args()

    cfg = current()
    if not cfg.remotes:
        # No silent refusal: say what would make this command do something.
        print("luria remotes: none configured. Add one to luria.toml:\n\n"
              "  [luria.remotes.LU]\n  repo = \"owner/name\"\n\n"
              "then cite it as `LU-ADR-013`.", file=sys.stderr)
        return 0

    if args.refresh:
        found: dict[str, dict[str, str]] = {}
        for remote in cfg.remotes.values():
            entries, how = discover(remote)
            found[remote.prefix] = entries
            print(f"{remote.prefix} ({remote.label}): {len(entries)} document(s) "
                  f"via {how}")
        path = write_lock(found)
        print(f"wrote {cfg.rel(path)}")

    references = cited()
    locked = lock()
    for remote in cfg.remotes.values():
        codes = sorted(references.get(remote.prefix, ()))
        known = locked.get(remote.prefix, {})
        rung = ("an explicit url template" if remote.url
                else f"{len(known)} discovered filename(s)" if known
                else "the code-only filename convention")
        print(f"\n{remote.prefix} → {remote.label}: {len(codes)} reference(s), "
              f"resolved by {rung}")
        for code in codes:
            target = link(remote, code)
            # Not "assumed": the code-only convention (ADR-013) is exact for
            # any remote that follows it, and `--check` says whether it does.
            note = ("" if code in known or remote.url else
                    "  (by the code-only convention)")
            print(f"  {code}  {target or 'NO SUCH DOCUMENT'}{note if target else ''}")

    if args.check:
        broken, unverifiable, absent = [], [], []
        for remote in cfg.remotes.values():
            codes = sorted(references.get(remote.prefix, ()))
            if not codes:
                continue
            visible, why = readable(remote)
            print(f"\nchecking {remote.prefix} ({remote.label})"
                  + ("" if visible else f" — {why}"))
            for code in codes:
                result = probe(remote, code, visible)
                if result.ok:
                    continue
                bucket = (unverifiable if result.status.startswith("unverifiable")
                          else absent if result.status == "absent from the remote"
                          else broken)
                bucket.append(result)
                print(f"  {result.remote}-{result.code}: {result.status}"
                      + (f" — {result.url}" if result.url else ""))
        print()
        if unverifiable:
            print(f"remotes: {len(unverifiable)} could not be checked — the "
                  "repository is not readable anonymously, so the lockfile is "
                  "the only evidence those resolve")
        if absent:
            # Not a network result: the lockfile was read from the remote, so
            # its silence is a finding. `luria ref-status` lists these too, and
            # `unresolved-ok:` is where a deliberate one is acknowledged.
            print(f"remotes: {len(absent)} name no document in their remote "
                  "(see `luria ref-status`)")
        print(f"remotes: {len(broken)} reference(s) did not answer 200"
              if broken else "remotes: nothing verifiable is broken",
              file=sys.stderr if broken else sys.stdout)
    return 0            # a report, never a failure (ADR-007)


if __name__ == "__main__":
    raise SystemExit(main())
