#!/usr/bin/env python3
"""The status reports, rendered as committed views (ADR-035, #35).

    luria reports               # → the configured `reports` dir
    luria reports --out DIR     # somewhere else, e.g. a CI artifact staging dir

`luria index` renders these with every other view, so the README's badges have
a real page to land on and a stale report fails `luria lint` instead of
drifting. They used to be written only as a CI artifact (`build/doc-reports`):
a report one badge-click away gets read; one behind a CI run's download button
mostly does not (#35).

**Nothing in a report depends on the clock.** A committed view is checked for
staleness, so it must be a pure function of the record — a generation date or
an age-in-days column would go stale at midnight with no record change behind
it. Ages are stated as dates ("open since 2026-08-03"), and the live
arithmetic stays in `luria lint`'s console warnings, which nobody commits.

Every code and citation site in a report is a link (#35): the point of landing
here from a badge is to click through to the decision or the referencing line,
not to grep for it.

Written as markdown rather than JSON on purpose — the audience is a person one
badge-click deep, not a program. Nothing consumes them, so nothing breaks if
the shape changes.
"""

from __future__ import annotations

import os.path
from pathlib import Path

from . import adr_pending, doc_refs, ref_status
from .config import current

STAMP = ("*Generated by `luria index` from the record's frontmatter — "
         "built, not edited.*\n")


def _link(target: Path, base: Path) -> str:
    return os.path.relpath(target, base)


def _site(c, base: Path) -> str:
    """A citation site as a clickable list item — the label keeps the line
    number, the link lands on the file."""
    return f"- [`{c}`]({_link(c.path, base)})"


def reference_status(base: Path | None = None) -> str:
    base = current().reports if base is None else base
    docs = ref_status.load_docs()
    result = ref_status.scan(docs=docs)
    rows = ref_status.flagged(result, docs)
    excused = ref_status.acknowledged_count(result, docs)

    out = ["# Retired documents cited from current docs and code", "",
           STAMP, ""]
    out += [
        "A reference reads as \"this is why things are the way they are\", and "
        "that claim holds only while the referenced document is in force. None "
        "of this is a failure — citing a `Rejected` decision is often exactly "
        "right — so nothing here fails a build. What is worth knowing is which "
        "of these nobody has looked at.", "",
        f"**{len(rows)} retired document(s) cited without acknowledgement.** "
        f"{excused} reference(s) carry an `inactive-ok` annotation and are not "
        "listed below.", "",
        "To acknowledge one, put the reason where the reference is — "
        "`inactive-ok:` covers its line and the line below, `-block` the "
        "paragraph, `-file` the page:", "",
        "```",
        "<!-- inactive-ok: ADR-012 — why this citation is right -->",
        "```", "",
    ]

    if not rows:
        out.append("Nothing unacknowledged. ✅")
    for doc, loud, acked in rows:
        files = len({c.path for c in loud})
        tail = f" · {acked} acknowledged elsewhere" if acked else ""
        out += [f"## [{doc.code}]({_link(doc.path, base)}) — {doc.status}", "",
                f"{doc.title}", "",
                f"{len(loud)} unacknowledged reference(s) in {files} file(s)"
                f"{tail}.", ""]
        out += [_site(c, base) for c in loud]
        out.append("")

    loose = ref_status.dangling(result, docs)
    out += ["## Codes that resolve to no document", "",
            "A reference nobody can follow. Three things look identical from "
            "here and read very differently — a typo, a number carried in from "
            "another project, and an illustrative code in an example — so this "
            "is a report, not an error. `unresolved-ok:` retires the "
            "deliberate ones, at the same three scopes.", ""]
    acked = ref_status.dangling_acknowledged_count(result, docs)
    out += [f"**{len(loose)} code(s) name no document.** {acked} reference(s) "
            "carry an `unresolved-ok` annotation and are not listed below.", ""]
    if not loose:
        out.append("Every code resolves. ✅")
    for code, sites, acked in loose:
        tail = f" · {acked} acknowledged elsewhere" if acked else ""
        out += ["", f"### {code} — no such document ({len(sites)} site(s)"
                    f"{tail})", ""]
        out += [_site(c, base)
                for c in sorted(sites, key=lambda c: (str(c.path), c.line))]
    out.append("")

    out += ["## Files that opt out of reference checking", "",
            "`unlinted-file:` exempts a whole document from the reference "
            "machinery — the blunt tool for a fixture-heavy or vendored page. "
            "It is counted here rather than hidden, the same bargain as an "
            "acknowledgement: the report stays a complete account of what "
            "nobody is checking.", ""]
    if result.unlinted:
        out += [f"- [`{current().rel(p)}`]({_link(p, base)})"
                for p in sorted(result.unlinted)]
    else:
        out.append("None. Every scanned file is checked. ✅")
    out.append("")

    stale = ref_status.stale_annotations(result, docs)
    for path in doc_refs.doc_files():
        stale += doc_refs.directive_problems(path, path.read_text())
    out += ["## Directives that no longer apply", ""]
    out += ([f"- {line}" for line in sorted(stale)] if stale
            else ["None. Every annotation still governs something. ✅"])
    out.append("")
    return "\n".join(out)


def pending_decisions(base: Path | None = None) -> str:
    base = current().reports if base is None else base
    rows = adr_pending.pending()
    uncited = [r for r in rows if not r.cites]
    undated = sum(1 for r in rows if r.date is None)

    out = ["# Documents awaiting a decision", "", STAMP, ""]
    out += [
        "`Proposed` and `Deferred` both describe an open question. Neither says "
        "*since when*, and that is the signal: a decision proposed last week is "
        "pending; the same one a year later was either overdue or settled in "
        "code and never written back.", "",
        f"**{len(rows)} document(s) awaiting a decision"
        + (f", {undated} undated" if undated else "") + ".**",
        "",
    ]
    if rows:
        out += ["| Open since | Status | Code | Cited | Unack. | Title |",
                "|---|---|---|--:|--:|---|"]
        for r in rows:
            since = r.date.isoformat() if r.date is not None else "undated"
            link = f"[{r.code}]({_link(r.path, base)})"
            out.append(f"| {since} | {r.status} | {link} | {r.cites} | "
                       f"{r.unacknowledged} | {r.title} |")
        out.append("")
    out += [
        "The citation count is the second axis, and it flips the priority: an "
        "old proposal nothing references is a stalled idea worth closing, while "
        "an old proposal many files cite is a decision the codebase has already "
        "made and hasn't written down.", "",
    ]
    out += ["This count and the reference-status report's will differ, and that "
            "is not an off-by-one. That report covers documents something "
            "actually **cites** and hasn't acknowledged; this one covers every "
            "**undecided** document. One here is missing from there for exactly "
            "one of two reasons: nothing cites it, or every citation carries an "
            "`inactive-ok` annotation.", ""]
    if uncited:
        codes = ", ".join(f"[{r.code}]({_link(r.path, base)})" for r in uncited)
        one = len(uncited) == 1
        out += [f"**Cited nowhere at all** ({len(uncited)}): {codes} — "
                f"{'this is' if one else 'these are'} the cheapest to close, "
                "since nothing depends on the answer.", ""]
    return "\n".join(out)


def outputs(out_dir: Path | None = None) -> dict[Path, str]:
    """Both reports, keyed by where they land — the unit `luria index`
    renders, so a stale report fails the same staleness check as every other
    view (#35)."""
    out_dir = current().reports if out_dir is None else out_dir
    return {
        out_dir / "reference-status.md": reference_status(out_dir),
        out_dir / "pending-decisions.md": pending_decisions(out_dir),
    }


def write(out_dir: Path | None = None) -> list[Path]:
    rendered = outputs(out_dir)
    for path, text in rendered.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
    return sorted(rendered)


def run(out: str = None) -> None:
    """Write the status reports — to the configured dir, or --out elsewhere
    (e.g. a CI artifact staging dir)."""
    for path in write(Path(out) if out else None):
        print(f"wrote {path}")


if __name__ == "__main__":
    import fire
    fire.Fire(run)
