from __future__ import annotations
import os.path
from pathlib import Path
from . import adr_pending, doc_refs, ref_status
from .config import current
STAMP = "*Generated by `luria index` from the record's frontmatter — built, not edited.*\n"

def _link(target: Path, base: Path) -> str:
    return os.path.relpath(target, base)

def _n(count: int, noun: str, plural: str='') -> str:
    return f"{count} {(noun if count == 1 else plural or noun + 's')}"

def _site(c, base: Path) -> str:
    return f'- [`{c}`]({_link(c.path, base)})'

def reference_status(base: Path | None=None) -> str:
    base = current().reports if base is None else base
    docs = ref_status.load_docs()
    result = ref_status.scan(docs=docs)
    rows = ref_status.flagged(result, docs)
    excused = ref_status.acknowledged_count(result, docs)
    out = ['# Reference status', '', STAMP, '']
    out += ['Every reference in the record is a claim — "this is why things are the way they are" — and this page is the account of the claims that need a human eye: citations of documents that are not in force, codes that resolve to nothing, and the acknowledgements and exemptions that keep either kind quiet on purpose. Nothing on this page fails a build (ADR-035): every row is a judgement call, and the acknowledgement comments are how a judgement, once made, stops being asked again.', '', '## Documents cited while not in force', '', 'Only an `Active` document is in force. `Proposed` and `Deferred` mean *not in force yet* — an open question, being cited as if it were settled — while `Superseded` and `Rejected` mean *no longer in force*, which is often a perfectly good thing to cite: history, or a rejection worth pointing at. Either way the citation should be deliberate, and this section lists the ones nobody has vouched for yet.', '', f"**{_n(len(rows), 'document')} cited without acknowledgement.** Not listed: {_n(excused, 'citation')} someone has already vouched for with an `inactive-ok:` comment at the citing site.", '', 'To vouch for one, put the reason where the citation is — `inactive-ok:` covers its own line and the line below it, `inactive-ok-block:` its paragraph, `inactive-ok-file:` the whole page:', '', '```', '<!-- inactive-ok: ADR-012 — why this citation is right -->', '```', '']
    if not rows:
        out.append('Nothing unacknowledged. ✅')
    for doc, loud, acked in rows:
        files = len({c.path for c in loud})
        tail = f"; {_n(acked, 'other citation')} of it {('is' if acked == 1 else 'are')} acknowledged" if acked else ''
        out += [f'### [{doc.code}]({_link(doc.path, base)}) — {doc.status}', '', f'{doc.title}', '', f"{_n(len(loud), 'citation')} in {_n(files, 'file')} await{('s' if len(loud) == 1 else '')} a look{tail}.", '']
        out += [_site(c, base) for c in loud]
        out.append('')
    loose = ref_status.dangling(result, docs)
    acked = ref_status.dangling_acknowledged_count(result, docs)
    out += ['## Codes that resolve to no document', '', 'A reference the reader cannot follow: the code names no document in this record. A typo, a number carried in from another project, and an illustrative code in an example all look identical from here — telling them apart takes a human, so this is a report, not an error.', '', f"**{_n(len(loose), 'code')} unaccounted for.** Not listed: {_n(acked, 'mention')} marked deliberate with an `unresolved-ok:` comment (same syntax and scopes as `inactive-ok:` above).", '']
    if not loose:
        out.append('Every code resolves. ✅')
    for code, sites, acked in loose:
        tail = f" · {_n(acked, 'other mention')} marked deliberate" if acked else ''
        out += ['', f"### {code} — resolves to nothing ({_n(len(sites), 'unmarked site')}{tail})", '']
        out += [_site(c, base) for c in sorted(sites, key=lambda c: (str(c.path), c.line))]
    out.append('')
    out += ['## Files that opt out of reference checking', '', '`unlinted-file:` exempts a whole document from the reference machinery — the blunt tool for a fixture-heavy or vendored page. It is counted here rather than hidden, the same bargain as an acknowledgement: the report stays a complete account of what nobody is checking.', '']
    if result.unlinted:
        out += [f'- [`{current().rel(p)}`]({_link(p, base)})' for p in sorted(result.unlinted)]
    else:
        out.append('None. Every scanned file is checked. ✅')
    out.append('')
    stale = ref_status.stale_annotations(result, docs)
    for path in doc_refs.doc_files():
        stale += doc_refs.directive_problems(path, path.read_text())
    out += ['## Directives that no longer apply', '']
    out += [f'- {line}' for line in sorted(stale)] if stale else ['None. Every annotation still governs something. ✅']
    out.append('')
    return '\n'.join(out)

def pending_decisions(base: Path | None=None) -> str:
    base = current().reports if base is None else base
    rows = adr_pending.pending()
    uncited = [r for r in rows if not r.cites]
    undated = sum((1 for r in rows if r.date is None))
    out = ['# Documents awaiting a decision', '', STAMP, '']
    out += ['`Proposed` and `Deferred` both describe an open question. Neither says *since when*, and that is the signal: a decision proposed last week is pending; the same one a year later was either overdue or settled in code and never written back.', '', f'**{len(rows)} document(s) awaiting a decision' + (f', {undated} undated' if undated else '') + '.**', '']
    if rows:
        out += ['| Open since | Status | Code | Cited | Unack. | Title |', '|---|---|---|--:|--:|---|']
        for r in rows:
            since = r.date.isoformat() if r.date is not None else 'undated'
            link = f'[{r.code}]({_link(r.path, base)})'
            out.append(f'| {since} | {r.status} | {link} | {r.cites} | {r.unacknowledged} | {r.title} |')
        out.append('')
    out += ["The citation count is the second axis, and it flips the priority: an old proposal nothing references is a stalled idea worth closing, while an old proposal many files cite is a decision the codebase has already made and hasn't written down.", '']
    out += ["This count and the reference-status report's will differ, and that is not an off-by-one. That report covers documents something actually **cites** and hasn't acknowledged; this one covers every **undecided** document. One here is missing from there for exactly one of two reasons: nothing cites it, or every citation carries an `inactive-ok` annotation.", '']
    if uncited:
        codes = ', '.join((f'[{r.code}]({_link(r.path, base)})' for r in uncited))
        one = len(uncited) == 1
        out += [f"**Cited nowhere at all** ({len(uncited)}): {codes} — {('this is' if one else 'these are')} the cheapest to close, since nothing depends on the answer.", '']
    return '\n'.join(out)

def outputs(out_dir: Path | None=None) -> dict[Path, str]:
    out_dir = current().reports if out_dir is None else out_dir
    return {out_dir / 'reference-status.md': reference_status(out_dir), out_dir / 'pending-decisions.md': pending_decisions(out_dir)}

def write(out_dir: Path | None=None) -> list[Path]:
    rendered = outputs(out_dir)
    for path, text in rendered.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
    return sorted(rendered)

def run(out: str=None) -> None:
    for path in write(Path(out) if out else None):
        print(f'wrote {path}')
if __name__ == '__main__':
    import fire
    fire.Fire(run)
