from __future__ import annotations
import fnmatch
import posixpath
import re
import shutil
import sys
from dataclasses import dataclass, field
from pathlib import Path
from . import doc_refs
from .adr_index import parse_frontmatter
from .config import Site, current
ALWAYS_EXCLUDED = ('_template.md',)
EXCLUDED_DIRS = ('.git', '.venv', 'venv', 'node_modules', '__pycache__', '.pytest_cache', '.mypy_cache')
IMAGE_SUFFIXES = ('.png', '.jpg', '.jpeg', '.gif', '.svg', '.webp', '.avif')
NOT_A_PATH = set('\\{}*|<>"')
RELATIVE_TARGET_RE = re.compile('(?:(?<=\\]\\()|(?<=<a href=")|(?<=<a href=\')|(?<=<img src=")|(?<=<img src=\'))(?![#/]|[A-Za-z][A-Za-z0-9+.-]*:)([^)\'"\\s]+)')
THEME_DEFAULTS: dict[str, dict[str, str]] = {'light': {'light': '#faf8f8', 'lightgray': '#e5e5e5', 'gray': '#b8b8b8', 'darkgray': '#4e4e4e', 'dark': '#2b2b2b', 'secondary': '#284b63', 'tertiary': '#84a59d', 'highlight': 'rgba(143, 159, 169, 0.15)', 'textHighlight': '#fff23688'}, 'dark': {'light': '#161618', 'lightgray': '#393639', 'gray': '#646464', 'darkgray': '#d4d4d4', 'dark': '#ebebec', 'secondary': '#7b97aa', 'tertiary': '#84a59d', 'highlight': 'rgba(143, 159, 169, 0.15)', 'textHighlight': '#b3aa0288'}}
INK_VAR = '--luria-ink'
QUARTZ_CONFIG = '// GENERATED by `luria site` from luria.toml — edit that, not this.\n//\n// Two settings are load-bearing and the rest is presentation:\n//\n//   markdownLinkResolution: "relative" — the record\'s links are ordinary\n//   relative paths, spelled for the directory each page sits in. Quartz\'s\n//   default ("shortest") re-resolves them by basename and silently lands a\n//   `docs/decisions/README.md` link on the wrong page.\n//\n//   CreatedModifiedDate without the git provider — the vault is a staged copy\n//   outside any repository, so a git lookup finds nothing and warns once per\n//   file. Frontmatter first (`date:`, `created:`), filesystem as the floor.\nimport {{ QuartzConfig }} from "./quartz/cfg"\nimport * as Plugin from "./quartz/plugins"\n\nconst config: QuartzConfig = {{\n  configuration: {{\n    pageTitle: "{title}",\n    pageTitleSuffix: "",\n    enableSPA: true,\n    enablePopovers: true,\n    analytics: null,\n    locale: "en-US",\n    baseUrl: "{base_url}",\n    ignorePatterns: [],\n    defaultDateType: "created",\n    theme: {{\n      fontOrigin: "googleFonts",\n      cdnCaching: true,\n      typography: {{\n        header: "Schibsted Grotesk",\n        body: "Source Sans Pro",\n        code: "IBM Plex Mono",\n      }},\n      colors: {{\n{colors}\n      }},\n    }},\n  }},\n  plugins: {{\n    transformers: [\n      Plugin.FrontMatter(),\n      Plugin.CreatedModifiedDate({{ priority: ["frontmatter", "filesystem"] }}),\n      Plugin.SyntaxHighlighting({{\n        theme: {{ light: "github-light", dark: "github-dark" }},\n        keepBackground: false,\n      }}),\n      Plugin.ObsidianFlavoredMarkdown({{ enableInHtmlEmbed: false }}),\n      Plugin.GitHubFlavoredMarkdown(),\n      Plugin.TableOfContents(),\n      Plugin.CrawlLinks({{ markdownLinkResolution: "relative" }}),\n      Plugin.Description(),\n      Plugin.Latex({{ renderEngine: "katex" }}),\n    ],\n    filters: [Plugin.RemoveDrafts()],\n    emitters: [\n      Plugin.AliasRedirects(),\n      Plugin.ComponentResources(),\n      Plugin.ContentPage(),\n      Plugin.FolderPage(),\n      Plugin.TagPage(),\n      Plugin.ContentIndex({{ enableSiteMap: true, enableRSS: true }}),\n      Plugin.Assets(),\n      Plugin.Static(),\n      Plugin.Favicon(),\n      Plugin.NotFoundPage(),\n      Plugin.CustomOgImages(),\n    ],\n  }},\n}}\n\nexport default config\n'
QUARTZ_LAYOUT = '// GENERATED by `luria site`. Quartz\'s default layout, with one change.\n//\n// The graph moves out of the right sidebar and into the content column,\n// directly under the title (#71). Quartz\'s sidebars stack *below* the article\n// under 1200px — so on any window narrower than that, which is most of them,\n// the graph a record publishes itself for was the last thing on the page. The\n// obvious remedies both miss: `MobileOnly` switches at 800px, leaving the\n// 800–1200px band broken, and reordering the grid in CSS couples this file to\n// Quartz\'s internal grid areas, which is what a version bump breaks.\n//\n// The cost is real and accepted: on a wide screen the graph now scrolls away\n// with the content instead of sitting in the sticky rail. A view that is\n// always visible to some readers and never visible to others is the worse\n// trade.\nimport {{ PageLayout, SharedLayout }} from "./quartz/cfg"\nimport * as Component from "./quartz/components"\n\nexport const sharedPageComponents: SharedLayout = {{\n  head: Component.Head(),\n  header: [],\n  afterBody: [],\n  footer: Component.Footer({{\n    links: {{\n      Repository: "{repo_url}",\n      Quartz: "https://quartz.jzhao.xyz/",\n    }},\n  }}),\n}}\n\nexport const defaultContentPageLayout: PageLayout = {{\n  beforeBody: [\n    Component.ConditionalRender({{\n      component: Component.Breadcrumbs(),\n      condition: (page) => page.fileData.slug !== "index",\n    }}),\n    Component.ArticleTitle(),\n    Component.ContentMeta(),\n    Component.TagList(),\n    // Retuned for the content column: Quartz\'s defaults are set for a 320px\n    // rail, and in a column twice that width they leave the neighbourhood\n    // huddled in the middle. Depth stays at 1 — depth 2 on a record this\n    // densely cross-cited renders a hairball with the current page lost in\n    // it, which is a picture of nothing.\n    Component.Graph({{\n      localGraph: {{\n        depth: 1,\n        scale: 1.05,\n        repelForce: 1.4,\n        centerForce: 0.2,\n        linkDistance: 70,\n        fontSize: 0.75,\n        focusOnHover: true,\n      }},\n    }}),\n  ],\n  left: [\n    Component.PageTitle(),\n    Component.MobileOnly(Component.Spacer()),\n    Component.Flex({{\n      components: [\n        {{ Component: Component.Search(), grow: true }},\n        {{ Component: Component.Darkmode() }},\n        {{ Component: Component.ReaderMode() }},\n      ],\n    }}),\n    Component.Explorer(),\n  ],\n  right: [\n    Component.DesktopOnly(Component.TableOfContents()),\n    Component.Backlinks(),\n  ],\n}}\n\nexport const defaultListPageLayout: PageLayout = {{\n  beforeBody: [\n    Component.Breadcrumbs(),\n    Component.ArticleTitle(),\n    Component.ContentMeta(),\n  ],\n  left: [\n    Component.PageTitle(),\n    Component.MobileOnly(Component.Spacer()),\n    Component.Flex({{\n      components: [\n        {{ Component: Component.Search(), grow: true }},\n        {{ Component: Component.Darkmode() }},\n      ],\n    }}),\n    Component.Explorer(),\n  ],\n  right: [],\n}}\n'
CUSTOM_SCSS = '// GENERATED by `luria site` from luria.toml — edit that, not this.\n@use "./base.scss";\n'
LOGO_SCSS = '\n.page-title a {{\n  display: block;\n  width: 100%;\n  max-width: {width};\n  aspect-ratio: {w} / {h};\n  background: url("{light}") no-repeat left center;\n  background-size: contain;\n  text-indent: -9999px;\n  overflow: hidden;\n  white-space: nowrap;\n}}\n\n// Two baked variants rather than one self-inverting file, because whether\n// artwork can invert itself is a *browser* question. Quartz declares\n// `color-scheme` per theme, and a browser that propagates that into an\n// embedded SVG resolves the artwork\'s own `prefers-color-scheme` against the\n// site\'s toggle — measured, and it is what Chromium does. A browser that\n// doesn\'t resolves it against the operating system, and a reader whose OS\n// disagrees with the toggle gets dark ink on a dark page. Baking the variants\n// makes the answer the same everywhere, and is the only way to theme a logo\n// that has no media query of its own.\n:root[saved-theme="dark"] .page-title a {{\n  background-image: url("{dark}");\n}}\n'

@dataclass
class Report:
    pages: int = 0
    assets: int = 0
    to_source: int = 0
    unplaced: list[str] = field(default_factory=list)
    lineage: int = 0

    def lines(self) -> list[str]:
        out = [f'{self.pages} pages, {self.assets} assets staged', f'{self.lineage} record lines added', f'{self.to_source} links redirected to the repository']
        if self.unplaced:
            shown = sorted(self.unplaced)
            out.append(f'{len(shown)} reference(s) the site cannot place:')
            out += [f'  {line}' for line in shown[:20]]
            if len(shown) > 20:
                out.append(f'  …and {len(shown) - 20} more')
        return out

def colors(site: Site) -> str:
    out = []
    for mode, key in (('light', 'lightMode'), ('dark', 'darkMode')):
        override = site.theme.get(mode, {}) or {}
        unknown = sorted(set(override) - set(THEME_DEFAULTS[mode]))
        if unknown:
            raise SystemExit(f"luria site: [luria.site.theme.{mode}] has no colour named {', '.join(unknown)} — Quartz knows {', '.join(THEME_DEFAULTS[mode])}")
        merged = {**THEME_DEFAULTS[mode], **override}
        body = ''.join((f'          {k}: "{v}",\n' for k, v in merged.items()))
        out.append(f'        {key}: {{\n{body}        }},')
    return '\n'.join(out)

def _reinked(svg: str, ink: str) -> str:
    if INK_VAR not in svg:
        return svg
    return re.sub('<svg\\b', f'<svg style="{INK_VAR}:{ink}"', svg, count=1)

def _svg_size(svg: str) -> tuple[float, float]:
    m = re.search('viewBox="([\\d.\\s-]+)"', svg)
    if m:
        parts = [float(x) for x in m.group(1).split()]
        if len(parts) == 4 and parts[2] and parts[3]:
            return (parts[2], parts[3])
    return (4.0, 1.0)

def _excluded(rel: str, site: Site) -> bool:
    parts = Path(rel).parts
    if any((part in EXCLUDED_DIRS for part in parts)):
        return True
    if Path(rel).name in ALWAYS_EXCLUDED:
        return True
    return any((fnmatch.fnmatch(rel, pattern) for pattern in site.exclude))

def publishable(cfg=None, skip: Path | None=None) -> list[Path]:
    cfg = cfg or current()
    out = []
    for path in sorted(cfg.root.rglob('*.md')):
        if skip and skip in path.parents:
            continue
        rel = path.relative_to(cfg.root).as_posix()
        if _excluded(rel, cfg.site):
            continue
        if cfg.link_base(path) != path.parent:
            continue
        out.append(path)
    return out

def destination(path: Path, cfg) -> Path:
    rel = path.relative_to(cfg.root)
    return Path('index.md') if rel.as_posix() == 'README.md' else rel

def _alias(path: Path, cfg) -> str | None:
    for scheme in cfg.schemes.values():
        if scheme.render != 'index' or path.parent != scheme.dir:
            continue
        number = scheme.number_of(path)
        if number is not None:
            return scheme.code(number)
    return None

def record_line(meta: dict, source: Path) -> str:
    bits = []
    if (status := str(meta.get('status', '')).strip()):
        bits.append(f'**Status** {status}')
    if (version := meta.get('version')) and str(version).strip() != '1':
        bits.append(f'**Version** {version}')
    if (date := str(meta.get('date', '')).strip()):
        bits.append(f'**Filed** {date}')
    if (issues := re.findall('#\\d+', str(meta.get('issue', '')))):
        bits.append('**Issue** ' + ' · '.join((f'[[{issue}]]' for issue in issues)))
    influenced = [str(c).strip() for c in meta.get('influenced_by') or []]
    if influenced:
        codes = ' · '.join((f'[[{code}]]' for code in influenced if code))
        bits.append(f'**Influenced by** {codes}')
    if not bits:
        return ''
    expanded, _ = doc_refs.expand_wikilinks('> ' + ' · '.join(bits), source)
    return expanded

def _insert_after_title(body: str, line: str) -> str:
    if not line:
        return body
    for match in re.finditer('^# .+$', body, re.MULTILINE):
        cut = match.end()
        return body[:cut] + '\n\n' + line + body[cut:]
    return line + '\n\n' + body

def split_frontmatter(text: str) -> tuple[str | None, str]:
    if not text.startswith('---\n'):
        return (None, text)
    end = text.find('\n---\n', 3)
    if end == -1:
        return (None, text)
    return (text[4:end + 1], text[end + 5:])

def _with_alias(front: str, alias: str | None) -> str:
    if not alias:
        return front
    return front.rstrip('\n') + f'\naliases:\n- "{alias}"\n'

def landing_page(text: str, cfg) -> str:
    yaml_text, body = split_frontmatter(text)
    added = f'title: "{cfg.site.title}"\naliases:\n- "README"\n'
    if yaml_text is None:
        return '---\n' + added + '---\n\n' + text
    if re.search('^title:', yaml_text, re.MULTILINE):
        added = 'aliases:\n- "README"\n'
    return '---\n' + yaml_text.rstrip('\n') + '\n' + added + '---\n' + body

def _retarget(text: str, source: Path, cfg, published: set[Path], staged_assets: dict[Path, Path], report: Report) -> str:
    site = cfg.site
    rel_source = cfg.rel(source)
    quoted = doc_refs.code_spans(text)

    def fix(match: re.Match) -> str:
        target = match.group(1)
        if any((a <= match.start() < b for a, b in quoted)):
            return target
        if NOT_A_PATH & set(target):
            return target
        path_part, sep, fragment = target.partition('#')
        if not path_part:
            return target
        try:
            resolved = (source.parent / path_part).resolve()
            inside = resolved.relative_to(cfg.root.resolve())
        except (ValueError, OSError):
            return target
        absolute = cfg.root / inside
        if absolute in published or absolute.is_dir():
            return target
        if not absolute.exists():
            report.unplaced.append(f'{rel_source} → {target}')
            return target
        if absolute.suffix.lower() in IMAGE_SUFFIXES:
            staged_assets[absolute] = inside
            return target
        if not site.source_url:
            report.unplaced.append(f'{rel_source} → {target}')
            return target
        report.to_source += 1
        return f"{site.source_url.rstrip('/')}/{inside.as_posix()}{sep}{fragment}"
    return RELATIVE_TARGET_RE.sub(fix, text)

def brand(out: Path, cfg, report: Report) -> str:
    site = cfg.site
    static = out / 'static'
    static.mkdir(parents=True, exist_ok=True)
    for label, source in (('icon', site.icon), ('logo', site.logo), ('logo_dark', site.logo_dark)):
        if source is not None and (not source.exists()):
            report.unplaced.append(f'[luria.site] {label} → {cfg.rel(source)} (no such file)')
    if site.icon is not None and site.icon.exists():
        shutil.copyfile(site.icon, static / f'icon{site.icon.suffix.lower()}')
        report.assets += 1
    if site.logo is None or not site.logo.exists():
        return CUSTOM_SCSS
    light_svg = site.logo.read_text(encoding='utf-8')
    dark_source = site.logo_dark if site.logo_dark and site.logo_dark.exists() else None
    dark_svg = dark_source.read_text(encoding='utf-8') if dark_source else light_svg
    palette = {mode: {**THEME_DEFAULTS[mode], **(site.theme.get(mode) or {})} for mode in ('light', 'dark')}
    light_svg = _reinked(light_svg, palette['light']['dark'])
    if dark_source is None:
        dark_svg = _reinked(dark_svg, palette['dark']['dark'])
    (static / 'logo-light.svg').write_text(light_svg, encoding='utf-8')
    (static / 'logo-dark.svg').write_text(dark_svg, encoding='utf-8')
    report.assets += 2
    w, h = _svg_size(light_svg)
    width = f'{min(15.0, 3.6 * w / h):.1f}rem'
    return CUSTOM_SCSS + LOGO_SCSS.format(width=width, w=w, h=h, light='static/logo-light.svg', dark='static/logo-dark.svg')

def stage(out: Path, cfg=None) -> Report:
    cfg = cfg or current()
    out = out.resolve()
    content = out / 'content'
    if content.exists():
        shutil.rmtree(content)
    content.mkdir(parents=True)
    pages = publishable(cfg, skip=out)
    published = set(pages)
    report, assets = (Report(), {})
    for path in pages:
        text = path.read_text(encoding='utf-8')
        yaml_text, body = split_frontmatter(text)
        if yaml_text is not None:
            meta = parse_frontmatter(text)[0]
            line = record_line(meta, path)
            if line:
                body = _insert_after_title(body, line)
                report.lineage += 1
                if '[[' in line:
                    report.unplaced.append(f'{cfg.rel(path)} → unresolved in frontmatter: ' + ' '.join(re.findall('\\[\\[[^\\]]+\\]\\]', line)))
            text = '---\n' + _with_alias(yaml_text, _alias(path, cfg)) + '---\n' + body
        dest_rel = destination(path, cfg)
        if dest_rel.as_posix() == 'index.md':
            text = landing_page(text, cfg)
        text = _retarget(text, path, cfg, published, assets, report)
        dest = content / dest_rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(text, encoding='utf-8')
        report.pages += 1
    for absolute, rel in assets.items():
        dest = content / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(absolute, dest)
        report.assets += 1
    (out / 'quartz.config.ts').write_text(QUARTZ_CONFIG.format(title=cfg.site.title, base_url=cfg.site.base_url, colors=colors(cfg.site)), encoding='utf-8')
    (out / 'custom.scss').write_text(brand(out, cfg, report), encoding='utf-8')
    repo_url = re.sub('/blob/[^/]+/?$', '', cfg.site.source_url)
    (out / 'quartz.layout.ts').write_text(QUARTZ_LAYOUT.format(repo_url=repo_url or cfg.site.source_url), encoding='utf-8')
    return report

def run(out: str='build/site') -> None:
    cfg = current()
    report = stage(Path(out) if Path(out).is_absolute() else cfg.root / out, cfg)
    print(f'staged {out}/content')
    for line in report.lines():
        print(f'  {line}')
    if not cfg.site.base_url:
        print('  no site.base_url and none derivable from issue_url — the site will build with relative URLs only')
if __name__ == '__main__':
    sys.exit(run())
