"""Stage the record as an Obsidian/Quartz vault, ready to build (ADR-042).

    luria site --out build/site

writes `build/site/content/` — the record's markdown, every path preserved —
plus a `quartz.config.ts` derived from `luria.toml`. Handing that pair to a
pinned Quartz checkout produces the published site: the decisions, the
principles document, the devlog books and the reports, with Quartz's graph
and backlinks over the citations the record already carries.

Three rules do the whole job.

**Paths are preserved, so links are not rewritten.** Every relative target in
this record was spelled by `luria link --fix` for the directory the prose
lands in. Staging into the same tree shape means those targets keep resolving
and the site inherits the fixer's work whole, rather than a second link
resolver drifting from the first (DP-4).

**A source that renders into a view is not published; the view is.** That set
is derived, not listed: `Config.link_base(path)` already answers "which
directory do this file's links resolve against?", and a file whose answer is
not its own directory is a fragment, a journal entry or a document-scheme
source — prose written to be read *somewhere else*. Publishing it would both
duplicate the view and break every link in it.

**A link out of the published set goes to the repository.** The record cites
workflows, templates and the licence, which are real files and not pages. An
image is copied so it renders; anything else becomes a `source_url` link, and
`luria site` counts what it could not place rather than emitting a dead one
(DP-1).

The one thing added rather than copied: each scheme document gets a **record
line** under its title — status, date, issue, and the decisions named in
`influenced_by:`. Those facts live in frontmatter, which a site renders as
nothing at all, and `influenced_by` is precisely the lineage a citation graph
exists to show. The line is composed with wikilinks and expanded by the same
resolver the record uses everywhere else.
"""

from __future__ import annotations

import fnmatch
import posixpath
import re
import shutil
import sys
from dataclasses import dataclass, field
from pathlib import Path

from . import doc_refs
from .adr_index import parse_frontmatter
from .config import Site, current

# Skipped wherever they turn up: a scaffold seed whose references are
# illustrative, and directories no record keeps prose in.
ALWAYS_EXCLUDED = ("_template.md",)
EXCLUDED_DIRS = (".git", ".venv", "venv", "node_modules", "__pycache__",
                 ".pytest_cache", ".mypy_cache")

# Copied into the vault rather than linked out to the repository: these render
# in place, and a link is not a picture.
IMAGE_SUFFIXES = (".png", ".jpg", ".jpeg", ".gif", ".svg", ".webp", ".avif")

# Characters no publishable repository path contains. The backstop for the one
# quoting form `doc_refs.code_spans` does not model — a four-space indented
# block — where a regex like `[.:](\\d{4,5})` reads as a link target. Reading
# a specimen wrongly would only miscount; *rewriting* one would corrupt the
# example the prose is teaching, so the site needs the guard the lint doesn't.
NOT_A_PATH = set("\\{}*|<>\"")

# A markdown link or image with a relative target — the same shape the index
# rebases, and for the same reason: those are the only ones a move disturbs.
# The `<a href>` alternative is not hypothetical: markdown isn't parsed inside
# a raw HTML block, so that is the form the fixer writes there (ADR-005).
RELATIVE_TARGET_RE = re.compile(
    r"(?:(?<=\]\()|(?<=<a href=\")|(?<=<a href='))"
    r"(?![#/]|[A-Za-z][A-Za-z0-9+.-]*:)([^)'\"\s]+)")

QUARTZ_CONFIG = """\
// GENERATED by `luria site` from luria.toml — edit that, not this.
//
// Two settings are load-bearing and the rest is presentation:
//
//   markdownLinkResolution: "relative" — the record's links are ordinary
//   relative paths, spelled for the directory each page sits in. Quartz's
//   default ("shortest") re-resolves them by basename and silently lands a
//   `docs/decisions/README.md` link on the wrong page.
//
//   CreatedModifiedDate without the git provider — the vault is a staged copy
//   outside any repository, so a git lookup finds nothing and warns once per
//   file. Frontmatter first (`date:`, `created:`), filesystem as the floor.
import {{ QuartzConfig }} from "./quartz/cfg"
import * as Plugin from "./quartz/plugins"

const config: QuartzConfig = {{
  configuration: {{
    pageTitle: "{title}",
    pageTitleSuffix: "",
    enableSPA: true,
    enablePopovers: true,
    analytics: null,
    locale: "en-US",
    baseUrl: "{base_url}",
    ignorePatterns: [],
    defaultDateType: "created",
    theme: {{
      fontOrigin: "googleFonts",
      cdnCaching: true,
      typography: {{
        header: "Schibsted Grotesk",
        body: "Source Sans Pro",
        code: "IBM Plex Mono",
      }},
      colors: {{
        lightMode: {{
          light: "#faf8f8",
          lightgray: "#e5e5e5",
          gray: "#b8b8b8",
          darkgray: "#4e4e4e",
          dark: "#2b2b2b",
          secondary: "#284b63",
          tertiary: "#84a59d",
          highlight: "rgba(143, 159, 169, 0.15)",
          textHighlight: "#fff23688",
        }},
        darkMode: {{
          light: "#161618",
          lightgray: "#393639",
          gray: "#646464",
          darkgray: "#d4d4d4",
          dark: "#ebebec",
          secondary: "#7b97aa",
          tertiary: "#84a59d",
          highlight: "rgba(143, 159, 169, 0.15)",
          textHighlight: "#b3aa0288",
        }},
      }},
    }},
  }},
  plugins: {{
    transformers: [
      Plugin.FrontMatter(),
      Plugin.CreatedModifiedDate({{ priority: ["frontmatter", "filesystem"] }}),
      Plugin.SyntaxHighlighting({{
        theme: {{ light: "github-light", dark: "github-dark" }},
        keepBackground: false,
      }}),
      Plugin.ObsidianFlavoredMarkdown({{ enableInHtmlEmbed: false }}),
      Plugin.GitHubFlavoredMarkdown(),
      Plugin.TableOfContents(),
      Plugin.CrawlLinks({{ markdownLinkResolution: "relative" }}),
      Plugin.Description(),
      Plugin.Latex({{ renderEngine: "katex" }}),
    ],
    filters: [Plugin.RemoveDrafts()],
    emitters: [
      Plugin.AliasRedirects(),
      Plugin.ComponentResources(),
      Plugin.ContentPage(),
      Plugin.FolderPage(),
      Plugin.TagPage(),
      Plugin.ContentIndex({{ enableSiteMap: true, enableRSS: true }}),
      Plugin.Assets(),
      Plugin.Static(),
      Plugin.Favicon(),
      Plugin.NotFoundPage(),
      Plugin.CustomOgImages(),
    ],
  }},
}}

export default config
"""


@dataclass
class Report:
    """What one staging run did, in the shape the CLI prints and a test
    asserts on. Counted rather than merely logged: a link that could not be
    placed is the number worth watching, and a silent staging run would hide
    exactly the reference the site is meant to make followable (DP-1)."""
    pages: int = 0
    assets: int = 0
    to_source: int = 0                  # links redirected at the repository
    unplaced: list[str] = field(default_factory=list)
    lineage: int = 0                    # record lines added to scheme docs

    def lines(self) -> list[str]:
        out = [f"{self.pages} pages, {self.assets} assets staged",
               f"{self.lineage} record lines added",
               f"{self.to_source} links redirected to the repository"]
        if self.unplaced:
            shown = sorted(self.unplaced)
            out.append(f"{len(shown)} reference(s) the site cannot place:")
            out += [f"  {line}" for line in shown[:20]]
            if len(shown) > 20:
                out.append(f"  …and {len(shown) - 20} more")
        return out


def _excluded(rel: str, site: Site) -> bool:
    parts = Path(rel).parts
    if any(part in EXCLUDED_DIRS for part in parts):
        return True
    if Path(rel).name in ALWAYS_EXCLUDED:
        return True
    return any(fnmatch.fnmatch(rel, pattern) for pattern in site.exclude)


def publishable(cfg=None, skip: Path | None = None) -> list[Path]:
    """Every markdown file the site publishes, in a stable order.

    The derived rule is the second clause: a file whose links resolve against
    some *other* directory is a source rendered into a view, and the view is
    already here. Excluding it is not tidiness — its links are spelled for
    where its prose lands, so publishing it in place would break every one.

    `skip` is the staging directory when it sits inside the project — the
    default `build/site` does. Without it the second run publishes the first
    run's output, and the site grows a copy of itself per build."""
    cfg = cfg or current()
    out = []
    for path in sorted(cfg.root.rglob("*.md")):
        if skip and skip in path.parents:
            continue
        rel = path.relative_to(cfg.root).as_posix()
        if _excluded(rel, cfg.site):
            continue
        if cfg.link_base(path) != path.parent:
            continue
        out.append(path)
    return out


def destination(path: Path, cfg) -> Path:
    """Where `path` lands in the vault, relative to `content/`.

    Only the root README moves: Quartz serves `index.md` as the landing page,
    and a record whose front door is its README should not need a second copy
    of it to have one."""
    rel = path.relative_to(cfg.root)
    return Path("index.md") if rel.as_posix() == "README.md" else rel


def _alias(path: Path, cfg) -> str | None:
    """The bare code a scheme document should also answer to — `/ADR-025`.

    This is the one place Obsidian's convention and Luria's meet. A wikilink
    here is a *code*, resolved through the scheme config; in a vault it is a
    *filename*, resolved by basename. For a file-per-code scheme those agree,
    and an alias makes the short URL agree too."""
    for scheme in cfg.schemes.values():
        if scheme.render != "index" or path.parent != scheme.dir:
            continue
        number = scheme.number_of(path)
        if number is not None:
            return scheme.code(number)
    return None


def record_line(meta: dict, source: Path) -> str:
    """The frontmatter facts, rendered where a reader (and a graph) can see
    them: status, when it was filed, the issue, and what influenced it.

    Composed with wikilinks and handed to the resolver rather than spelled
    here — the fixer owns every target in this record, and a second speller
    would be the drift DP-4 names."""
    bits = []
    if status := str(meta.get("status", "")).strip():
        bits.append(f"**Status** {status}")
    # Shown only when it isn't 1, the same rule the index follows (ADR-016).
    # A version that isn't a number is somebody's mistake, not this function's
    # to interpret — it is shown as written and the lint says so.
    if (version := meta.get("version")) and str(version).strip() != "1":
        bits.append(f"**Version** {version}")
    if date := str(meta.get("date", "")).strip():
        bits.append(f"**Filed** {date}")
    # `issue: '#21, #23'` is a real shape in this record, so the separator is
    # read out of the field rather than assumed to be a space.
    if issues := re.findall(r"#\d+", str(meta.get("issue", ""))):
        bits.append("**Issue** "
                    + " · ".join(f"[[{issue}]]" for issue in issues))
    influenced = [str(c).strip() for c in (meta.get("influenced_by") or [])]
    if influenced:
        codes = " · ".join(f"[[{code}]]" for code in influenced if code)
        bits.append(f"**Influenced by** {codes}")
    if not bits:
        return ""
    expanded, _ = doc_refs.expand_wikilinks("> " + " · ".join(bits), source)
    return expanded


def _insert_after_title(body: str, line: str) -> str:
    """Put the record line under the document's `# ` heading, or at the top
    when there isn't one. A superseded decision announces itself above the
    fold or not at all."""
    if not line:
        return body
    for match in re.finditer(r"^# .+$", body, re.MULTILINE):
        cut = match.end()
        return body[:cut] + "\n\n" + line + body[cut:]
    return line + "\n\n" + body


def split_frontmatter(text: str) -> tuple[str | None, str]:
    """(raw YAML, body). `None` for the YAML when there is no frontmatter —
    a generated view has none, and is copied through untouched."""
    if not text.startswith("---\n"):
        return None, text
    end = text.find("\n---\n", 3)
    if end == -1:
        return None, text
    return text[4:end + 1], text[end + 5:]


def _with_alias(front: str, alias: str | None) -> str:
    if not alias:
        return front
    return front.rstrip("\n") + f'\naliases:\n- "{alias}"\n'


def _retarget(text: str, source: Path, cfg, published: set[Path],
              staged_assets: dict[Path, Path], report: Report) -> str:
    """Send every relative link that leaves the published set somewhere real.

    An image is staged so it renders; anything else — a workflow, the scaffold,
    the licence — becomes a link at the repository, because the site is a view
    of the record and those files are the record's subject, not its pages."""
    site = cfg.site
    rel_source = cfg.rel(source)
    # Code is quoted, not asserted — the same rule the reference lint runs on
    # (ADR-008). A path inside a fence is a specimen, and "re-pointing" it
    # would rewrite the example the prose is teaching.
    quoted = doc_refs.code_spans(text)

    def fix(match: re.Match) -> str:
        target = match.group(1)
        if any(a <= match.start() < b for a, b in quoted):
            return target
        if NOT_A_PATH & set(target):
            return target
        path_part, sep, fragment = target.partition("#")
        if not path_part:
            return target
        try:
            resolved = (source.parent / path_part).resolve()
            inside = resolved.relative_to(cfg.root.resolve())
        except (ValueError, OSError):
            return target
        absolute = cfg.root / inside
        if absolute in published or absolute.is_dir():
            return target
        if not absolute.exists():
            report.unplaced.append(f"{rel_source} → {target}")
            return target
        if absolute.suffix.lower() in IMAGE_SUFFIXES:
            staged_assets[absolute] = inside
            return target
        if not site.source_url:
            report.unplaced.append(f"{rel_source} → {target}")
            return target
        report.to_source += 1
        return f"{site.source_url.rstrip('/')}/{inside.as_posix()}{sep}{fragment}"

    return RELATIVE_TARGET_RE.sub(fix, text)


def stage(out: Path, cfg=None) -> Report:
    """Write the vault and its config under `out`. Idempotent: the content
    directory is rebuilt from scratch, so a rename in the record cannot leave
    a stale page behind to be served forever."""
    cfg = cfg or current()
    out = out.resolve()
    content = out / "content"
    if content.exists():
        shutil.rmtree(content)
    content.mkdir(parents=True)

    pages = publishable(cfg, skip=out)
    published = set(pages)
    report, assets = Report(), {}

    for path in pages:
        text = path.read_text(encoding="utf-8")
        yaml_text, body = split_frontmatter(text)
        if yaml_text is not None:
            meta = parse_frontmatter(text)[0]
            line = record_line(meta, path)
            if line:
                body = _insert_after_title(body, line)
                report.lineage += 1
                # A wikilink the resolver could not expand survives as literal
                # brackets. Visible, but visible is not the same as reported —
                # the frontmatter it came from is data, which the prose scanner
                # never reads, so this is the only place it can be counted.
                if "[[" in line:
                    report.unplaced.append(
                        f"{cfg.rel(path)} → unresolved in frontmatter: "
                        + " ".join(re.findall(r"\[\[[^\]]+\]\]", line)))
            # The YAML itself is carried over verbatim — only the alias is
            # added — so a re-serialization can never quietly reorder or
            # requote a field the record is the source of truth for.
            text = ("---\n" + _with_alias(yaml_text, _alias(path, cfg))
                    + "---\n" + body)
        text = _retarget(text, path, cfg, published, assets, report)
        dest = content / destination(path, cfg)
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(text, encoding="utf-8")
        report.pages += 1

    for absolute, rel in assets.items():
        dest = content / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(absolute, dest)
        report.assets += 1

    (out / "quartz.config.ts").write_text(
        QUARTZ_CONFIG.format(title=cfg.site.title,
                             base_url=cfg.site.base_url),
        encoding="utf-8")
    return report


def run(out: str = "build/site") -> None:
    """Stage the record as a Quartz vault — `content/` plus `quartz.config.ts`
    — under OUT, ready for `npx quartz build`."""
    cfg = current()
    report = stage(Path(out) if Path(out).is_absolute() else cfg.root / out,
                   cfg)
    print(f"staged {out}/content")
    for line in report.lines():
        print(f"  {line}")
    if not cfg.site.base_url:
        print("  no site.base_url and none derivable from issue_url — "
              "the site will build with relative URLs only")


if __name__ == "__main__":
    sys.exit(run())
