# luria/vocabularies.py
"""A frontmatter field backed by a scheme-local controlled vocabulary.

    [luria.schemes.SCENE.fields.worlds]
    vocabulary = "worlds"
    many       = true
    default    = ["B"]

with `worlds.yaml` beside the records, shaped like `tags.yaml`:

    A:
      label: The unbroken line
      blurb: the trajectory where the treaty holds

The scheme directory already held two of these — `statuses.yaml` behind
`status:` (closed, one value) and `tags.yaml` behind `tags:` (open, many) —
each built as a special case. A downstream record's `worlds: [A, C]` on 37
of 75 entries, from a closed six-value set, was the third, and the one that
showed the pattern (ADR-tmpcso13).

The file is the vocabulary; the TOML table is the wiring, and the wiring is
explicit — a stray `foo.yaml` beside the records declares nothing. The
vocabulary is closed: a value not in the file is a finding, which is the
`statuses.yaml` posture, because a controlled vocabulary that accepts
unknown values is `tags:`. A default is an *effective* value — every
consumer reads an absent field as it — and never a rewrite of the source.

This module reads the file and renders the views: a block on the scheme's
index and a page per value beside the tag pages. The contract compiles the
field (`contract.for_scheme`) and the lint checks it; the config validates
the declaration at load, eagerly, like a tag group.
"""

from __future__ import annotations

from pathlib import Path

import yaml


def declared(path: Path) -> dict[str, dict]:
    """`{value: {label, blurb}}` in file order, or `{}` when there is no file."""
    if not path.exists():
        return {}
    loaded = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if not isinstance(loaded, dict):
        return {}
    return {str(k): (v or {}) for k, v in loaded.items()}


def _label(meta: dict, value: str) -> str:
    return str(meta.get("label") or value)


def _listing(scheme, docs) -> list[tuple[object, object, dict[str, list]]]:
    """Per vocabulary: (declaration, compiled field, {value: [docs]}) — the
    documents under each value by their *effective* values, so an entry
    with the field absent sits under the default."""
    from .contract import effective_values, for_scheme
    fields = {f.name: f for f in for_scheme(scheme).fields}
    out = []
    for vocab in scheme.vocabularies:
        field = fields[vocab.field]
        under: dict[str, list] = {v: [] for v in field.values}
        for doc in docs:
            for value in effective_values(field, doc.meta.get(vocab.field)) or []:
                if str(value) in under:
                    under[str(value)].append(doc)
        out.append((vocab, field, under))
    return out


def index_blocks(scheme, docs) -> str:
    """One block per vocabulary on the scheme's index, after the tag
    categories: every value linked to its page, with its count, the default
    said so. Rendered automatically rather than behind a stub placeholder
    (ADR-056): declaring the vocabulary is enough to make it visible."""
    blocks = []
    for vocab, field, under in _listing(scheme, docs):
        meta = declared(vocab.file)
        axis = vocab.field.replace("_", " ")
        chips = []
        for value in field.values:
            count = len(under[value])
            note = ", the default" if field.default and value in field.default else ""
            chips.append(f"[{_label(meta.get(value, {}), value)}]"
                         f"({vocab.name}/{value}.md) ({count}{note})")
        blocks.append(f"**By {axis}:** " + " · ".join(chips))
    return "\n\n".join(blocks)


def pages(scheme, docs) -> dict[Path, str]:
    """A page per value, beside the tag pages: `<view>/<name>/<value>.md`."""
    from .adr_index import TABLE_HEAD, prefix_for
    out: dict[Path, str] = {}
    noun = "decisions" if scheme.prefix == "ADR" else f"{scheme.prefix} documents"
    for vocab, field, under in _listing(scheme, docs):
        meta = declared(vocab.file)
        where = scheme.vocab_dir(vocab.name)
        prefix = prefix_for(scheme, where)
        for value in field.values:
            listed = under[value]
            label = _label(meta.get(value, {}), value)
            raw = str(meta.get(value, {}).get("blurb") or "")
            blurb = f" — {raw}" if raw else ""
            default = (f" — the default when `{vocab.field}:` is absent"
                       if field.default and value in field.default else "")
            out[where / f"{value}.md"] = (
                f"<!-- GENERATED by `luria index` — do not edit. -->\n\n"
                f"# {scheme.prefix}s with `{vocab.field}` `{value}`\n\n"
                f"**{label}**{blurb}.\n\n"
                f"{len(listed)} of {len(docs)} {noun}{default}. "
                f"Back to the [full index](../README.md).\n\n"
                + TABLE_HEAD
                + "\n".join(a.row(prefix=prefix) for a in listed)
                + "\n")
    return out
